import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Sinonim kata 'AKURAT' adalah...",
      optionA: "Cermat",
      optionB: "Sembarangan",
      optionC: "Lambat",
      optionD: "Kasar",
      optionE: "Salah",
      correctAnswer: "A",
      explanation: "Akurat berarti tepat/cermat. Sinonim terdekat: cermat, teliti, presisi.",
    },
    {
      question: "Antonim kata 'KENDALA' adalah...",
      optionA: "Hambatan",
      optionB: "Pendukung",
      optionC: "Rintangan",
      optionD: "Tantangan",
      optionE: "Beban",
      correctAnswer: "B",
      explanation: "Kendala = halangan. Lawan kata: pendukung/penolong/pelancar.",
    },
    {
      question: "GURU : SEKOLAH = DOKTER : ...",
      optionA: "Pasien",
      optionB: "Obat",
      optionC: "Rumah Sakit",
      optionD: "Stetoskop",
      optionE: "Klinik gigi",
      correctAnswer: "C",
      explanation: "Guru bekerja di sekolah, maka dokter bekerja di rumah sakit. Hubungan: profesi-tempat kerja utama.",
    },
    {
      question: "Sinonim 'INTERVENSI' adalah...",
      optionA: "Diam",
      optionB: "Campur tangan",
      optionC: "Penolakan",
      optionD: "Pengabaian",
      optionE: "Pendiaman",
      correctAnswer: "B",
      explanation: "Intervensi = campur tangan, ikut serta dalam suatu urusan untuk mempengaruhi.",
    },
    {
      question: "PADI : BERAS = TEBU : ...",
      optionA: "Manis",
      optionB: "Petani",
      optionC: "Gula",
      optionD: "Sawah",
      optionE: "Sirup",
      correctAnswer: "C",
      explanation: "Padi diolah jadi beras, tebu diolah jadi gula. Hubungan: bahan baku → produk olahan.",
    },
    {
      question: "Antonim 'EKSPLISIT' adalah...",
      optionA: "Jelas",
      optionB: "Tegas",
      optionC: "Implisit",
      optionD: "Terang",
      optionE: "Pasti",
      correctAnswer: "C",
      explanation: "Eksplisit = jelas/terang-terangan. Antonim: implisit (tersirat/tidak langsung).",
    },
    {
      question: "Sinonim 'KOLABORASI' adalah...",
      optionA: "Persaingan",
      optionB: "Kerjasama",
      optionC: "Pertentangan",
      optionD: "Konfrontasi",
      optionE: "Pengasingan",
      correctAnswer: "B",
      explanation: "Kolaborasi = bekerja bersama untuk tujuan yang sama. Sinonim: kerjasama, sinergi.",
    },
    {
      question: "BUKU : PENULIS = LUKISAN : ...",
      optionA: "Kanvas",
      optionB: "Cat",
      optionC: "Pelukis",
      optionD: "Galeri",
      optionE: "Pameran",
      correctAnswer: "C",
      explanation: "Buku dihasilkan penulis, lukisan dihasilkan pelukis. Hubungan: karya → pencipta.",
    },
    {
      question: "Antonim 'OPTIMIS' adalah...",
      optionA: "Yakin",
      optionB: "Pesimis",
      optionC: "Antusias",
      optionD: "Bersemangat",
      optionE: "Positif",
      correctAnswer: "B",
      explanation: "Optimis = yakin pada hal positif. Lawan: pesimis (cenderung melihat hal negatif).",
    },
    {
      question: "Sinonim 'MITIGASI' adalah...",
      optionA: "Pencegahan",
      optionB: "Pemeliharaan",
      optionC: "Pengabaian",
      optionD: "Pelaksanaan",
      optionE: "Pertanggungan",
      correctAnswer: "A",
      explanation: "Mitigasi = upaya mengurangi dampak/risiko, lebih dekat ke pencegahan/penanggulangan.",
    },
  ],
  ujian: [
    {
      question: "Sinonim 'STAGNASI' adalah...",
      optionA: "Kemajuan",
      optionB: "Kemandekan",
      optionC: "Pertumbuhan",
      optionD: "Perubahan",
      optionE: "Lonjakan",
      correctAnswer: "B",
      explanation: "Stagnasi = keadaan tidak berkembang/diam. Sinonim: kemandekan, kebuntuan.",
    },
    {
      question: "Antonim 'KONKRET' adalah...",
      optionA: "Nyata",
      optionB: "Abstrak",
      optionC: "Padat",
      optionD: "Jelas",
      optionE: "Pasti",
      correctAnswer: "B",
      explanation: "Konkret = berwujud nyata. Antonim: abstrak (tidak berwujud, hanya konsep).",
    },
    {
      question: "DOKTER : PASIEN = PENGACARA : ...",
      optionA: "Hakim",
      optionB: "Klien",
      optionC: "Pengadilan",
      optionD: "Polisi",
      optionE: "Saksi",
      correctAnswer: "B",
      explanation: "Dokter melayani pasien, pengacara melayani klien. Hubungan: profesi → pihak yang dilayani.",
    },
    {
      question: "Sinonim 'EKUIVALEN' adalah...",
      optionA: "Berbeda",
      optionB: "Setara/sebanding",
      optionC: "Ganda",
      optionD: "Bertentangan",
      optionE: "Tidak terkait",
      correctAnswer: "B",
      explanation: "Ekuivalen berasal dari equivalent = setara/sebanding nilainya.",
    },
    {
      question: "Antonim 'PROGRESIF' adalah...",
      optionA: "Maju",
      optionB: "Modern",
      optionC: "Konservatif/tradisional",
      optionD: "Dinamis",
      optionE: "Berkembang",
      correctAnswer: "C",
      explanation: "Progresif = mendorong perubahan ke arah maju. Antonim: konservatif (mempertahankan yang lama).",
    },
    {
      question: "BURUNG : SAYAP = IKAN : ...",
      optionA: "Air",
      optionB: "Kolam",
      optionC: "Sirip",
      optionD: "Insang",
      optionE: "Sisik",
      correctAnswer: "C",
      explanation: "Burung bergerak/terbang dengan sayap, ikan bergerak/berenang dengan sirip. Hubungan: organ → fungsi gerak.",
    },
    {
      question: "Sinonim 'INHEREN' adalah...",
      optionA: "Lepas",
      optionB: "Melekat/sudah menjadi sifat",
      optionC: "Terpisah",
      optionD: "Tambahan",
      optionE: "Pinggir",
      correctAnswer: "B",
      explanation: "Inheren = melekat/menyatu sejak awal pada sesuatu, sudah menjadi sifat dasarnya.",
    },
    {
      question: "Sinonim 'PARSIAL' adalah...",
      optionA: "Penuh",
      optionB: "Sebagian/parsial",
      optionC: "Total",
      optionD: "Final",
      optionE: "Akhir",
      correctAnswer: "B",
      explanation: "Parsial = bagian/sebagian, tidak menyeluruh. Sinonim: parsial, separuh, fragmental.",
    },
    {
      question: "Antonim 'KOHESIF' adalah...",
      optionA: "Bersatu",
      optionB: "Terpadu",
      optionC: "Terpecah/disjungtif",
      optionD: "Lengket",
      optionE: "Erat",
      correctAnswer: "C",
      explanation: "Kohesif = saling melekat/bersatu. Antonim: terpecah, terpisah, disjungtif.",
    },
    {
      question: "JARUM : BENANG = PALU : ...",
      optionA: "Batu",
      optionB: "Paku",
      optionC: "Kayu",
      optionD: "Tukang",
      optionE: "Gergaji",
      correctAnswer: "B",
      explanation: "Jarum dipakai bersama benang (untuk menjahit), palu dipakai bersama paku (untuk memaku).",
    },
    {
      question: "Sinonim 'ANTAGONIS' adalah...",
      optionA: "Pendukung",
      optionB: "Penentang/lawan",
      optionC: "Sahabat",
      optionD: "Saksi",
      optionE: "Penonton",
      correctAnswer: "B",
      explanation: "Antagonis = tokoh/pihak yang berlawanan; lawan dari protagonis.",
    },
    {
      question: "Antonim 'LANCAR' adalah...",
      optionA: "Cepat",
      optionB: "Tersendat",
      optionC: "Mengalir",
      optionD: "Mulus",
      optionE: "Bebas",
      correctAnswer: "B",
      explanation: "Lancar = berjalan tanpa hambatan. Antonim: tersendat/macet/tersumbat.",
    },
    {
      question: "Sinonim 'DEPRESI' (ekonomi) adalah...",
      optionA: "Kemakmuran",
      optionB: "Lonjakan",
      optionC: "Resesi/keterpurukan ekonomi",
      optionD: "Booming",
      optionE: "Pertumbuhan",
      correctAnswer: "C",
      explanation: "Depresi ekonomi = kemerosotan ekonomi parah dan berkepanjangan, mirip resesi tetapi lebih dalam.",
    },
    {
      question: "PENA : TINTA = MOBIL : ...",
      optionA: "Roda",
      optionB: "Sopir",
      optionC: "Bensin",
      optionD: "Jalan",
      optionE: "Klakson",
      correctAnswer: "C",
      explanation: "Pena membutuhkan tinta untuk berfungsi, mobil membutuhkan bensin untuk berfungsi. Hubungan: alat → bahan bakarnya.",
    },
    {
      question: "Sinonim 'SUBSTANSI' adalah...",
      optionA: "Pembungkus",
      optionB: "Inti/pokok",
      optionC: "Akhir",
      optionD: "Lampiran",
      optionE: "Catatan kaki",
      correctAnswer: "B",
      explanation: "Substansi = inti/hakikat dari sesuatu. Sinonim: pokok, esensi, inti.",
    },
    {
      question: "Antonim 'EKSPANSI' adalah...",
      optionA: "Pembesaran",
      optionB: "Penyusutan/kontraksi",
      optionC: "Pertumbuhan",
      optionD: "Perluasan",
      optionE: "Penambahan",
      correctAnswer: "B",
      explanation: "Ekspansi = perluasan/pembesaran. Antonim: kontraksi/penyusutan.",
    },
    {
      question: "Sinonim 'AMBIGU' adalah...",
      optionA: "Jelas",
      optionB: "Bermakna ganda/taksa",
      optionC: "Tegas",
      optionD: "Sederhana",
      optionE: "Final",
      correctAnswer: "B",
      explanation: "Ambigu = memiliki lebih dari satu makna; taksa, mendua arti.",
    },
    {
      question: "DINGIN : MENGGIGIL = LELAH : ...",
      optionA: "Tidur",
      optionB: "Mengantuk",
      optionC: "Beristirahat",
      optionD: "Lemas",
      optionE: "Berlari",
      correctAnswer: "D",
      explanation: "Dingin → reaksi tubuh: menggigil. Lelah → reaksi tubuh: lemas. Hubungan: kondisi → reaksi tubuh.",
    },
    {
      question: "Sinonim 'KOLOSAL' adalah...",
      optionA: "Kecil",
      optionB: "Sangat besar/raksasa",
      optionC: "Sederhana",
      optionD: "Wajar",
      optionE: "Standar",
      correctAnswer: "B",
      explanation: "Kolosal = sangat besar/megah/raksasa, biasanya untuk skala produksi atau bangunan.",
    },
    {
      question: "Antonim 'EFISIEN' adalah...",
      optionA: "Hemat",
      optionB: "Boros/tidak hemat",
      optionC: "Cepat",
      optionD: "Tepat",
      optionE: "Akurat",
      correctAnswer: "B",
      explanation: "Efisien = hemat sumber daya untuk hasil maksimal. Antonim: boros/tidak efisien.",
    },
    {
      question: "Sinonim 'KONSENSUS' adalah...",
      optionA: "Pertentangan",
      optionB: "Kesepakatan bersama",
      optionC: "Voting",
      optionD: "Penolakan",
      optionE: "Tunggal",
      correctAnswer: "B",
      explanation: "Konsensus = kesepakatan/kemufakatan bersama melalui musyawarah.",
    },
    {
      question: "GEMPA : SEISMOGRAF = SUHU : ...",
      optionA: "Termos",
      optionB: "Termometer",
      optionC: "Barometer",
      optionD: "Higrometer",
      optionE: "Speedometer",
      correctAnswer: "B",
      explanation: "Gempa diukur seismograf, suhu diukur termometer. Hubungan: fenomena → alat ukur.",
    },
    {
      question: "Sinonim 'ALOKASI' adalah...",
      optionA: "Pengumpulan",
      optionB: "Pembagian/penjatahan",
      optionC: "Pembuangan",
      optionD: "Penghapusan",
      optionE: "Pemeriksaan",
      correctAnswer: "B",
      explanation: "Alokasi = penjatahan/penempatan sumber daya untuk tujuan tertentu.",
    },
    {
      question: "Antonim 'EKSTRINSIK' adalah...",
      optionA: "Luar",
      optionB: "Intrinsik (dari dalam)",
      optionC: "Tambahan",
      optionD: "Luaran",
      optionE: "Pinjaman",
      correctAnswer: "B",
      explanation: "Ekstrinsik = berasal dari luar. Antonim: intrinsik (berasal dari dalam diri).",
    },
    {
      question: "Sinonim 'INSINUASI' adalah...",
      optionA: "Pujian terbuka",
      optionB: "Sindiran terselubung",
      optionC: "Permintaan langsung",
      optionD: "Perintah keras",
      optionE: "Tawaran",
      correctAnswer: "B",
      explanation: "Insinuasi = sindiran/celaan secara tidak langsung; menyindir tanpa menyebut sasaran secara terbuka.",
    },
    {
      question: "BUKU : PERPUSTAKAAN = ARSIP : ...",
      optionA: "Lemari",
      optionB: "Depot Arsip / Arsip Nasional",
      optionC: "Kertas",
      optionD: "Stempel",
      optionE: "Map",
      correctAnswer: "B",
      explanation: "Buku disimpan di perpustakaan, arsip disimpan di depot arsip / lembaga arsip. Hubungan: dokumen → tempat penyimpanan resmi.",
    },
    {
      question: "Sinonim 'NIRLABA' adalah...",
      optionA: "Mengejar untung",
      optionB: "Tidak berorientasi keuntungan",
      optionC: "Komersil",
      optionD: "Modal kecil",
      optionE: "Tunai",
      correctAnswer: "B",
      explanation: "Nirlaba = tidak mencari keuntungan; istilah untuk organisasi non-profit.",
    },
    {
      question: "Antonim 'TRANSPARAN' adalah...",
      optionA: "Jelas",
      optionB: "Tertutup/buram",
      optionC: "Terbuka",
      optionD: "Akuntabel",
      optionE: "Bebas",
      correctAnswer: "B",
      explanation: "Transparan = terbuka, dapat dilihat. Antonim: buram/tertutup/tidak transparan.",
    },
    {
      question: "Sinonim 'PROVOKATIF' adalah...",
      optionA: "Menenangkan",
      optionB: "Memancing reaksi/emosi",
      optionC: "Damai",
      optionD: "Sederhana",
      optionE: "Diam",
      correctAnswer: "B",
      explanation: "Provokatif = bersifat memancing/menyulut reaksi atau emosi pihak lain.",
    },
    {
      question: "PENGUSAHA : LABA = ATLET : ...",
      optionA: "Bola",
      optionB: "Stadion",
      optionC: "Medali/prestasi",
      optionD: "Latihan",
      optionE: "Pelatih",
      correctAnswer: "C",
      explanation: "Pengusaha mengejar laba (output utama), atlet mengejar prestasi/medali. Hubungan: profesi → hasil utama yang dikejar.",
    },
  ],
};

export default bank;
