import type { QuestionBank } from "../types";

// Catatan: untuk demo platform, soal figural disajikan dalam bentuk deskripsi
// teks pola dan analogi posisi. Pada implementasi produksi, soal figural
// akan dilengkapi dengan rendering SVG/gambar di frontend.

const bank: QuestionBank = {
  latihan: [
    {
      question: "Pola: lingkaran, segitiga, lingkaran, segitiga, lingkaran, ... Berikutnya adalah...",
      optionA: "Lingkaran",
      optionB: "Segitiga",
      optionC: "Persegi",
      optionD: "Bintang",
      optionE: "Tidak ada",
      correctAnswer: "B",
      explanation: "Pola berselang-seling lingkaran-segitiga. Setelah lingkaran ke-3 berikutnya segitiga.",
    },
    {
      question: "Sebuah persegi diputar 90° searah jarum jam, kemudian 180°. Total rotasi posisinya...",
      optionA: "0°",
      optionB: "90°",
      optionC: "180°",
      optionD: "270°",
      optionE: "360°",
      correctAnswer: "D",
      explanation: "90° + 180° = 270° searah jarum jam.",
    },
    {
      question: "Jika sebuah huruf 'F' dicerminkan vertikal, hasilnya menyerupai...",
      optionA: "Huruf F biasa",
      optionB: "Huruf F terbalik horizontal (mirror)",
      optionC: "Huruf E",
      optionD: "Huruf P",
      optionE: "Huruf L",
      correctAnswer: "B",
      explanation: "Pencerminan vertikal membuat huruf F menjadi mirror image — bagian palang menghadap ke kiri.",
    },
    {
      question: "Pola jumlah titik: 1, 3, 6, 10, ... berikutnya?",
      optionA: "12",
      optionB: "13",
      optionC: "15",
      optionD: "18",
      optionE: "20",
      correctAnswer: "C",
      explanation: "Bilangan segitiga: tambah 2, 3, 4, 5. 10 + 5 = 15.",
    },
    {
      question: "Kubus memiliki ... sisi.",
      optionA: "4",
      optionB: "5",
      optionC: "6",
      optionD: "8",
      optionE: "12",
      correctAnswer: "C",
      explanation: "Kubus memiliki 6 sisi (persegi), 12 rusuk, 8 titik sudut.",
    },
    {
      question: "Bayangan cermin huruf 'B' tampak menyerupai...",
      optionA: "Huruf D",
      optionB: "Huruf B terbalik (mirror image)",
      optionC: "Huruf P",
      optionD: "Huruf R",
      optionE: "Huruf E",
      correctAnswer: "B",
      explanation: "Cermin menghasilkan refleksi — huruf B yang dicerminkan menjadi 'mirror B' (bukan huruf lain).",
    },
    {
      question: "Suatu pola: △, △△, △△△, ... berikutnya?",
      optionA: "△△△",
      optionB: "△△△△",
      optionC: "△△",
      optionD: "△",
      optionE: "△△△△△",
      correctAnswer: "B",
      explanation: "Jumlah segitiga bertambah 1 tiap langkah: 1, 2, 3, 4 → empat segitiga.",
    },
    {
      question: "Jika sebuah segitiga sama sisi diputar 120°, posisinya...",
      optionA: "Berbeda total",
      optionB: "Sama persis dengan posisi awal (simetri rotasi)",
      optionC: "Terbalik",
      optionD: "Hilang",
      optionE: "Mengecil",
      correctAnswer: "B",
      explanation: "Segitiga sama sisi memiliki simetri rotasi orde 3 — rotasi 120° menghasilkan posisi identik dengan asal.",
    },
    {
      question: "Pola: ●, ●●, ●●●, ●●●●●, ... pola jumlahnya?",
      optionA: "Aritmetika",
      optionB: "Geometri",
      optionC: "Fibonacci",
      optionD: "Acak",
      optionE: "Konstan",
      correctAnswer: "C",
      explanation: "1, 2, 3, 5 — pola Fibonacci (suku berikut = jumlah dua sebelumnya).",
    },
    {
      question: "Lingkaran memiliki sumbu simetri sebanyak...",
      optionA: "1",
      optionB: "2",
      optionC: "4",
      optionD: "Hanya 8",
      optionE: "Tak terhingga",
      correctAnswer: "E",
      explanation: "Lingkaran memiliki simetri rotasi dan refleksi tak terhingga melalui setiap diameter.",
    },
  ],
  ujian: [
    {
      question: "Persegi panjang memiliki sumbu simetri lipat sebanyak...",
      optionA: "0",
      optionB: "1",
      optionC: "2",
      optionD: "3",
      optionE: "4",
      correctAnswer: "C",
      explanation: "Persegi panjang punya 2 sumbu simetri lipat: vertikal (tegak) dan horizontal (datar).",
    },
    {
      question: "Persegi memiliki sumbu simetri lipat sebanyak...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "8",
      correctAnswer: "D",
      explanation: "Persegi punya 4 sumbu simetri: 2 melalui titik tengah sisi, 2 melalui diagonal.",
    },
    {
      question: "Banyak rusuk balok adalah...",
      optionA: "6",
      optionB: "8",
      optionC: "10",
      optionD: "12",
      optionE: "14",
      correctAnswer: "D",
      explanation: "Balok memiliki 12 rusuk: 4 panjang, 4 lebar, 4 tinggi.",
    },
    {
      question: "Banyak titik sudut limas segiempat adalah...",
      optionA: "4",
      optionB: "5",
      optionC: "6",
      optionD: "7",
      optionE: "8",
      correctAnswer: "B",
      explanation: "Limas segiempat: 4 titik sudut alas + 1 titik puncak = 5 titik sudut.",
    },
    {
      question: "Pola: 1, 4, 9, 16, 25, 36, ... berikutnya?",
      optionA: "42",
      optionB: "45",
      optionC: "49",
      optionD: "56",
      optionE: "64",
      correctAnswer: "C",
      explanation: "Bilangan kuadrat: n² → 7² = 49.",
    },
    {
      question: "Pencerminan suatu titik (3, 5) terhadap sumbu X menjadi...",
      optionA: "(−3, 5)",
      optionB: "(3, −5)",
      optionC: "(−3, −5)",
      optionD: "(5, 3)",
      optionE: "(0, 5)",
      correctAnswer: "B",
      explanation: "Cermin terhadap sumbu X: (x, y) → (x, −y). Jadi (3, 5) → (3, −5).",
    },
    {
      question: "Jaring-jaring kubus terdiri atas...",
      optionA: "4 persegi",
      optionB: "5 persegi",
      optionC: "6 persegi",
      optionD: "8 persegi",
      optionE: "12 persegi",
      correctAnswer: "C",
      explanation: "Jaring-jaring kubus = bentangan 6 sisi persegi yang dilipat membentuk kubus.",
    },
    {
      question: "Translasi titik (2, 3) sejauh (4, −1) menghasilkan titik...",
      optionA: "(6, 2)",
      optionB: "(6, 4)",
      optionC: "(2, 4)",
      optionD: "(−2, 4)",
      optionE: "(4, 2)",
      correctAnswer: "A",
      explanation: "Translasi: (x+a, y+b) = (2+4, 3−1) = (6, 2).",
    },
    {
      question: "Bangun datar yang TIDAK memiliki simetri putar adalah...",
      optionA: "Persegi",
      optionB: "Lingkaran",
      optionC: "Segitiga sama sisi",
      optionD: "Trapesium sembarang",
      optionE: "Persegi panjang",
      correctAnswer: "D",
      explanation: "Trapesium sembarang tidak punya simetri putar maupun lipat. Bangun lain memilikinya.",
    },
    {
      question: "Diagonal sisi kubus dengan rusuk 4 cm panjangnya...",
      optionA: "4 cm",
      optionB: "4√2 cm",
      optionC: "4√3 cm",
      optionD: "8 cm",
      optionE: "16 cm",
      correctAnswer: "B",
      explanation: "Diagonal sisi kubus = sisi × √2 = 4√2 cm.",
    },
    {
      question: "Diagonal ruang kubus dengan rusuk 4 cm panjangnya...",
      optionA: "4 cm",
      optionB: "4√2 cm",
      optionC: "4√3 cm",
      optionD: "8 cm",
      optionE: "16 cm",
      correctAnswer: "C",
      explanation: "Diagonal ruang kubus = sisi × √3 = 4√3 cm.",
    },
    {
      question: "Banyak segitiga yang dapat dibentuk dari 5 titik tak segaris adalah... (kombinasi)",
      optionA: "5",
      optionB: "8",
      optionC: "10",
      optionD: "15",
      optionE: "20",
      correctAnswer: "C",
      explanation: "C(5,3) = 5!/(3!·2!) = 10 segitiga.",
    },
    {
      question: "Pola: 2, 6, 12, 20, 30, 42, ... berikutnya?",
      optionA: "48",
      optionB: "52",
      optionC: "54",
      optionD: "56",
      optionE: "60",
      correctAnswer: "D",
      explanation: "Selisih: 4, 6, 8, 10, 12, 14. 42 + 14 = 56.",
    },
    {
      question: "Banyak diagonal pada segi enam (heksagon) adalah...",
      optionA: "6",
      optionB: "9",
      optionC: "12",
      optionD: "15",
      optionE: "20",
      correctAnswer: "B",
      explanation: "Rumus diagonal = n(n−3)/2 = 6×3/2 = 9.",
    },
    {
      question: "Sudut pusat lingkaran yang membentuk seperempat lingkaran adalah...",
      optionA: "45°",
      optionB: "60°",
      optionC: "90°",
      optionD: "120°",
      optionE: "180°",
      correctAnswer: "C",
      explanation: "Lingkaran penuh = 360°. Seperempat = 360°/4 = 90°.",
    },
    {
      question: "Banyak sisi pada limas segitiga (tetrahedron) adalah...",
      optionA: "3",
      optionB: "4",
      optionC: "5",
      optionD: "6",
      optionE: "8",
      correctAnswer: "B",
      explanation: "Tetrahedron memiliki 4 sisi segitiga (1 alas + 3 sisi tegak).",
    },
    {
      question: "Pola: ▲, ▲△, ▲△▲, ▲△▲△, ... berikutnya?",
      optionA: "▲△▲△▲",
      optionB: "△▲△▲△",
      optionC: "▲△▲",
      optionD: "▲▲△",
      optionE: "▲▲▲",
      correctAnswer: "A",
      explanation: "Pola berselang-seling, jumlah karakter bertambah 1 tiap langkah dimulai dari ▲.",
    },
    {
      question: "Sebuah jam menunjukkan pukul 03.00. Sudut antara jarum jam dan menit adalah...",
      optionA: "30°",
      optionB: "60°",
      optionC: "90°",
      optionD: "120°",
      optionE: "180°",
      correctAnswer: "C",
      explanation: "Pukul 03.00: jarum menit di angka 12, jarum jam di angka 3 (3 jam × 30°/jam = 90°).",
    },
    {
      question: "Pola: ●○●○●●●○○○●●●●●○○○○○. Pola berikutnya jika diteruskan...",
      optionA: "●×6, ○×6",
      optionB: "●×7, ○×7",
      optionC: "●×4, ○×4",
      optionD: "Acak",
      optionE: "Berhenti",
      correctAnswer: "B",
      explanation: "Jumlah ● dan ○ bertambah 1 tiap putaran (1,1, 3,3, 5,5, …) → 7,7.",
    },
    {
      question: "Bayangan titik (4, −2) setelah dirotasi 90° berlawanan jarum jam terhadap titik asal adalah...",
      optionA: "(−4, 2)",
      optionB: "(2, 4)",
      optionC: "(−2, −4)",
      optionD: "(2, −4)",
      optionE: "(4, 2)",
      correctAnswer: "B",
      explanation: "Rotasi 90° berlawanan jarum jam: (x, y) → (−y, x). (4, −2) → (2, 4).",
    },
    {
      question: "Jumlah sudut dalam segi-n adalah (n−2)×180°. Untuk segi-6 (heksagon), totalnya...",
      optionA: "360°",
      optionB: "540°",
      optionC: "720°",
      optionD: "900°",
      optionE: "1080°",
      correctAnswer: "C",
      explanation: "(6−2)×180 = 4×180 = 720°.",
    },
    {
      question: "Banyaknya tutup penuh sebuah kubus dengan kubus mini berukuran setengah-rusuknya adalah...",
      optionA: "2",
      optionB: "4",
      optionC: "6",
      optionD: "8",
      optionE: "16",
      correctAnswer: "D",
      explanation: "Membagi tiap rusuk menjadi 2 menghasilkan 2³ = 8 kubus mini.",
    },
    {
      question: "Pola: 1, 8, 27, 64, ... berikutnya?",
      optionA: "100",
      optionB: "121",
      optionC: "125",
      optionD: "144",
      optionE: "216",
      correctAnswer: "C",
      explanation: "Pola pangkat tiga: n³ → 5³ = 125.",
    },
    {
      question: "Jumlah sisi prisma segitiga adalah...",
      optionA: "3",
      optionB: "4",
      optionC: "5",
      optionD: "6",
      optionE: "8",
      correctAnswer: "C",
      explanation: "Prisma segitiga: 2 alas segitiga + 3 sisi tegak persegi panjang = 5 sisi.",
    },
    {
      question: "Banyak rusuk limas segi lima adalah...",
      optionA: "5",
      optionB: "8",
      optionC: "10",
      optionD: "12",
      optionE: "15",
      correctAnswer: "C",
      explanation: "Limas segi lima: 5 rusuk alas + 5 rusuk tegak = 10 rusuk.",
    },
    {
      question: "Pencerminan terhadap garis y = x: titik (4, 7) menjadi...",
      optionA: "(−4, 7)",
      optionB: "(7, 4)",
      optionC: "(4, −7)",
      optionD: "(−4, −7)",
      optionE: "(7, −4)",
      correctAnswer: "B",
      explanation: "Cermin terhadap y = x: (x, y) → (y, x). Maka (4, 7) → (7, 4).",
    },
    {
      question: "Sudut interior segi lima beraturan adalah...",
      optionA: "60°",
      optionB: "72°",
      optionC: "90°",
      optionD: "108°",
      optionE: "120°",
      correctAnswer: "D",
      explanation: "Sudut interior = (n−2)×180°/n = 3×180/5 = 108°.",
    },
    {
      question: "Bola memiliki ... sumbu simetri.",
      optionA: "0",
      optionB: "1",
      optionC: "2",
      optionD: "Tak terhingga",
      optionE: "8",
      correctAnswer: "D",
      explanation: "Bola memiliki simetri rotasi tak terhingga terhadap setiap sumbu yang melalui pusat.",
    },
    {
      question: "Pola jumlah lingkaran dalam susunan segitiga: 1, 3, 6, 10, 15, ... berikutnya?",
      optionA: "18",
      optionB: "20",
      optionC: "21",
      optionD: "25",
      optionE: "28",
      correctAnswer: "C",
      explanation: "Bilangan segitiga: tambah berurutan 2, 3, 4, 5, 6. 15 + 6 = 21.",
    },
    {
      question: "Sebuah segitiga sama kaki memiliki sudut puncak 40°. Sudut alasnya masing-masing...",
      optionA: "60°",
      optionB: "70°",
      optionC: "80°",
      optionD: "90°",
      optionE: "100°",
      correctAnswer: "B",
      explanation: "Total sudut segitiga = 180°. Sudut alas = (180 − 40)/2 = 70° per sudut.",
    },
  ],
};

export default bank;
