import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Berapakah hasil dari 25% × 80 + 30?",
      optionA: "40",
      optionB: "45",
      optionC: "50",
      optionD: "55",
      optionE: "60",
      correctAnswer: "C",
      explanation: "25% × 80 = 20, lalu 20 + 30 = 50.",
    },
    {
      question: "Deret: 2, 4, 8, 16, ... berikutnya adalah...",
      optionA: "20",
      optionB: "24",
      optionC: "28",
      optionD: "32",
      optionE: "64",
      correctAnswer: "D",
      explanation: "Setiap suku dikali 2: 16 × 2 = 32.",
    },
    {
      question: "Jika 3x + 5 = 20, maka x = ...",
      optionA: "3",
      optionB: "4",
      optionC: "5",
      optionD: "6",
      optionE: "7",
      correctAnswer: "C",
      explanation: "3x = 20 − 5 = 15, sehingga x = 15 ÷ 3 = 5.",
    },
    {
      question: "Sebuah barang dijual Rp 240.000 setelah diskon 20%. Harga aslinya...",
      optionA: "Rp 280.000",
      optionB: "Rp 288.000",
      optionC: "Rp 300.000",
      optionD: "Rp 320.000",
      optionE: "Rp 360.000",
      correctAnswer: "C",
      explanation: "Harga setelah diskon = 80% × harga asli. 240.000 = 0,8 × HA → HA = 300.000.",
    },
    {
      question: "Rata-rata 5 angka adalah 14. Jika ditambah 1 angka, rata-ratanya jadi 15. Angka tersebut...",
      optionA: "18",
      optionB: "19",
      optionC: "20",
      optionD: "21",
      optionE: "22",
      correctAnswer: "C",
      explanation: "Total awal = 5×14 = 70. Total baru = 6×15 = 90. Angka baru = 90 − 70 = 20.",
    },
    {
      question: "Deret: 1, 4, 9, 16, ... berikutnya...",
      optionA: "20",
      optionB: "24",
      optionC: "25",
      optionD: "30",
      optionE: "36",
      correctAnswer: "C",
      explanation: "Pola kuadrat: 1², 2², 3², 4², 5² = 25.",
    },
    {
      question: "Jika 2 pekerja menyelesaikan tugas dalam 6 hari, berapa hari jika ada 3 pekerja?",
      optionA: "2",
      optionB: "3",
      optionC: "4",
      optionD: "5",
      optionE: "6",
      correctAnswer: "C",
      explanation: "Total man-hari = 2×6 = 12. Dengan 3 pekerja: 12 ÷ 3 = 4 hari.",
    },
    {
      question: "Berapakah 2/3 dari 1/2 dari 60?",
      optionA: "10",
      optionB: "15",
      optionC: "20",
      optionD: "25",
      optionE: "30",
      correctAnswer: "C",
      explanation: "1/2 × 60 = 30, lalu 2/3 × 30 = 20.",
    },
    {
      question: "Deret: 3, 6, 11, 18, 27, ... berikutnya...",
      optionA: "32",
      optionB: "34",
      optionC: "36",
      optionD: "38",
      optionE: "40",
      correctAnswer: "D",
      explanation: "Selisih: 3, 5, 7, 9, 11 (bilangan ganjil naik). 27 + 11 = 38.",
    },
    {
      question: "Jika harga 4 buku Rp 60.000, maka harga 7 buku adalah...",
      optionA: "Rp 95.000",
      optionB: "Rp 100.000",
      optionC: "Rp 105.000",
      optionD: "Rp 110.000",
      optionE: "Rp 120.000",
      correctAnswer: "C",
      explanation: "Harga per buku = 60.000 ÷ 4 = 15.000. 7 buku = 7 × 15.000 = 105.000.",
    },
  ],
  ujian: [
    {
      question: "Hasil dari (15 + 5) × 3 − 10 = ...",
      optionA: "40",
      optionB: "45",
      optionC: "50",
      optionD: "55",
      optionE: "60",
      correctAnswer: "C",
      explanation: "(15+5)×3 − 10 = 20×3 − 10 = 60 − 10 = 50.",
    },
    {
      question: "Berapa 15% dari 240?",
      optionA: "30",
      optionB: "32",
      optionC: "36",
      optionD: "40",
      optionE: "48",
      correctAnswer: "C",
      explanation: "15% × 240 = 0,15 × 240 = 36.",
    },
    {
      question: "Deret: 5, 10, 20, 40, ... berikutnya?",
      optionA: "60",
      optionB: "70",
      optionC: "80",
      optionD: "100",
      optionE: "120",
      correctAnswer: "C",
      explanation: "Setiap suku dikali 2: 40 × 2 = 80.",
    },
    {
      question: "Bilangan 24 dan 36 memiliki KPK...",
      optionA: "48",
      optionB: "60",
      optionC: "72",
      optionD: "84",
      optionE: "96",
      correctAnswer: "C",
      explanation: "24=2³×3, 36=2²×3². KPK = 2³×3² = 8×9 = 72.",
    },
    {
      question: "FPB dari 18 dan 24 adalah...",
      optionA: "2",
      optionB: "3",
      optionC: "6",
      optionD: "9",
      optionE: "12",
      correctAnswer: "C",
      explanation: "18=2×3², 24=2³×3. FPB = 2×3 = 6.",
    },
    {
      question: "Sebuah segitiga memiliki alas 10 cm dan tinggi 6 cm. Luasnya...",
      optionA: "16 cm²",
      optionB: "30 cm²",
      optionC: "60 cm²",
      optionD: "16 cm",
      optionE: "30 cm",
      correctAnswer: "B",
      explanation: "L = ½ × alas × tinggi = ½ × 10 × 6 = 30 cm².",
    },
    {
      question: "Jika 5 mesin menghasilkan 100 unit dalam 4 jam, berapa unit dihasilkan 8 mesin dalam 6 jam?",
      optionA: "180",
      optionB: "200",
      optionC: "220",
      optionD: "240",
      optionE: "280",
      correctAnswer: "D",
      explanation: "Per mesin per jam = 100÷(5×4) = 5 unit. 8×6×5 = 240 unit.",
    },
    {
      question: "Deret: 2, 3, 5, 8, 13, ... berikutnya?",
      optionA: "18",
      optionB: "20",
      optionC: "21",
      optionD: "23",
      optionE: "25",
      correctAnswer: "C",
      explanation: "Pola Fibonacci: tiap suku = jumlah dua suku sebelumnya. 8+13 = 21.",
    },
    {
      question: "Jika x² = 49 dan x positif, maka x = ...",
      optionA: "5",
      optionB: "6",
      optionC: "7",
      optionD: "8",
      optionE: "9",
      correctAnswer: "C",
      explanation: "√49 = 7 (positif diambil).",
    },
    {
      question: "Sebuah persegi memiliki keliling 36 cm. Luasnya...",
      optionA: "64 cm²",
      optionB: "72 cm²",
      optionC: "81 cm²",
      optionD: "100 cm²",
      optionE: "121 cm²",
      correctAnswer: "C",
      explanation: "Sisi = 36÷4 = 9 cm. Luas = 9² = 81 cm².",
    },
    {
      question: "Sebuah mobil menempuh 240 km dalam 4 jam. Kecepatan rata-ratanya...",
      optionA: "50 km/jam",
      optionB: "55 km/jam",
      optionC: "60 km/jam",
      optionD: "65 km/jam",
      optionE: "70 km/jam",
      correctAnswer: "C",
      explanation: "Kecepatan = jarak ÷ waktu = 240 ÷ 4 = 60 km/jam.",
    },
    {
      question: "Diskon 25% pada harga Rp 80.000 menjadi...",
      optionA: "Rp 50.000",
      optionB: "Rp 55.000",
      optionC: "Rp 60.000",
      optionD: "Rp 65.000",
      optionE: "Rp 70.000",
      correctAnswer: "C",
      explanation: "Diskon = 25% × 80.000 = 20.000. Harga akhir = 80.000 − 20.000 = 60.000.",
    },
    {
      question: "Deret: 100, 90, 81, 73, ... berikutnya?",
      optionA: "64",
      optionB: "65",
      optionC: "66",
      optionD: "67",
      optionE: "68",
      correctAnswer: "C",
      explanation: "Selisih: 10, 9, 8, 7. 73 − 7 = 66.",
    },
    {
      question: "Jika a + b = 12 dan a − b = 4, maka a × b = ...",
      optionA: "24",
      optionB: "28",
      optionC: "32",
      optionD: "36",
      optionE: "40",
      correctAnswer: "C",
      explanation: "a = 8, b = 4. a×b = 32.",
    },
    {
      question: "Berapa banyak bilangan prima antara 10 dan 30?",
      optionA: "4",
      optionB: "5",
      optionC: "6",
      optionD: "7",
      optionE: "8",
      correctAnswer: "C",
      explanation: "11, 13, 17, 19, 23, 29 — total 6 bilangan prima.",
    },
    {
      question: "Sebuah lingkaran memiliki jari-jari 7 cm. Luasnya (π = 22/7)...",
      optionA: "44 cm²",
      optionB: "88 cm²",
      optionC: "144 cm²",
      optionD: "154 cm²",
      optionE: "196 cm²",
      correctAnswer: "D",
      explanation: "L = π × r² = (22/7) × 49 = 154 cm².",
    },
    {
      question: "Jika 40% siswa adalah perempuan dan jumlah perempuan 80, total siswa...",
      optionA: "150",
      optionB: "180",
      optionC: "200",
      optionD: "220",
      optionE: "250",
      correctAnswer: "C",
      explanation: "40% × T = 80 → T = 80 ÷ 0,4 = 200.",
    },
    {
      question: "Deret: 1, 1, 2, 3, 5, 8, ... berikutnya?",
      optionA: "10",
      optionB: "11",
      optionC: "12",
      optionD: "13",
      optionE: "14",
      correctAnswer: "D",
      explanation: "Fibonacci: 5+8 = 13.",
    },
    {
      question: "Berapakah 3⁴?",
      optionA: "27",
      optionB: "64",
      optionC: "81",
      optionD: "108",
      optionE: "256",
      correctAnswer: "C",
      explanation: "3⁴ = 3×3×3×3 = 81.",
    },
    {
      question: "Jika rata-rata 4 angka adalah 12, jumlah keempat angka tersebut...",
      optionA: "36",
      optionB: "40",
      optionC: "44",
      optionD: "48",
      optionE: "52",
      correctAnswer: "D",
      explanation: "Jumlah = rata-rata × banyak data = 12 × 4 = 48.",
    },
    {
      question: "Deret: 64, 32, 16, 8, ... berikutnya?",
      optionA: "2",
      optionB: "4",
      optionC: "5",
      optionD: "6",
      optionE: "7",
      correctAnswer: "B",
      explanation: "Setiap suku dibagi 2: 8 ÷ 2 = 4.",
    },
    {
      question: "Selisih ¾ dan ⅓ adalah...",
      optionA: "1/12",
      optionB: "5/12",
      optionC: "7/12",
      optionD: "1/4",
      optionE: "1/3",
      correctAnswer: "B",
      explanation: "¾ − ⅓ = 9/12 − 4/12 = 5/12.",
    },
    {
      question: "Jika 5x − 7 = 18, maka x = ...",
      optionA: "3",
      optionB: "4",
      optionC: "5",
      optionD: "6",
      optionE: "7",
      correctAnswer: "C",
      explanation: "5x = 25 → x = 5.",
    },
    {
      question: "Deret: 2, 6, 12, 20, 30, ... berikutnya?",
      optionA: "36",
      optionB: "40",
      optionC: "42",
      optionD: "48",
      optionE: "50",
      correctAnswer: "C",
      explanation: "Selisih bertambah 2: 4, 6, 8, 10, 12. 30+12 = 42.",
    },
    {
      question: "Sebuah kotak memuat 12 buah jeruk. Berapa banyak jeruk dalam 15 kotak?",
      optionA: "150",
      optionB: "160",
      optionC: "175",
      optionD: "180",
      optionE: "190",
      correctAnswer: "D",
      explanation: "12 × 15 = 180 jeruk.",
    },
    {
      question: "Bilangan terkecil yang habis dibagi 4, 5, dan 6 adalah...",
      optionA: "30",
      optionB: "45",
      optionC: "60",
      optionD: "90",
      optionE: "120",
      correctAnswer: "C",
      explanation: "KPK(4,5,6) = 60.",
    },
    {
      question: "Selembar uang Rp 100.000 ditukar koin Rp 500. Berapa banyak koin?",
      optionA: "100",
      optionB: "150",
      optionC: "200",
      optionD: "250",
      optionE: "500",
      correctAnswer: "C",
      explanation: "100.000 ÷ 500 = 200 koin.",
    },
    {
      question: "Deret: 3, 7, 15, 31, ... berikutnya?",
      optionA: "47",
      optionB: "55",
      optionC: "63",
      optionD: "71",
      optionE: "79",
      correctAnswer: "C",
      explanation: "Pola: ×2 +1. 31×2+1 = 63.",
    },
    {
      question: "Jika sisi sebuah kubus 5 cm, volume kubus...",
      optionA: "75 cm³",
      optionB: "100 cm³",
      optionC: "125 cm³",
      optionD: "150 cm³",
      optionE: "200 cm³",
      correctAnswer: "C",
      explanation: "V = sisi³ = 5³ = 125 cm³.",
    },
    {
      question: "Sebuah toko menaikkan harga 20%, lalu memberi diskon 20%. Harga akhir terhadap awal...",
      optionA: "Sama dengan awal",
      optionB: "Lebih mahal 4%",
      optionC: "Lebih murah 4%",
      optionD: "Lebih mahal 20%",
      optionE: "Lebih murah 20%",
      correctAnswer: "C",
      explanation: "1×1,2×0,8 = 0,96 → harga akhir 96% dari awal, atau lebih murah 4%.",
    },
  ],
};

export default bank;
