import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Semua mahasiswa pandai. Budi adalah mahasiswa. Maka...",
      optionA: "Budi belum tentu pandai",
      optionB: "Budi pandai",
      optionC: "Budi pasti malas",
      optionD: "Budi bukan mahasiswa",
      optionE: "Tidak dapat disimpulkan",
      correctAnswer: "B",
      explanation: "Silogisme: premis mayor 'semua mahasiswa pandai' + premis minor 'Budi mahasiswa' → kesimpulan 'Budi pandai'.",
    },
    {
      question: "Jika hujan, jalan basah. Jalan tidak basah. Maka...",
      optionA: "Hujan",
      optionB: "Tidak hujan",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Jalan akan basah nanti",
      optionE: "Cuaca cerah",
      correctAnswer: "B",
      explanation: "Modus tollens: 'jika P maka Q' + '~Q' → '~P'. Jadi tidak hujan.",
    },
    {
      question: "Semua dokter memakai jas putih. Andi memakai jas putih. Maka...",
      optionA: "Andi pasti dokter",
      optionB: "Andi belum tentu dokter",
      optionC: "Andi bukan dokter",
      optionD: "Andi perawat",
      optionE: "Andi pasien",
      correctAnswer: "B",
      explanation: "Memakai jas putih tidak otomatis dokter — bisa apoteker, koki, dll. Jadi belum tentu Andi dokter.",
    },
    {
      question: "Hanya siswa kelas 12 yang mengikuti UN. Doni mengikuti UN. Maka...",
      optionA: "Doni kelas 12",
      optionB: "Doni belum tentu kelas 12",
      optionC: "Doni bukan siswa",
      optionD: "Doni guru",
      optionE: "Tidak dapat disimpulkan",
      correctAnswer: "A",
      explanation: "'Hanya X yang Q' artinya jika Q maka X. Doni ikut UN → Doni kelas 12.",
    },
    {
      question: "A lebih tinggi dari B. C lebih pendek dari B. Yang paling tinggi...",
      optionA: "A",
      optionB: "B",
      optionC: "C",
      optionD: "Sama tinggi",
      optionE: "Tidak dapat disimpulkan",
      correctAnswer: "A",
      explanation: "A > B dan B > C, jadi A > B > C — A paling tinggi.",
    },
    {
      question: "Semua kucing memiliki ekor. Mimi adalah kucing. Maka...",
      optionA: "Mimi memiliki ekor",
      optionB: "Mimi tidak memiliki ekor",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Mimi anjing",
      optionE: "Mimi kelinci",
      correctAnswer: "A",
      explanation: "Silogisme valid: semua kucing punya ekor + Mimi kucing → Mimi punya ekor.",
    },
    {
      question: "Jika bekerja keras, sukses. Bagas tidak sukses. Maka (jika premis benar)...",
      optionA: "Bagas bekerja keras",
      optionB: "Bagas tidak bekerja keras",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Bagas malas",
      optionE: "Bagas kaya",
      correctAnswer: "B",
      explanation: "Modus tollens: P→Q, ~Q ⊢ ~P. 'Tidak sukses' → 'tidak bekerja keras'.",
    },
    {
      question: "Beberapa burung tidak bisa terbang. Penguin adalah burung. Maka...",
      optionA: "Penguin pasti tidak bisa terbang",
      optionB: "Penguin pasti bisa terbang",
      optionC: "Penguin mungkin bisa terbang, mungkin tidak — belum dapat disimpulkan dari premis",
      optionD: "Penguin bukan burung",
      optionE: "Penguin mamalia",
      correctAnswer: "C",
      explanation: "'Beberapa' = ada minimal satu, tidak semua. Tidak bisa simpulkan penguin spesifik tanpa info tambahan dari premis.",
    },
    {
      question: "Andi lebih tua dari Budi. Caca lebih muda dari Andi tetapi lebih tua dari Budi. Urutan dari termuda ke tertua...",
      optionA: "Andi, Caca, Budi",
      optionB: "Budi, Caca, Andi",
      optionC: "Caca, Andi, Budi",
      optionD: "Budi, Andi, Caca",
      optionE: "Andi, Budi, Caca",
      correctAnswer: "B",
      explanation: "Andi > Caca > Budi (umur). Termuda → tertua: Budi, Caca, Andi.",
    },
    {
      question: "Negasi dari 'Semua siswa hadir' adalah...",
      optionA: "Tidak ada siswa yang hadir",
      optionB: "Ada siswa yang tidak hadir",
      optionC: "Semua siswa tidak hadir",
      optionD: "Hanya satu siswa hadir",
      optionE: "Setengah siswa hadir",
      correctAnswer: "B",
      explanation: "Negasi 'semua P' adalah 'ada P yang tidak'. Negasi 'semua siswa hadir' = 'ada siswa yang tidak hadir'.",
    },
  ],
  ujian: [
    {
      question: "Semua A adalah B. Semua B adalah C. Maka...",
      optionA: "Semua A adalah C",
      optionB: "Semua C adalah A",
      optionC: "Tidak ada A yang C",
      optionD: "Sebagian C bukan A",
      optionE: "Sebagian A bukan C",
      correctAnswer: "A",
      explanation: "Silogisme transitif: A⊆B, B⊆C ⊢ A⊆C. Semua A adalah C.",
    },
    {
      question: "Jika P maka Q. Q. Maka...",
      optionA: "P pasti benar",
      optionB: "P bisa benar bisa salah (afirmasi konsekuen — tidak valid)",
      optionC: "P pasti salah",
      optionD: "Tidak ada Q",
      optionE: "Tidak relevan",
      correctAnswer: "B",
      explanation: "Afirmasi konsekuen adalah kekeliruan logika. Dari P→Q dan Q tidak bisa disimpulkan P benar.",
    },
    {
      question: "Negasi 'Beberapa mahasiswa rajin' adalah...",
      optionA: "Tidak ada mahasiswa yang rajin",
      optionB: "Semua mahasiswa rajin",
      optionC: "Beberapa mahasiswa malas",
      optionD: "Semua mahasiswa malas",
      optionE: "Hanya satu yang rajin",
      correctAnswer: "A",
      explanation: "Negasi 'beberapa P' = 'tidak ada P sama sekali' = 'semua bukan P'.",
    },
    {
      question: "Tono lebih kaya dari Doni. Doni lebih kaya dari Sari. Maka...",
      optionA: "Sari paling miskin",
      optionB: "Tono paling miskin",
      optionC: "Doni paling kaya",
      optionD: "Sari = Doni",
      optionE: "Tidak dapat disimpulkan",
      correctAnswer: "A",
      explanation: "Tono > Doni > Sari → Sari paling miskin di antara mereka.",
    },
    {
      question: "Semua R adalah S. Beberapa S adalah T. Maka...",
      optionA: "Beberapa R adalah T",
      optionB: "Semua R adalah T",
      optionC: "Tidak ada R yang T",
      optionD: "Tidak dapat disimpulkan",
      optionE: "Semua T adalah R",
      correctAnswer: "D",
      explanation: "Premis 'beberapa S adalah T' bisa jadi T tersebut bukan bagian dari R. Jadi tidak dapat disimpulkan.",
    },
    {
      question: "Jika seseorang ASN, maka harus netral politik. Pak Anto tidak netral politik. Maka...",
      optionA: "Pak Anto ASN",
      optionB: "Pak Anto bukan ASN",
      optionC: "Pak Anto netral",
      optionD: "Tidak relevan",
      optionE: "Pak Anto pejabat",
      correctAnswer: "B",
      explanation: "Modus tollens: ASN→netral, ~netral → ~ASN. Pak Anto bukan ASN (jika premis benar).",
    },
    {
      question: "Negasi 'jika hujan maka basah' adalah...",
      optionA: "Hujan dan tidak basah",
      optionB: "Tidak hujan dan basah",
      optionC: "Tidak hujan atau basah",
      optionD: "Hujan dan basah",
      optionE: "Tidak hujan dan tidak basah",
      correctAnswer: "A",
      explanation: "~(P→Q) ≡ P ∧ ~Q. Negasi 'jika hujan maka basah' = 'hujan tetapi tidak basah'.",
    },
    {
      question: "Semua siswa rajin lulus ujian. Andi tidak lulus ujian. Kesimpulan paling logis...",
      optionA: "Andi tidak rajin",
      optionB: "Andi rajin",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Andi pintar",
      optionE: "Ujian sulit",
      correctAnswer: "A",
      explanation: "Modus tollens: rajin→lulus, ~lulus → ~rajin. Andi tidak rajin (kontrapositif valid).",
    },
    {
      question: "A duduk di sebelah kanan B. C di sebelah kanan A. D di sebelah kiri B. Urutan dari kiri ke kanan...",
      optionA: "D, B, A, C",
      optionB: "B, D, A, C",
      optionC: "C, A, B, D",
      optionD: "A, B, C, D",
      optionE: "D, A, B, C",
      correctAnswer: "A",
      explanation: "B-A-C berurutan kanan, D di kiri B → D, B, A, C dari kiri ke kanan.",
    },
    {
      question: "Semua P adalah Q. Tidak ada Q yang R. Maka...",
      optionA: "Semua P adalah R",
      optionB: "Tidak ada P yang R",
      optionC: "Beberapa P adalah R",
      optionD: "Semua R adalah P",
      optionE: "Tidak dapat disimpulkan",
      correctAnswer: "B",
      explanation: "P⊆Q dan Q∩R=∅ → P∩R=∅. Tidak ada P yang R.",
    },
    {
      question: "Jika x > 5 maka y > 10. Diketahui y = 8. Maka...",
      optionA: "x > 5",
      optionB: "x ≤ 5",
      optionC: "x = 5",
      optionD: "Tidak dapat disimpulkan",
      optionE: "Premis salah",
      correctAnswer: "B",
      explanation: "y = 8 < 10, berarti y > 10 salah. Modus tollens: jika x>5→y>10, ~(y>10) → ~(x>5) yaitu x ≤ 5.",
    },
    {
      question: "Semua dokter pintar. Beberapa dokter kaya. Maka...",
      optionA: "Semua orang pintar adalah kaya",
      optionB: "Ada orang pintar yang kaya",
      optionC: "Tidak ada dokter yang kaya",
      optionD: "Semua kaya adalah dokter",
      optionE: "Beberapa orang pintar tidak kaya",
      correctAnswer: "B",
      explanation: "Beberapa dokter kaya, dan semua dokter pintar → ada orang pintar (yaitu dokter tersebut) yang kaya.",
    },
    {
      question: "Premis: 'Tidak ada A adalah B'. Setara dengan...",
      optionA: "Beberapa A adalah B",
      optionB: "Semua A bukan B",
      optionC: "Beberapa B adalah A",
      optionD: "Semua B adalah A",
      optionE: "Beberapa A bukan B",
      correctAnswer: "B",
      explanation: "'Tidak ada A adalah B' setara 'semua A bukan B' (universal negatif).",
    },
    {
      question: "Jika kucing miaw maka anjing menggonggong. Anjing menggonggong. Maka...",
      optionA: "Kucing pasti miaw",
      optionB: "Tidak dapat disimpulkan apakah kucing miaw",
      optionC: "Kucing tidak miaw",
      optionD: "Anjing diam",
      optionE: "Tidak relevan",
      correctAnswer: "B",
      explanation: "Afirmasi konsekuen tidak valid: anjing menggonggong tidak otomatis berarti kucing miaw.",
    },
    {
      question: "Empat orang A, B, C, D duduk. A di tengah. B di kanan A. D di kiri C. Posisi yang mungkin...",
      optionA: "C-D-A-B",
      optionB: "D-C-A-B",
      optionC: "B-A-D-C",
      optionD: "A-B-C-D",
      optionE: "D-B-A-C",
      correctAnswer: "B",
      explanation: "A di tengah, B kanan A, D kiri C: D-C-A-B memenuhi semua syarat.",
    },
    {
      question: "Jika lulus tes maka diterima. Tidak diterima. Maka...",
      optionA: "Tidak lulus tes",
      optionB: "Lulus tes",
      optionC: "Tes tidak diadakan",
      optionD: "Tidak dapat disimpulkan",
      optionE: "Tes mudah",
      correctAnswer: "A",
      explanation: "Modus tollens: lulus→diterima, ~diterima → ~lulus. Maka tidak lulus tes.",
    },
    {
      question: "Pernyataan 'Semua angsa berwarna putih' dibantah oleh...",
      optionA: "Semua angsa putih",
      optionB: "Beberapa angsa putih",
      optionC: "Adanya satu angsa hitam (kontra-contoh)",
      optionD: "Tidak ada angsa",
      optionE: "Angsa terbang",
      correctAnswer: "C",
      explanation: "Universal positif dibantah cukup dengan satu kontra-contoh — penemuan satu angsa hitam membatalkan klaim 'semua angsa putih'.",
    },
    {
      question: "Jika P benar dan Q salah, maka 'P dan Q' bernilai...",
      optionA: "Benar",
      optionB: "Salah",
      optionC: "Tidak dapat ditentukan",
      optionD: "Sebagian benar",
      optionE: "Bergantung konteks",
      correctAnswer: "B",
      explanation: "Konjungsi (P ∧ Q) bernilai benar HANYA jika kedua-duanya benar. Q salah → konjungsi salah.",
    },
    {
      question: "Jika P salah, maka 'P atau Q' bernilai...",
      optionA: "Selalu benar",
      optionB: "Selalu salah",
      optionC: "Bergantung pada Q",
      optionD: "Tidak dapat ditentukan",
      optionE: "Sama dengan P",
      correctAnswer: "C",
      explanation: "Disjungsi P ∨ Q salah jika kedua-duanya salah. P salah → tergantung nilai Q.",
    },
    {
      question: "Negasi 'beberapa pegawai datang terlambat' adalah...",
      optionA: "Semua pegawai datang terlambat",
      optionB: "Tidak ada pegawai yang datang terlambat",
      optionC: "Hanya satu pegawai terlambat",
      optionD: "Beberapa pegawai tidak terlambat",
      optionE: "Semua pegawai tepat waktu (sama dengan B)",
      correctAnswer: "B",
      explanation: "Negasi 'beberapa P' = 'tidak ada satupun P' = 'semua bukan P'. Pilihan B paling tepat.",
    },
    {
      question: "Empat orang berlomba: Andi finis sebelum Budi. Caca finis sebelum Andi. Doni finis terakhir. Posisi pertama adalah...",
      optionA: "Andi",
      optionB: "Budi",
      optionC: "Caca",
      optionD: "Doni",
      optionE: "Tidak dapat ditentukan",
      correctAnswer: "C",
      explanation: "Caca > Andi > Budi, dan Doni terakhir. Maka urutan: Caca, Andi, Budi, Doni → Caca pertama.",
    },
    {
      question: "Ruang kelas memuat 30 siswa. 18 siswa suka olahraga, 15 suka musik, 8 suka keduanya. Yang tidak suka keduanya...",
      optionA: "3",
      optionB: "5",
      optionC: "7",
      optionD: "10",
      optionE: "12",
      correctAnswer: "B",
      explanation: "Suka salah satu = 18+15−8 = 25. Tidak suka keduanya = 30 − 25 = 5.",
    },
    {
      question: "Pernyataan 'jika X maka Y' setara dengan...",
      optionA: "Jika Y maka X (konvers)",
      optionB: "Jika tidak Y maka tidak X (kontrapositif)",
      optionC: "Jika tidak X maka tidak Y (invers)",
      optionD: "X dan Y",
      optionE: "X atau Y",
      correctAnswer: "B",
      explanation: "Hanya kontrapositif yang setara secara logis dengan implikasi asli. Konvers dan invers tidak setara.",
    },
    {
      question: "Jika 'jika rajin maka pintar' bernilai BENAR, manakah yang pasti benar?",
      optionA: "Jika tidak pintar maka tidak rajin",
      optionB: "Jika pintar maka rajin",
      optionC: "Jika tidak rajin maka tidak pintar",
      optionD: "Rajin dan pintar",
      optionE: "Pintar atau rajin",
      correctAnswer: "A",
      explanation: "Kontrapositif (tidak pintar → tidak rajin) selalu setara dengan pernyataan asli.",
    },
    {
      question: "Tono lebih cepat dari Doni. Doni lebih lambat dari Sari. Yang paling cepat...",
      optionA: "Tono",
      optionB: "Doni",
      optionC: "Sari",
      optionD: "Tono atau Sari (tidak dapat dipastikan)",
      optionE: "Sama cepat",
      correctAnswer: "D",
      explanation: "Tono > Doni dan Sari > Doni. Hubungan Tono vs Sari tidak diketahui — bisa keduanya.",
    },
    {
      question: "Semua siswa wajib seragam. Beberapa siswa pakai topi. Pernyataan yang pasti benar...",
      optionA: "Semua yang pakai topi adalah siswa",
      optionB: "Ada siswa yang berseragam dan pakai topi",
      optionC: "Tidak ada yang pakai seragam",
      optionD: "Topi dilarang",
      optionE: "Tidak ada siswa pakai topi",
      correctAnswer: "B",
      explanation: "Beberapa siswa pakai topi → mereka pasti pakai seragam (premis pertama wajib). Jadi ada siswa berseragam yang pakai topi.",
    },
    {
      question: "'Hanya jika lulus pra-syarat, dapat ikut tes utama.' Andi ikut tes utama. Maka...",
      optionA: "Andi lulus pra-syarat",
      optionB: "Andi tidak lulus pra-syarat",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Tes mudah",
      optionE: "Andi rajin",
      correctAnswer: "A",
      explanation: "'Hanya jika P maka Q' artinya Q→P. Ikut tes utama → lulus pra-syarat.",
    },
    {
      question: "Jika hujan, jalan basah ATAU lampu padam. Hujan terjadi tetapi lampu tidak padam. Maka...",
      optionA: "Jalan kering",
      optionB: "Jalan basah",
      optionC: "Tidak dapat disimpulkan",
      optionD: "Lampu padam",
      optionE: "Tidak hujan",
      correctAnswer: "B",
      explanation: "Hujan → (basah ∨ padam). Lampu tidak padam → komponen disjungsi yang benar pasti 'jalan basah'.",
    },
    {
      question: "Diketahui: A>B, B>C, C>D, D>E. Yang paling kecil...",
      optionA: "A",
      optionB: "B",
      optionC: "C",
      optionD: "D",
      optionE: "E",
      correctAnswer: "E",
      explanation: "Rantai transitif: A>B>C>D>E. E paling kecil.",
    },
    {
      question: "Jika ada satu mahasiswa malas, maka tidak semua mahasiswa rajin. Pernyataan tersebut...",
      optionA: "Salah",
      optionB: "Benar — kontradiksi langsung dengan 'semua rajin'",
      optionC: "Tidak dapat dinilai",
      optionD: "Bergantung kasus",
      optionE: "Hanya simbolis",
      correctAnswer: "B",
      explanation: "'Semua rajin' dilanggar oleh adanya satu yang tidak rajin (malas). Premis tersebut benar secara logis.",
    },
  ],
};

export default bank;
