import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Saya ditugaskan ke daerah dengan budaya berbeda. Saya...",
      optionA: "Memaksakan budaya saya",
      optionB: "Pelajari budaya setempat, hormati adat, sesuaikan komunikasi",
      optionC: "Mengisolasi diri",
      optionD: "Mengeluh",
      optionE: "Tolak penugasan",
      correctAnswer: "B",
      explanation: "Adaptasi budaya & sensitivitas lokal adalah modal ASN multi-daerah (bobot 5).",
    },
    {
      question: "Tetangga sekitar berbeda agama merayakan hari raya. Saya...",
      optionA: "Hindari interaksi",
      optionB: "Ucapkan selamat dengan tulus dan jaga toleransi",
      optionC: "Kritisi perayaannya",
      optionD: "Pura-pura tidak tahu",
      optionE: "Larang anak ikut menyapa",
      correctAnswer: "B",
      explanation: "Toleransi aktif memperkuat kohesi sosial dalam masyarakat plural (bobot 5).",
    },
    {
      question: "Saya bertemu kelompok marginal di lingkungan kerja. Saya...",
      optionA: "Hindari",
      optionB: "Bersikap inklusif, hargai martabat mereka, bantu jika dibutuhkan",
      optionC: "Beri label negatif",
      optionD: "Diam",
      optionE: "Lapor satpam",
      correctAnswer: "B",
      explanation: "Inklusi sosial mencerminkan sila kemanusiaan yang adil-beradab (bobot 5).",
    },
    {
      question: "Anak tetangga membutuhkan bantuan biaya sekolah. Saya...",
      optionA: "Tidak peduli",
      optionB: "Dukung sesuai kemampuan, hubungkan ke program bantuan resmi",
      optionC: "Sumbang berlebihan tanpa pertimbangan",
      optionD: "Permalukan keluarganya",
      optionE: "Komentar negatif",
      correctAnswer: "B",
      explanation: "Kepedulian sosial yang sehat: dukungan personal + akses ke sistem bantuan (bobot 5).",
    },
    {
      question: "Saya melihat hoaks SARA tersebar di grup keluarga. Saya...",
      optionA: "Sebar lebih luas",
      optionB: "Klarifikasi sumber, ajak verifikasi, dan jelaskan bahaya hoaks SARA",
      optionC: "Diam",
      optionD: "Keluar grup",
      optionE: "Adu argumen panas",
      correctAnswer: "B",
      explanation: "Literasi digital + edukasi keluarga = melawan polarisasi sosial (bobot 5).",
    },
    {
      question: "Saya mendengar lelucon merendahkan etnis di kantor. Saya...",
      optionA: "Tertawa untuk sopan",
      optionB: "Dengan halus sampaikan keberatan dan ingatkan etika",
      optionC: "Ikut bercanda",
      optionD: "Sebar lebih luas",
      optionE: "Dendam diam",
      correctAnswer: "B",
      explanation: "Standar etika di kantor harus dijaga dengan teguran ramah saat dilanggar (bobot 5).",
    },
    {
      question: "Saya diundang ke pernikahan adat yang asing bagi saya. Saya...",
      optionA: "Tolak karena ribet",
      optionB: "Hadir, tanya etiket dasar, dan ikuti dengan hormat",
      optionC: "Hadir tapi cuek terhadap adat",
      optionD: "Komentari adat aneh",
      optionE: "Datang sebentar lalu pulang",
      correctAnswer: "B",
      explanation: "Belajar etiket lintas budaya menunjukkan rasa hormat dan memperkaya wawasan (bobot 5).",
    },
    {
      question: "Saya bekerja dengan rekan disabilitas. Saya...",
      optionA: "Mengasihani berlebihan",
      optionB: "Perlakukan setara, sesuaikan akses kerja, hargai kompetensinya",
      optionC: "Hindari",
      optionD: "Ambil alih semua tugasnya",
      optionE: "Beri label keterbatasan",
      correctAnswer: "B",
      explanation: "Inklusi disabilitas: kesetaraan + akomodasi yang dibutuhkan (bobot 5).",
    },
    {
      question: "Generasi muda di kantor punya cara kerja berbeda dari saya. Saya...",
      optionA: "Paksakan cara saya",
      optionB: "Buka pikiran, pelajari pendekatan baru, gabungkan kekuatan generasi",
      optionC: "Tolak ide mereka semua",
      optionD: "Mengeluh",
      optionE: "Hindari",
      correctAnswer: "B",
      explanation: "Kolaborasi lintas generasi = kekuatan, bukan ancaman (bobot 5).",
    },
    {
      question: "Saya menyaksikan kemiskinan di sekitar rumah. Saya...",
      optionA: "Tidak peduli",
      optionB: "Bantu sesuai kemampuan, dorong program pemerintah/komunitas",
      optionC: "Beri label malas",
      optionD: "Pindah lingkungan",
      optionE: "Posting di sosmed kasihan",
      correctAnswer: "B",
      explanation: "Kepedulian sosial dengan tindakan + pendekatan sistemik (bobot 5).",
    },
  ],
  ujian: [
    {
      question: "Saat penugasan di daerah, masyarakat menggunakan bahasa lokal. Saya...",
      optionA: "Memaksa pakai Bahasa Indonesia",
      optionB: "Belajar dasar bahasa lokal sambil pakai bahasa Indonesia untuk hal resmi",
      optionC: "Hindari komunikasi",
      optionD: "Pakai penerjemah selalu",
      optionE: "Mengejek dialek mereka",
      correctAnswer: "B",
      explanation: "Bilingualitas fungsional = kunci pelayanan di daerah (bobot 5).",
    },
    {
      question: "Adat lokal mengharuskan ritual tertentu sebelum acara dimulai. Saya...",
      optionA: "Lewati karena tidak penting",
      optionB: "Hormati dan ikuti sesuai panduan tokoh adat",
      optionC: "Kritik di depan publik",
      optionD: "Hadir tapi telat sengaja",
      optionE: "Tinggalkan acara",
      correctAnswer: "B",
      explanation: "Hormat adat = jembatan kepercayaan dengan masyarakat lokal (bobot 5).",
    },
    {
      question: "Saya melihat eksklusi terhadap kelompok minoritas di kegiatan kantor. Saya...",
      optionA: "Diam",
      optionB: "Aktif libatkan kelompok minoritas, usulkan kebijakan inklusi",
      optionC: "Setuju saja",
      optionD: "Pisahkan diri",
      optionE: "Melapor anonim saja",
      correctAnswer: "B",
      explanation: "Kebijakan inklusi memerlukan suara aktif dari semua anggota organisasi (bobot 5).",
    },
    {
      question: "Saya mengetahui rekan rentan akibat KDRT. Saya...",
      optionA: "Ikut campur secara tidak etis",
      optionB: "Dukung empatik, info hotline & jalur bantuan resmi, jaga kerahasiaan",
      optionC: "Sebarkan kabar",
      optionD: "Salahkan korban",
      optionE: "Hindari rekan tersebut",
      correctAnswer: "B",
      explanation: "Dukungan empatik + akses bantuan resmi + privasi = pendekatan profesional (bobot 5).",
    },
    {
      question: "Lingkungan saya kurang peduli kebersihan. Saya...",
      optionA: "Ikut acuh",
      optionB: "Inisiatif kerja bakti dan edukasi mulai dari aksi konkret",
      optionC: "Pindah",
      optionD: "Mengeluh saja",
      optionE: "Membayar pengganti tanpa edukasi",
      correctAnswer: "B",
      explanation: "Perubahan budaya komunal dimulai dari aksi nyata dan pelibatan partisipatif (bobot 5).",
    },
    {
      question: "Saya bertugas di luar kota terpisah dari keluarga. Saya...",
      optionA: "Sering izin tidak masuk",
      optionB: "Bangun rutinitas komunikasi keluarga + fokus optimalkan kontribusi di tempat tugas",
      optionC: "Cari celah pindah segera",
      optionD: "Bekerja seadanya",
      optionE: "Resign",
      correctAnswer: "B",
      explanation: "Work-life balance jarak jauh = komunikasi rutin + komitmen kerja (bobot 5).",
    },
    {
      question: "Tetangga sebelah berisik. Saya...",
      optionA: "Lapor polisi langsung",
      optionB: "Bicara baik-baik dulu sambil cari solusi bersama",
      optionC: "Balas berisik",
      optionD: "Adu fisik",
      optionE: "Diamkan dan dendam",
      correctAnswer: "B",
      explanation: "Resolusi konflik tetangga: dialog langsung sebagai langkah pertama (bobot 5).",
    },
    {
      question: "Generasi anak saya menghadapi tekanan media sosial. Saya...",
      optionA: "Larang total bermedia sosial",
      optionB: "Bimbing literasi digital, dialog terbuka tentang risiko & manfaat",
      optionC: "Biarkan bebas",
      optionD: "Mata-matai diam-diam",
      optionE: "Marah-marah saja",
      correctAnswer: "B",
      explanation: "Parenting digital era: dialog & literasi lebih efektif daripada larangan absolut (bobot 5).",
    },
    {
      question: "Saya menemui demonstrasi yang anarkis. Saya...",
      optionA: "Bergabung",
      optionB: "Hindari area, dukung jalur penyaluran aspirasi yang konstitusional",
      optionC: "Provokasi",
      optionD: "Sebar info berlebihan",
      optionE: "Filmkan untuk konten pribadi",
      correctAnswer: "B",
      explanation: "Aspirasi disampaikan via jalur konstitusional, ASN tidak terlibat aksi anarkis (bobot 5).",
    },
    {
      question: "Saya melihat sampah berserakan di tempat ibadah agama lain. Saya...",
      optionA: "Abaikan karena bukan tempat saya",
      optionB: "Bersihkan atau lapor pengelola dengan rasa hormat",
      optionC: "Tambah sampah",
      optionD: "Kritik via sosmed",
      optionE: "Tertawa",
      correctAnswer: "B",
      explanation: "Kepedulian lintas agama mencerminkan kemanusiaan & toleransi sejati (bobot 5).",
    },
    {
      question: "Saya bertugas di daerah konflik horizontal. Saya...",
      optionA: "Pilih sisi",
      optionB: "Netral, bantu mediasi via tokoh adat/agama, dukung rekonsiliasi",
      optionC: "Hindari tugas",
      optionD: "Lapor saja tanpa aksi",
      optionE: "Tinggalkan daerah",
      correctAnswer: "B",
      explanation: "Netralitas + memanfaatkan modal sosial lokal (tokoh) untuk rekonsiliasi (bobot 5).",
    },
    {
      question: "Saya bertemu warga berbeda orientasi politik dari saya. Saya...",
      optionA: "Adu argumen tajam",
      optionB: "Dengarkan, hargai pilihannya, fokus pada kepentingan bersama",
      optionC: "Putus relasi",
      optionD: "Konversi paksa",
      optionE: "Hindari topik politik selamanya",
      correctAnswer: "B",
      explanation: "Demokrasi sehat butuh dialog antar pilihan politik dengan saling hormat (bobot 5).",
    },
    {
      question: "Anak yatim tinggal sendirian di lingkungan saya. Saya...",
      optionA: "Tidak peduli",
      optionB: "Koordinasi dengan RT/Dinas Sosial untuk penanganan resmi & dukungan komunal",
      optionC: "Adopsi tanpa prosedur",
      optionD: "Rajin membantu sembunyi-sembunyi",
      optionE: "Posting kasus untuk viral",
      correctAnswer: "B",
      explanation: "Dukungan formal via dinas sosial + komunal = perlindungan terbaik bagi anak (bobot 5).",
    },
    {
      question: "Acara kantor jatuh saat hari ibadah agama saya. Saya...",
      optionA: "Tolak total",
      optionB: "Komunikasikan kebutuhan ibadah, atur jadwal hadir di luar waktu ibadah",
      optionC: "Hadir penuh tanpa ibadah",
      optionD: "Hilang tanpa kabar",
      optionE: "Tuntut acara dipindah",
      correctAnswer: "B",
      explanation: "Komunikasi kebutuhan ibadah secara profesional adalah hak yang dilindungi UUD 1945 (bobot 5).",
    },
    {
      question: "Saya melihat anak-anak dengan stunting di lingkungan tugas. Saya...",
      optionA: "Diam",
      optionB: "Lapor ke Puskesmas/Dinas Kesehatan, dukung edukasi gizi keluarga",
      optionC: "Beri uang seadanya",
      optionD: "Posting tanpa tindakan",
      optionE: "Anggap takdir",
      correctAnswer: "B",
      explanation: "Aksi kolaboratif via sistem kesehatan = solusi sistemik stunting (bobot 5).",
    },
    {
      question: "Saya melihat senior tidak menghargai junior dalam rapat. Saya...",
      optionA: "Diam karena hierarki",
      optionB: "Beri ruang junior bicara, dukung kontribusinya secara terbuka",
      optionC: "Ikut menekan",
      optionD: "Lapor HR diam-diam",
      optionE: "Cuek",
      correctAnswer: "B",
      explanation: "Allyship lintas senioritas membangun kultur inklusif (bobot 5).",
    },
    {
      question: "Anggota keluarga saya menentang pekerjaan saya di luar kota. Saya...",
      optionA: "Resign demi keluarga",
      optionB: "Dialog terbuka, jelaskan tujuan & manfaat, atur kompromi yang sehat",
      optionC: "Abaikan keluarga",
      optionD: "Berbohong tentang lokasi",
      optionE: "Konflik berkepanjangan",
      correctAnswer: "B",
      explanation: "Komunikasi & kompromi keluarga = kunci keseimbangan karier-keluarga (bobot 5).",
    },
    {
      question: "Saya menyaksikan pelecehan verbal terhadap perempuan di tempat umum. Saya...",
      optionA: "Diam",
      optionB: "Intervensi aman: dekati korban, panggil bantuan, laporkan ke pihak berwenang",
      optionC: "Filmkan untuk viral",
      optionD: "Salahkan korban",
      optionE: "Pergi cepat",
      correctAnswer: "B",
      explanation: "Bystander intervention dengan keamanan terjaga = tanggung jawab sosial (bobot 5).",
    },
    {
      question: "Saya melihat budaya konsumtif berlebihan di lingkungan. Saya...",
      optionA: "Ikut arus",
      optionB: "Pegang prinsip hidup sederhana sebagai contoh, edukasi hemat & investasi",
      optionC: "Kritisi keras",
      optionD: "Hindari pergaulan",
      optionE: "Kalahkan dengan barang lebih mahal",
      correctAnswer: "B",
      explanation: "Modeling sikap sederhana lebih efektif daripada kritik (bobot 5).",
    },
    {
      question: "Saya mendapat informasi rahasia agama tertentu. Saya...",
      optionA: "Sebarkan untuk jadikan bahan tertawaan",
      optionB: "Jaga kerahasiaan dan hargai privasi keagamaan",
      optionC: "Eksploitasi untuk keuntungan",
      optionD: "Diskusi terbuka tanpa izin",
      optionE: "Posting sosmed",
      correctAnswer: "B",
      explanation: "Privasi agama dilindungi UUD 1945. Hormati & jaga kerahasiaannya (bobot 5).",
    },
    {
      question: "Saya bekerja dengan rekan beragama berbeda yang sedang puasa. Saya...",
      optionA: "Makan di depannya provokatif",
      optionB: "Hargai puasanya, sesuaikan etika di ruang bersama",
      optionC: "Tolak semua interaksi",
      optionD: "Komentari ibadahnya",
      optionE: "Ajak makan terus",
      correctAnswer: "B",
      explanation: "Etika ruang bersama: hormati ibadah rekan dengan adjustment sederhana (bobot 5).",
    },
    {
      question: "Saya mengetahui ada pernikahan di bawah umur di lingkungan. Saya...",
      optionA: "Diam",
      optionB: "Lapor ke pihak berwenang dan KPAI, dukung edukasi keluarga",
      optionC: "Hadir merayakan",
      optionD: "Posting kontroversi",
      optionE: "Salahkan anak",
      correctAnswer: "B",
      explanation: "Pernikahan anak adalah pelanggaran hukum & HAM. Lapor & edukasi adalah jalan tepat (bobot 5).",
    },
    {
      question: "Saya bertemu kelompok yang menyebarkan paham radikal. Saya...",
      optionA: "Bergabung",
      optionB: "Lapor ke aparat berwenang dan jaga jarak",
      optionC: "Konfrontasi keras",
      optionD: "Diam dan dukung",
      optionE: "Coba menasihati sendirian",
      correctAnswer: "B",
      explanation: "Radikalisme ditangani aparat profesional. ASN melapor & menjaga ideologi negara (bobot 5).",
    },
    {
      question: "Anak saya bertanya tentang perbedaan agama. Saya...",
      optionA: "Hindari topik",
      optionB: "Jelaskan dengan terbuka, ajarkan toleransi dan rasa hormat",
      optionC: "Beri jawaban diskriminatif",
      optionD: "Suruh tanya guru",
      optionE: "Marah",
      correctAnswer: "B",
      explanation: "Pendidikan toleransi sejak dini di rumah membentuk warga negara inklusif (bobot 5).",
    },
    {
      question: "Lingkungan saya jarang gotong royong. Saya...",
      optionA: "Ikut acuh",
      optionB: "Inisiatif acara komunitas kecil sebagai pemicu kebiasaan baru",
      optionC: "Mengeluh ke RT",
      optionD: "Pindah",
      optionE: "Bayar saja",
      correctAnswer: "B",
      explanation: "Membangun budaya gotong royong dimulai dari inisiatif kecil yang konsisten (bobot 5).",
    },
    {
      question: "Saya menemui korban bencana di daerah tugas. Saya...",
      optionA: "Tinggalkan",
      optionB: "Beri pertolongan pertama jika mampu, koordinasi dengan BPBD/relawan",
      optionC: "Foto-foto saja",
      optionD: "Kritik penanganan pemerintah",
      optionE: "Pulang dulu",
      correctAnswer: "B",
      explanation: "Respons bencana: pertolongan langsung + koordinasi sistem resmi (bobot 5).",
    },
    {
      question: "Saya bertugas membuat program pemberdayaan UMKM lokal. Saya...",
      optionA: "Salin program kota lain",
      optionB: "Lakukan asesmen kebutuhan lokal & rancang program kontekstual",
      optionC: "Fokus laporan saja",
      optionD: "Top-down tanpa survei",
      optionE: "Tunda terus",
      correctAnswer: "B",
      explanation: "Program berbasis kebutuhan lokal = pemberdayaan yang efektif & berkelanjutan (bobot 5).",
    },
    {
      question: "Saya bertemu mantan napi yang kesulitan reintegrasi. Saya...",
      optionA: "Hindari & beri stigma",
      optionB: "Bersikap manusiawi, dukung program reintegrasi resmi",
      optionC: "Kabari semua orang",
      optionD: "Tutup peluang kerja",
      optionE: "Curigai terus",
      correctAnswer: "B",
      explanation: "Reintegrasi sosial mantan napi adalah amanat UU & semangat kemanusiaan Pancasila (bobot 5).",
    },
    {
      question: "Saya bekerja di daerah dengan kearifan lokal kuat. Saya...",
      optionA: "Abaikan",
      optionB: "Pelajari kearifan lokal, integrasikan dengan program pemerintah secara sinergis",
      optionC: "Ganti dengan modern",
      optionD: "Kritisi kearifan tersebut",
      optionE: "Pakai sesekali untuk simbol",
      correctAnswer: "B",
      explanation: "Sinergi modern dengan kearifan lokal membuat program lebih diterima & lestari (bobot 5).",
    },
    {
      question: "Saya melihat perundungan di sekolah anak saya. Saya...",
      optionA: "Tidak campur",
      optionB: "Dialog dengan sekolah dan dorong sistem anti-bullying yang adil",
      optionC: "Marahi pelaku langsung",
      optionD: "Pindahkan anak diam-diam",
      optionE: "Sebarkan di sosmed",
      correctAnswer: "B",
      explanation: "Pencegahan bullying butuh sistem sekolah, bukan tindakan instan (bobot 5).",
    },
  ],
};

export default bank;
