import type { QuestionBank } from "../types";

// Catatan TKP: pada CPNS resmi, semua opsi memiliki bobot 1-5. Untuk demo
// platform, jawaban paling tepat (bobot 5) ditandai sebagai correctAnswer
// dan pembahasan menyebut konvensi ini.

const bank: QuestionBank = {
  latihan: [
    {
      question: "Saat melayani masyarakat di loket, ada orang yang sangat marah dan berteriak. Sikap saya...",
      optionA: "Membalas dengan suara keras",
      optionB: "Mengabaikan dan melayani orang lain",
      optionC: "Tetap tenang, mendengarkan keluhan, dan mencari solusi yang tepat",
      optionD: "Memanggil satpam langsung",
      optionE: "Meminta dia menunggu sampai tenang",
      correctAnswer: "C",
      explanation: "Profesionalisme menuntut tetap tenang dan empati. Mendengarkan dulu, lalu memberi solusi adalah pendekatan paling tepat (bobot 5).",
    },
    {
      question: "Atasan meminta bantuan tetapi pekerjaan saya menumpuk. Saya...",
      optionA: "Menolak karena sibuk",
      optionB: "Membantu sambil mengomunikasikan beban kerja saya untuk skala prioritas",
      optionC: "Mengiyakan tapi tidak mengerjakan",
      optionD: "Mengerjakan asal-asalan",
      optionE: "Diam dan stres",
      correctAnswer: "B",
      explanation: "Komunikasi terbuka tentang beban kerja sambil tetap kooperatif adalah jawaban paling profesional.",
    },
    {
      question: "Seorang masyarakat datang dengan dokumen tidak lengkap. Saya...",
      optionA: "Menolak melayani",
      optionB: "Memarahi karena tidak teliti",
      optionC: "Menjelaskan dengan sabar dokumen yang kurang dan cara melengkapinya",
      optionD: "Menyuruh datang lagi besok",
      optionE: "Menyuruh tanya teman",
      correctAnswer: "C",
      explanation: "Pelayanan publik prima: jelaskan dengan sabar dan beri panduan jelas (bobot 5).",
    },
    {
      question: "Ada rekan yang berkonflik dengan masyarakat. Saya...",
      optionA: "Memihak rekan tanpa cek fakta",
      optionB: "Memihak masyarakat tanpa cek fakta",
      optionC: "Menengahi dengan netral, mendengarkan kedua pihak, mencari solusi adil",
      optionD: "Diam saja",
      optionE: "Lapor atasan tanpa upaya mediasi",
      correctAnswer: "C",
      explanation: "Mediasi dan penyelesaian konflik dengan netralitas adalah ciri ASN profesional (bobot 5).",
    },
    {
      question: "Saya mendapat tugas baru yang belum pernah saya lakukan. Saya...",
      optionA: "Menolak karena tidak bisa",
      optionB: "Menerima dan belajar/mencari mentor untuk menyelesaikannya",
      optionC: "Menyerahkan ke rekan",
      optionD: "Mengerjakan asal jadi",
      optionE: "Menunggu instruksi detail",
      correctAnswer: "B",
      explanation: "Sikap pembelajar dan inisiatif mencari pengetahuan adalah indikator profesionalisme tinggi (bobot 5).",
    },
    {
      question: "Saat melayani, ada yang menawarkan uang sebagai 'tanda terima kasih'. Saya...",
      optionA: "Menerima karena ikhlas",
      optionB: "Menolak dengan halus dan menjelaskan layanan publik gratis sesuai SOP",
      optionC: "Menerima sedikit saja",
      optionD: "Melapor setelah menerima",
      optionE: "Diam",
      correctAnswer: "B",
      explanation: "Integritas: tolak gratifikasi dan edukasi publik bahwa layanan gratis adalah hak warga (bobot 5).",
    },
    {
      question: "Antrean panjang dan mendekati jam tutup. Saya...",
      optionA: "Tutup tepat waktu, abaikan antrean",
      optionB: "Tetap melayani sampai antrean selesai dan koordinasi dengan tim",
      optionC: "Menyuruh sebagian datang besok",
      optionD: "Layani asal cepat tanpa cek detail",
      optionE: "Pulang lebih cepat",
      correctAnswer: "B",
      explanation: "Komitmen pelayanan: prioritaskan kebutuhan publik selama masih memungkinkan, dengan koordinasi tim (bobot 5).",
    },
    {
      question: "Saya melihat rekan yang melakukan praktik tidak jujur. Saya...",
      optionA: "Diam karena bukan urusan saya",
      optionB: "Menegur secara pribadi terlebih dahulu, lalu lapor jika berlanjut",
      optionC: "Langsung viralkan",
      optionD: "Bergabung melakukannya",
      optionE: "Pura-pura tidak tahu",
      correctAnswer: "B",
      explanation: "Etika profesional: teguran personal dulu sebagai pendekatan kekeluargaan, eskalasi resmi jika tidak berubah (bobot 5).",
    },
    {
      question: "Kantor menerapkan sistem antrean baru tetapi rekan-rekan menolak. Saya...",
      optionA: "Ikut menolak demi solidaritas",
      optionB: "Mendukung dan membantu sosialisasi serta adaptasi sistem baru",
      optionC: "Diam",
      optionD: "Tetap pakai cara lama",
      optionE: "Mengeluh ke media sosial",
      correctAnswer: "B",
      explanation: "Adaptif terhadap perubahan dan menjadi agen change management adalah karakteristik ASN unggul (bobot 5).",
    },
    {
      question: "Masyarakat mengajukan keluhan via media sosial tentang layanan kami. Saya...",
      optionA: "Mengabaikan",
      optionB: "Membalas dengan emosional",
      optionC: "Merespons profesional, klarifikasi, dan tindak lanjuti perbaikan",
      optionD: "Memblokir akun pengeluh",
      optionE: "Menghapus komentar",
      correctAnswer: "C",
      explanation: "Responsif dan transparan terhadap kritik publik adalah praktik akuntabilitas modern (bobot 5).",
    },
  ],
  ujian: [
    {
      question: "Standar Operasional Prosedur (SOP) tidak sesuai dengan kondisi lapangan saat ini. Saya...",
      optionA: "Tetap ikuti SOP buta meski merugikan masyarakat",
      optionB: "Mengusulkan revisi SOP dengan data dan tetap melayani sebaik mungkin selama proses",
      optionC: "Abaikan SOP dan improvisasi sendiri",
      optionD: "Menyalahkan atasan",
      optionE: "Berhenti melayani",
      correctAnswer: "B",
      explanation: "Improvement: usul perbaikan SOP via jalur formal dengan data, sambil tetap melayani — solusi profesional (bobot 5).",
    },
    {
      question: "Masyarakat berkali-kali menanyakan hal yang sama. Saya...",
      optionA: "Marah karena diulang",
      optionB: "Menjelaskan ulang dengan sabar dan cek pemahaman",
      optionC: "Menyuruh lihat brosur",
      optionD: "Menjawab singkat",
      optionE: "Menjawab dengan emosional",
      correctAnswer: "B",
      explanation: "Empati dan kesabaran melayani publik dengan beragam latar belakang adalah inti pelayanan prima.",
    },
    {
      question: "Atasan meminta saya melakukan hal yang melanggar aturan. Saya...",
      optionA: "Patuh karena hierarki",
      optionB: "Menolak dengan sopan, jelaskan risiko hukum, dan tawarkan alternatif legal",
      optionC: "Lakukan dengan menyembunyikan jejak",
      optionD: "Lakukan dan lapor jika ketahuan",
      optionE: "Diam dan ikut saja",
      correctAnswer: "B",
      explanation: "Integritas mengalahkan loyalitas buta. Tolak yang melanggar, tawarkan jalan keluar legal (bobot 5).",
    },
    {
      question: "Masyarakat dengan disabilitas datang ke kantor tanpa pendamping. Saya...",
      optionA: "Pura-pura tidak melihat",
      optionB: "Menyuruh datang lagi dengan pendamping",
      optionC: "Mendekat, menawarkan bantuan, dan melayani dengan ramah",
      optionD: "Memanggil rekan untuk menggantikan",
      optionE: "Layani biasa tanpa penyesuaian",
      correctAnswer: "C",
      explanation: "Inklusi disabilitas: aktif menawarkan bantuan dan menyesuaikan layanan adalah kewajiban ASN modern (bobot 5).",
    },
    {
      question: "Saya menemukan kesalahan data dalam dokumen yang sudah saya tandatangani. Saya...",
      optionA: "Membiarkan supaya tidak diketahui",
      optionB: "Segera laporkan, koreksi sesuai prosedur, dan dokumentasikan",
      optionC: "Menyalahkan staf input",
      optionD: "Memperbaiki diam-diam",
      optionE: "Mengabaikan",
      correctAnswer: "B",
      explanation: "Akuntabilitas: tanggung jawab penuh atas tanda tangan, koreksi terbuka via prosedur (bobot 5).",
    },
    {
      question: "Rekan menyuruh saya pulang lebih cepat dengan absen titip. Saya...",
      optionA: "Ikut karena solidaritas",
      optionB: "Tolak dengan tegas tapi sopan, jelaskan disiplin kehadiran",
      optionC: "Sekali-sekali tidak apa",
      optionD: "Diam",
      optionE: "Ikut tapi merasa bersalah",
      correctAnswer: "B",
      explanation: "Disiplin dan integritas kehadiran tidak bisa dikompromikan. Edukasi rekan dengan cara baik.",
    },
    {
      question: "Pelayanan online sistem error. Saya...",
      optionA: "Tunggu IT memperbaiki, layanan terhenti",
      optionB: "Inisiatif siapkan layanan manual sementara dan komunikasikan ke publik",
      optionC: "Menyalahkan vendor",
      optionD: "Pulang",
      optionE: "Tunggu instruksi atasan",
      correctAnswer: "B",
      explanation: "Inisiatif kontingensi dan komunikasi publik adalah ciri ASN responsif (bobot 5).",
    },
    {
      question: "Saya ditempatkan di unit baru yang berbeda dari latar pendidikan saya. Saya...",
      optionA: "Mengeluh dan minta pindah",
      optionB: "Beradaptasi, belajar cepat, dan kontribusi maksimal sesuai posisi baru",
      optionC: "Bekerja seadanya",
      optionD: "Pasif menunggu pelatihan",
      optionE: "Resign",
      correctAnswer: "B",
      explanation: "Adaptabilitas dan growth mindset adalah modal utama ASN dalam rotasi tugas (bobot 5).",
    },
    {
      question: "Atasan jarang ke kantor dan jarang memberi arahan. Saya...",
      optionA: "Bekerja semau saya",
      optionB: "Tetap kerjakan tugas rutin, ambil inisiatif, dan komunikasikan progres berkala",
      optionC: "Tidak bekerja jika tidak ada perintah",
      optionD: "Mengeluh ke rekan",
      optionE: "Lapor ke pejabat lebih atas tanpa diskusi",
      correctAnswer: "B",
      explanation: "Self-driven dan komunikasi proaktif menjaga kinerja tetap optimal (bobot 5).",
    },
    {
      question: "Ada anggota tim yang sering terlambat. Saya selaku rekan...",
      optionA: "Diam saja",
      optionB: "Menyindir",
      optionC: "Bicara langsung dengan empati, tanyakan kendala dan dorong solusi",
      optionD: "Lapor langsung ke atasan",
      optionE: "Mengejek",
      correctAnswer: "C",
      explanation: "Empati dan dialog konstruktif lebih efektif daripada konfrontasi atau sikap pasif (bobot 5).",
    },
    {
      question: "Saya melihat antrean panjang di loket sementara loket lain kosong. Saya...",
      optionA: "Tetap di posisi karena bukan tugas saya",
      optionB: "Inisiatif buka loket bantuan/koordinasi sehingga antrean terbagi",
      optionC: "Lapor lalu menunggu instruksi",
      optionD: "Memvideokan untuk media sosial",
      optionE: "Diam saja",
      correctAnswer: "B",
      explanation: "Inisiatif kolektif untuk mengurangi waktu tunggu publik adalah pelayanan prima (bobot 5).",
    },
    {
      question: "Masyarakat memberikan saran konstruktif di kotak saran. Saya...",
      optionA: "Abaikan",
      optionB: "Pelajari, diskusikan dengan tim, dan tindak lanjuti yang feasible",
      optionC: "Buang saran tersebut",
      optionD: "Hanya simpan tanpa baca",
      optionE: "Marah pada pemberi saran",
      correctAnswer: "B",
      explanation: "Saran publik adalah aset perbaikan layanan. Aktif tindaklanjuti yang relevan (bobot 5).",
    },
    {
      question: "Saya tahu data sensitif rekan kerja yang sedang viral. Saya...",
      optionA: "Sebar di grup chat",
      optionB: "Menjaga kerahasiaan dan tidak terlibat dalam penyebaran",
      optionC: "Bagikan ke teman dekat saja",
      optionD: "Konfirmasi kepada rekan tersebut secara provokatif",
      optionE: "Manfaatkan untuk tekan rekan",
      correctAnswer: "B",
      explanation: "Etika privasi: data pribadi tidak untuk disebarkan tanpa izin. Diam adalah profesional (bobot 5).",
    },
    {
      question: "Saya diminta memberi tanda tangan pada dokumen yang belum saya baca. Saya...",
      optionA: "Tanda tangan saja karena sudah dipercaya",
      optionB: "Minta waktu untuk membaca dulu sebelum menandatangani",
      optionC: "Tanda tangan tapi minta dijelaskan setelahnya",
      optionD: "Tolak total",
      optionE: "Suruh atasan tanda tangan",
      correctAnswer: "B",
      explanation: "Akuntabilitas: tanda tangan = tanggung jawab. Selalu baca dan pahami (bobot 5).",
    },
    {
      question: "Pekerjaan banyak tetapi sumber daya terbatas. Saya...",
      optionA: "Mengeluh dan tunda",
      optionB: "Buat skala prioritas, identifikasi resource gap, dan komunikasikan ke atasan",
      optionC: "Kerjakan semua sekaligus",
      optionD: "Kerjakan yang mudah saja",
      optionE: "Tinggalkan",
      correctAnswer: "B",
      explanation: "Manajemen prioritas + komunikasi atas keterbatasan sumber daya = solusi profesional (bobot 5).",
    },
    {
      question: "Kantor mengadakan pelatihan di hari libur. Saya...",
      optionA: "Tolak karena mengganggu istirahat",
      optionB: "Hadir dengan antusias karena investasi diri jangka panjang",
      optionC: "Hadir tapi tidak fokus",
      optionD: "Pura-pura sakit",
      optionE: "Datang terlambat",
      correctAnswer: "B",
      explanation: "Sikap pembelajar dan komitmen pengembangan diri adalah ciri ASN unggul (bobot 5).",
    },
    {
      question: "Saya selesaikan tugas lebih cepat dari deadline. Saya...",
      optionA: "Pulang awal diam-diam",
      optionB: "Tawarkan bantuan ke rekan atau ambil tugas baru",
      optionC: "Browsing media sosial",
      optionD: "Menunda penyerahan agar terlihat sibuk",
      optionE: "Tidur di meja",
      correctAnswer: "B",
      explanation: "Etos kerja tinggi: gunakan waktu sisa untuk membantu tim atau ambil pekerjaan tambahan (bobot 5).",
    },
    {
      question: "Saya menemukan kesalahan SOP yang saya gunakan selama ini. Saya...",
      optionA: "Diam saja agar tidak terlihat salah",
      optionB: "Akui terbuka, perbaiki ke depan, dan dokumentasikan untuk lessons learned",
      optionC: "Salahkan rekan",
      optionD: "Hapus jejak kesalahan",
      optionE: "Salahkan SOP nya",
      correctAnswer: "B",
      explanation: "Transparansi dan budaya belajar dari kesalahan adalah inti perbaikan organisasi (bobot 5).",
    },
    {
      question: "Saya ditempatkan di daerah terpencil dengan fasilitas minim. Saya...",
      optionA: "Mengeluh terus",
      optionB: "Adaptasi, kontribusi maksimal, dan jadi pemberi inspirasi bagi masyarakat lokal",
      optionC: "Sering izin pulang ke kota",
      optionD: "Bekerja seadanya",
      optionE: "Cari celah pindah segera",
      correctAnswer: "B",
      explanation: "Pengabdian ASN tidak terbatas ruang. Sikap positif di kondisi sulit menunjukkan integritas (bobot 5).",
    },
    {
      question: "Anggota masyarakat mengkritik saya di media massa. Saya...",
      optionA: "Tuntut balik",
      optionB: "Tanggapi profesional, klarifikasi via jalur resmi, evaluasi diri",
      optionC: "Diam dan dendam",
      optionD: "Balas dengan emosi",
      optionE: "Sebarkan kontra-konten",
      correctAnswer: "B",
      explanation: "Kritik publik = peluang introspeksi. Klarifikasi resmi tanpa emosi (bobot 5).",
    },
    {
      question: "Saya diminta memimpin proyek lintas instansi yang kompleks. Saya...",
      optionA: "Tolak karena belum siap",
      optionB: "Terima dengan persiapan matang, libatkan stakeholder, dan minta dukungan mentor",
      optionC: "Terima asal-asalan",
      optionD: "Delegasi semua ke staf",
      optionE: "Tolak halus",
      correctAnswer: "B",
      explanation: "Tantangan adalah ruang berkembang. Terima dengan strategi & kolaborasi (bobot 5).",
    },
    {
      question: "Rekan tim saya pasif saat rapat. Saya...",
      optionA: "Mengabaikan",
      optionB: "Aktifkan dengan pertanyaan terbuka dan beri ruang ekspresi",
      optionC: "Mengeluh ke atasan",
      optionD: "Sindir di depan tim",
      optionE: "Lapor HR",
      correctAnswer: "B",
      explanation: "Kepemimpinan partisipatif: aktifkan rekan dengan dialog inklusif (bobot 5).",
    },
    {
      question: "Saya diminta memberi keterangan sebagai saksi di pengadilan. Saya...",
      optionA: "Hindari karena merepotkan",
      optionB: "Hadir dan beri keterangan jujur sesuai fakta yang saya ketahui",
      optionC: "Beri keterangan menguntungkan teman",
      optionD: "Pura-pura sakit",
      optionE: "Beri keterangan ambigu",
      correctAnswer: "B",
      explanation: "Kewajiban warga & ASN: beri keterangan jujur demi keadilan (bobot 5).",
    },
    {
      question: "Saya mendapat tawaran bekerja di sektor swasta dengan gaji 3x lipat. Saya...",
      optionA: "Langsung resign tanpa serah terima",
      optionB: "Pertimbangkan matang, jika resign lakukan dengan handover profesional dan etika baik",
      optionC: "Resign mendadak",
      optionD: "Bekerja paralel diam-diam",
      optionE: "Tolak tanpa dipikir",
      correctAnswer: "B",
      explanation: "Hak setiap orang memilih karier. Yang dinilai: profesionalisme transisi dan etika handover (bobot 5).",
    },
    {
      question: "Saya melihat infrastruktur publik rusak yang membahayakan. Saya...",
      optionA: "Foto untuk media sosial",
      optionB: "Lapor ke instansi terkait dan beri peringatan kepada warga sekitar",
      optionC: "Diam karena bukan urusan unit saya",
      optionD: "Lewat saja",
      optionE: "Tunggu orang lain melapor",
      correctAnswer: "B",
      explanation: "Tanggung jawab sosial ASN melampaui tupoksi formal — keselamatan publik utama (bobot 5).",
    },
    {
      question: "Pimpinan menetapkan target kinerja tinggi. Saya...",
      optionA: "Mengeluh ke seluruh tim",
      optionB: "Buat rencana kerja terstruktur dan komunikasikan kebutuhan resource",
      optionC: "Pasrah",
      optionD: "Kerja asal-asalan",
      optionE: "Sabotase target",
      correctAnswer: "B",
      explanation: "Profesionalisme: terima target sebagai tantangan, susun strategi & resource plan (bobot 5).",
    },
    {
      question: "Saya melihat data publikasi statistik instansi yang salah. Saya...",
      optionA: "Diamkan karena bukan unit saya",
      optionB: "Lapor ke unit data agar segera dikoreksi sebelum publikasi luas",
      optionC: "Posting di media sosial",
      optionD: "Tunggu warga komplain",
      optionE: "Buat data sendiri",
      correctAnswer: "B",
      explanation: "Akurasi data publik adalah trust pemerintahan. Lapor cepat via jalur internal (bobot 5).",
    },
    {
      question: "Saya melayani warga lansia yang lambat. Saya...",
      optionA: "Mempercepat dengan terburu-buru",
      optionB: "Pelan, sabar, dan pastikan dia paham proses sampai selesai",
      optionC: "Suruh ditemani anaknya",
      optionD: "Lewatkan ke loket lain",
      optionE: "Selesaikan tanpa penjelasan",
      correctAnswer: "B",
      explanation: "Pelayanan inklusif untuk kelompok rentan adalah praktik pelayanan prima (bobot 5).",
    },
    {
      question: "Saya diminta lembur tanpa kompensasi. Saya...",
      optionA: "Tolak total",
      optionB: "Bantu untuk urgensi tertentu sambil komunikasikan kebutuhan kompensasi sesuai aturan",
      optionC: "Pura-pura tidak bisa",
      optionD: "Mengeluh ke media",
      optionE: "Resign",
      correctAnswer: "B",
      explanation: "Profesional: balance antara dedikasi dan hak. Komunikasi transparan adalah jalan tengah (bobot 5).",
    },
    {
      question: "Saya mendapatkan apresiasi atas kerja tim. Saya...",
      optionA: "Klaim sebagai keberhasilan pribadi",
      optionB: "Akui kontribusi tim secara terbuka dan bagi apresiasi kepada anggota",
      optionC: "Diam saja",
      optionD: "Pamer ke media sosial",
      optionE: "Tolak apresiasi",
      correctAnswer: "B",
      explanation: "Kepemimpinan rendah hati: prestasi tim adalah milik bersama (bobot 5).",
    },
  ],
};

export default bank;
