import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Dalam tim saya ada perbedaan pendapat yang tajam. Saya...",
      optionA: "Memenangkan pendapat saya dengan keras",
      optionB: "Membuka diskusi terstruktur, dengarkan semua, cari titik temu berbasis data",
      optionC: "Voting cepat",
      optionD: "Diam saja",
      optionE: "Mundur dari diskusi",
      correctAnswer: "B",
      explanation: "Kolaborasi sehat butuh dialog terstruktur dan keputusan berbasis data (bobot 5).",
    },
    {
      question: "Anggota tim baru tampak kesulitan beradaptasi. Saya...",
      optionA: "Biarkan saja",
      optionB: "Aktif menyapa, jadi mentor, dan bantu memahami kultur tim",
      optionC: "Lapor atasan",
      optionD: "Mengeluh ke rekan lain",
      optionE: "Anggap dia harus bisa sendiri",
      correctAnswer: "B",
      explanation: "Onboarding informal yang ramah membangun jejaring yang kuat sejak awal (bobot 5).",
    },
    {
      question: "Saya butuh data dari unit lain yang sulit dihubungi. Saya...",
      optionA: "Lapor ke atasan untuk perintahkan",
      optionB: "Bangun komunikasi personal dulu, jelaskan kebutuhan, baru jalur formal jika perlu",
      optionC: "Ambil paksa",
      optionD: "Menyerah",
      optionE: "Cari data dari sumber lain tidak resmi",
      correctAnswer: "B",
      explanation: "Pendekatan kolaboratif & komunikasi personal lebih efektif sebelum eskalasi (bobot 5).",
    },
    {
      question: "Saat rapat lintas instansi, ada pihak yang dominan dan menutup diskusi. Saya...",
      optionA: "Diam saja",
      optionB: "Ajukan pertanyaan terbuka untuk memberi ruang pihak lain bicara",
      optionC: "Konfrontasi langsung",
      optionD: "Mengeluh setelah rapat",
      optionE: "Walk out",
      correctAnswer: "B",
      explanation: "Fasilitasi inklusi pendapat melalui pertanyaan terbuka adalah skill kolaborasi penting (bobot 5).",
    },
    {
      question: "Rekan saya kurang memahami teknologi baru. Saya...",
      optionA: "Mengejek",
      optionB: "Tawarkan bantuan/training kecil dengan sabar",
      optionC: "Ambil alih pekerjaannya",
      optionD: "Biarkan",
      optionE: "Lapor atasan",
      correctAnswer: "B",
      explanation: "Knowledge sharing dan empati membangun kapasitas tim secara kolektif (bobot 5).",
    },
    {
      question: "Tim saya mendapat proyek dengan deadline ketat. Saya...",
      optionA: "Kerja sendiri sampai selesai",
      optionB: "Pecah tugas berdasar kekuatan masing-masing & pantau progres bersama",
      optionC: "Beban semua ke satu orang ahli",
      optionD: "Tunda mulai",
      optionE: "Mengeluh ke pimpinan",
      correctAnswer: "B",
      explanation: "Distribusi kerja berbasis kompetensi + kontrol progres = manajemen tim efektif (bobot 5).",
    },
    {
      question: "Saya sangat berbeda pandangan politik dengan rekan kerja. Saya...",
      optionA: "Berdebat panas tiap hari",
      optionB: "Hormati perbedaan, fokus pada profesionalisme kerja",
      optionC: "Hindari rekan tersebut total",
      optionD: "Lapor HR",
      optionE: "Sebar pandangan saya",
      correctAnswer: "B",
      explanation: "Profesionalisme: pisahkan pandangan personal dengan kolaborasi kerja (bobot 5).",
    },
    {
      question: "Atasan saya kurang komunikatif. Saya...",
      optionA: "Mengeluh ke rekan",
      optionB: "Inisiatif komunikasi reguler — laporan progres berkala dan minta feedback",
      optionC: "Ikut diam",
      optionD: "Bypass ke pejabat lebih atas",
      optionE: "Resign",
      correctAnswer: "B",
      explanation: "Kepemimpinan ke atas: bangun komunikasi proaktif dengan atasan untuk alignment (bobot 5).",
    },
    {
      question: "Kantor mengadakan kegiatan team building. Saya...",
      optionA: "Tolak karena buang waktu",
      optionB: "Hadir dengan partisipasi aktif untuk pererat tim",
      optionC: "Hadir tapi pasif",
      optionD: "Datang terlambat",
      optionE: "Pura-pura sakit",
      correctAnswer: "B",
      explanation: "Team building = investasi modal sosial tim. Partisipasi aktif penting (bobot 5).",
    },
    {
      question: "Saya mendapat email kasar dari unit lain. Saya...",
      optionA: "Balas dengan kasar",
      optionB: "Tunggu emosi reda, balas profesional, dan lakukan klarifikasi telepon/tatap muka",
      optionC: "Forward ke atasan untuk ditangani",
      optionD: "Diamkan",
      optionE: "Sebar email tersebut",
      correctAnswer: "B",
      explanation: "Komunikasi profesional di tengah konflik membutuhkan jeda emosi & klarifikasi langsung (bobot 5).",
    },
  ],
  ujian: [
    {
      question: "Saat presentasi tim, salah satu anggota tampil buruk. Saya...",
      optionA: "Permalukan saat itu juga",
      optionB: "Bantu menyelesaikan presentasi, evaluasi konstruktif setelah selesai",
      optionC: "Diam",
      optionD: "Salahkan ke audience",
      optionE: "Pura-pura tidak kenal",
      correctAnswer: "B",
      explanation: "Solidaritas tim di depan publik + feedback konstruktif privat = kepemimpinan dewasa (bobot 5).",
    },
    {
      question: "Saya bertemu kolega dari instansi lain di acara informal. Saya...",
      optionA: "Hindari karena tidak ada kepentingan",
      optionB: "Bangun relasi profesional dengan obrolan ringan dan tukar kontak",
      optionC: "Hanya basa-basi",
      optionD: "Diam saja",
      optionE: "Pulang lebih awal",
      correctAnswer: "B",
      explanation: "Networking organik di acara informal membuka kolaborasi lintas instansi di masa depan (bobot 5).",
    },
    {
      question: "Saya butuh meminta bantuan dari rekan yang kurang akrab. Saya...",
      optionA: "Bersikap memerintah",
      optionB: "Sapa dulu, jelaskan konteks, dan minta dengan sopan",
      optionC: "Suruh orang lain saja",
      optionD: "Lewatkan permintaan",
      optionE: "Mengancam",
      correctAnswer: "B",
      explanation: "Sopan santun & kontekstualisasi membuat kolaborasi mudah meski belum akrab (bobot 5).",
    },
    {
      question: "Tim saya selalu konflik internal. Saya selaku anggota...",
      optionA: "Pilih sisi terkuat",
      optionB: "Inisiatif retrospective: identifikasi root cause, ajukan solusi sistemik",
      optionC: "Diam",
      optionD: "Mengeluh keluar tim",
      optionE: "Tunggu konflik selesai sendiri",
      correctAnswer: "B",
      explanation: "Pendekatan sistemik dengan retrospective adalah cara dewasa menyelesaikan konflik tim (bobot 5).",
    },
    {
      question: "Atasan saya beralih dengan gaya kepemimpinan baru yang berbeda. Saya...",
      optionA: "Resisten total",
      optionB: "Adaptasi, pelajari preferensi, dan bangun hubungan kerja produktif",
      optionC: "Mengeluh ke rekan",
      optionD: "Tetap pakai cara lama",
      optionE: "Pindah unit",
      correctAnswer: "B",
      explanation: "Adaptabilitas terhadap gaya kepemimpinan = profesionalisme (bobot 5).",
    },
    {
      question: "Saya bekerja dengan pegawai dari latar belakang budaya berbeda. Saya...",
      optionA: "Hindari interaksi",
      optionB: "Pelajari budayanya, hargai perbedaan, dan jadikan kekayaan tim",
      optionC: "Memaksakan budaya saya",
      optionD: "Anggap mereka asing",
      optionE: "Buat lelucon stereotip",
      correctAnswer: "B",
      explanation: "Cultural intelligence (CQ) adalah skill jejaring kerja modern (bobot 5).",
    },
    {
      question: "Saya kena marah atasan padahal kesalahan ada di sistem. Saya...",
      optionA: "Diam menerima",
      optionB: "Setelah atasan tenang, jelaskan dengan data dan ajukan perbaikan sistem",
      optionC: "Lawan saat itu juga",
      optionD: "Salahkan rekan",
      optionE: "Resign",
      correctAnswer: "B",
      explanation: "Komunikasi setelah jeda emosi dengan data adalah pendekatan profesional (bobot 5).",
    },
    {
      question: "Saya diminta jadi mentor pegawai baru. Saya...",
      optionA: "Tolak karena sibuk",
      optionB: "Terima dengan persiapan: jadwal mentoring, materi, dan goals jelas",
      optionC: "Terima asal-asalan",
      optionD: "Suruh dia belajar sendiri",
      optionE: "Limpahkan ke rekan lain",
      correctAnswer: "B",
      explanation: "Mentoring terstruktur membangun kapasitas organisasi & relasi jangka panjang (bobot 5).",
    },
    {
      question: "Rekan dari unit lain mengajukan kolaborasi proyek. Saya...",
      optionA: "Tolak karena tidak ada di KPI saya",
      optionB: "Pelajari relevansinya, diskusi dengan atasan, dan buka peluang kolaborasi",
      optionC: "Iya-iya saja",
      optionD: "Tunda terus",
      optionE: "Salah informasi sengaja",
      correctAnswer: "B",
      explanation: "Kolaborasi lintas-unit memperluas dampak organisasi. Filter relevan + alignment atasan (bobot 5).",
    },
    {
      question: "Saya melihat ide kreatif rekan diabaikan rapat. Saya...",
      optionA: "Diam",
      optionB: "Ajak diskusi balik dan dukung ide tersebut dengan elaborasi konstruktif",
      optionC: "Sebut ide itu sebagai ide saya",
      optionD: "Setuju saja meski ide bagus",
      optionE: "Sindir pemimpin rapat",
      correctAnswer: "B",
      explanation: "Allyship: dukung ide rekan agar tidak hilang, beri credit yang seharusnya (bobot 5).",
    },
    {
      question: "Komunikasi via grup WhatsApp tim sering ramai dan tidak fokus. Saya...",
      optionA: "Mute grup",
      optionB: "Usulkan aturan komunikasi grup dan pemisahan kanal teknis vs informal",
      optionC: "Keluar grup",
      optionD: "Spam balik",
      optionE: "Diamkan",
      correctAnswer: "B",
      explanation: "Disiplin komunikasi tim membutuhkan struktur dan aturan yang disepakati bersama (bobot 5).",
    },
    {
      question: "Saya butuh feedback atas kinerja saya. Saya...",
      optionA: "Tunggu performance review tahunan",
      optionB: "Aktif minta feedback berkala dari atasan & peer",
      optionC: "Tanyakan ke teman dekat saja",
      optionD: "Anggap diri sudah bagus",
      optionE: "Tidak peduli",
      correctAnswer: "B",
      explanation: "Growth mindset: aktif cari feedback adalah investasi karier (bobot 5).",
    },
    {
      question: "Rekan saya curhat masalah pribadi yang berat. Saya...",
      optionA: "Mengabaikan",
      optionB: "Dengarkan empatik, hormati privasi, sarankan bantuan profesional bila perlu",
      optionC: "Sebar ke rekan lain",
      optionD: "Beri solusi tanpa diminta",
      optionE: "Suruh kuat sendiri",
      correctAnswer: "B",
      explanation: "Empati dan menjaga rahasia adalah pondasi kepercayaan dalam tim (bobot 5).",
    },
    {
      question: "Saya berbeda level senior dengan tim. Saya yang lebih senior...",
      optionA: "Memerintah dengan otoritas",
      optionB: "Bersikap setara, sharing knowledge, dorong inisiatif anggota junior",
      optionC: "Hanya delegasi tanpa coaching",
      optionD: "Kontrol mikro setiap tugas",
      optionE: "Ambil semua kerjaan sendiri",
      correctAnswer: "B",
      explanation: "Leadership inklusif menumbuhkan tim, bukan menekan (bobot 5).",
    },
    {
      question: "Saya bekerja dengan rekan yang ekstra teliti dan lambat. Saya...",
      optionA: "Mengeluh",
      optionB: "Hargai ketelitiannya, sinkronkan ritme, tetapkan deadline parsial",
      optionC: "Ambil alih pekerjaannya",
      optionD: "Lapor atasan",
      optionE: "Tinggalkan",
      correctAnswer: "B",
      explanation: "Manajemen perbedaan ritme kerja: hargai kekuatan, atur ritme dengan timeline (bobot 5).",
    },
    {
      question: "Saya pemimpin proyek, tim demotivasi. Saya...",
      optionA: "Tekan dengan target lebih besar",
      optionB: "Lakukan one-on-one untuk pahami akar demotivasi & restrukturisasi pendekatan",
      optionC: "Ganti tim",
      optionD: "Hilang",
      optionE: "Tutup proyek",
      correctAnswer: "B",
      explanation: "Servant leadership: pahami penyebab dan dukung pemulihan motivasi (bobot 5).",
    },
    {
      question: "Saya tidak setuju dengan keputusan tim yang sudah final. Saya...",
      optionA: "Sabotase pelaksanaan",
      optionB: "Ekspresikan ketidaksetujuan secara terbuka di forum, lalu eksekusi keputusan tim",
      optionC: "Mundur dari tim",
      optionD: "Diam dan dendam",
      optionE: "Sebar isu negatif",
      correctAnswer: "B",
      explanation: "Disagree-and-commit: kritik di tahap diskusi, dukung keputusan setelah final (bobot 5).",
    },
    {
      question: "Saya bertemu pejabat tinggi di forum. Saya...",
      optionA: "Hindari karena gugup",
      optionB: "Sapa profesional, perkenalkan diri singkat, tukar kartu nama jika tepat",
      optionC: "Foto-foto saja",
      optionD: "Minta tolong sesuatu langsung",
      optionE: "Berlebihan menjilat",
      correctAnswer: "B",
      explanation: "Networking dengan profesionalisme & batasan etika membangun jaringan jangka panjang (bobot 5).",
    },
    {
      question: "Saya bekerja sama dengan vendor eksternal yang terlambat deliver. Saya...",
      optionA: "Putus kontrak langsung",
      optionB: "Diskusi root cause, tetapkan recovery plan, evaluasi formal jika berulang",
      optionC: "Mengeluh terus",
      optionD: "Diamkan",
      optionE: "Bayar lebih biar cepat",
      correctAnswer: "B",
      explanation: "Manajemen vendor: gali penyebab + recovery plan sebelum eskalasi atau pemutusan (bobot 5).",
    },
    {
      question: "Saya menjadi PIC acara besar. Saya...",
      optionA: "Kerjakan semua sendiri",
      optionB: "Bagi tugas berdasar kompetensi, tetapkan checkpoint, koordinasi reguler",
      optionC: "Delegasi total tanpa kontrol",
      optionD: "Improvisasi tanpa rencana",
      optionE: "Ikut perintah orang saja",
      correctAnswer: "B",
      explanation: "Project management: distribusi tugas + monitoring + komunikasi reguler = sukses acara (bobot 5).",
    },
    {
      question: "Saya melihat ada bullying di tempat kerja. Saya...",
      optionA: "Diam",
      optionB: "Dukung korban privat, lapor jalur resmi, dorong kebijakan anti-bullying",
      optionC: "Ikut tertawa",
      optionD: "Salahkan korban",
      optionE: "Pindah unit",
      correctAnswer: "B",
      explanation: "Bystander intervention dengan saluran resmi adalah tanggung jawab semua anggota tim (bobot 5).",
    },
    {
      question: "Saya akan pindah ke unit lain. Saya...",
      optionA: "Pergi diam-diam",
      optionB: "Lakukan handover komprehensif, dokumentasikan, dan jaga relasi",
      optionC: "Tinggalkan tanggung jawab",
      optionD: "Sebar info negatif unit lama",
      optionE: "Ambil semua dokumen",
      correctAnswer: "B",
      explanation: "Etika transisi yang baik membangun reputasi profesional jangka panjang (bobot 5).",
    },
    {
      question: "Saya bekerja remote dengan tim. Saya...",
      optionA: "Komunikasi minim",
      optionB: "Aktif komunikasi via tools yang disepakati, hadir di sync meeting tepat waktu",
      optionC: "Hilang seharian",
      optionD: "Rapat tanpa kamera",
      optionE: "Balas pesan kapan suka",
      correctAnswer: "B",
      explanation: "Remote work butuh disiplin komunikasi tinggi untuk koordinasi tim efektif (bobot 5).",
    },
    {
      question: "Saya ditunjuk juru bicara tim untuk media. Saya...",
      optionA: "Asal jawab",
      optionB: "Persiapkan key messages, koordinasi dengan tim, sampaikan dengan akurat",
      optionC: "Improvisasi total",
      optionD: "Tolak tugas",
      optionE: "Bocorkan info internal",
      correctAnswer: "B",
      explanation: "Komunikasi publik: prepared messages + alignment internal = profesional (bobot 5).",
    },
    {
      question: "Atasan baru menggantikan atasan lama yang dekat dengan saya. Saya...",
      optionA: "Membandingkan terus",
      optionB: "Buka diri, bangun relasi baru dari nol secara profesional",
      optionC: "Resisten",
      optionD: "Bersikap dingin",
      optionE: "Sebar negatif",
      correctAnswer: "B",
      explanation: "Adaptabilitas relasi & openness = ASN profesional (bobot 5).",
    },
    {
      question: "Saya memimpin rapat tetapi peserta sering interupsi. Saya...",
      optionA: "Marah",
      optionB: "Buat aturan rapat di awal: parking lot untuk topik di luar agenda",
      optionC: "Tutup rapat",
      optionD: "Diamkan",
      optionE: "Larang berbicara",
      correctAnswer: "B",
      explanation: "Facilitation skill: aturan & parking lot menjaga rapat fokus tanpa menyensor (bobot 5).",
    },
    {
      question: "Saya mendapat tugas yang tumpang tindih dengan unit lain. Saya...",
      optionA: "Klaim semua tugas",
      optionB: "Koordinasi dengan unit lain, tetapkan pembagian peran tertulis",
      optionC: "Lewatkan ke mereka",
      optionD: "Adu domba",
      optionE: "Lakukan dua kali",
      correctAnswer: "B",
      explanation: "Tugas overlap diselesaikan dengan koordinasi dan kesepakatan tertulis (bobot 5).",
    },
    {
      question: "Tim saya merayakan keberhasilan. Saya...",
      optionA: "Tidak ikut",
      optionB: "Hadir dan apresiasi kontribusi tiap anggota dengan tulus",
      optionC: "Klaim sebagai jasa pribadi",
      optionD: "Tunjukkan iri",
      optionE: "Sindir yang kurang kontribusi",
      correctAnswer: "B",
      explanation: "Apresiasi tulus memperkuat ikatan dan motivasi tim untuk proyek selanjutnya (bobot 5).",
    },
    {
      question: "Saya mendapat tugas yang membutuhkan pengetahuan teknis di luar saya. Saya...",
      optionA: "Tutupi ketidaktahuan",
      optionB: "Akui keterbatasan dan ajak pakar internal/eksternal kolaborasi",
      optionC: "Kerjakan asal-asalan",
      optionD: "Tunda terus",
      optionE: "Tolak total",
      correctAnswer: "B",
      explanation: "Ego rendah + kolaborasi pakar = hasil kerja bermutu (bobot 5).",
    },
    {
      question: "Saya berkomunikasi via email dengan kolega lintas zona waktu. Saya...",
      optionA: "Kirim spam jam 03:00",
      optionB: "Sesuaikan jam pengiriman, gunakan timestamp jelas, dan beri due date eksplisit",
      optionC: "Email sembarangan",
      optionD: "Telepon malam",
      optionE: "Tunggu mereka kontak duluan",
      correctAnswer: "B",
      explanation: "Etika komunikasi cross-timezone: thoughtful timing + clarity (bobot 5).",
    },
  ],
};

export default bank;
