import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Pancasila sebagai dasar negara Indonesia secara resmi disahkan pada tanggal...",
      optionA: "1 Juni 1945",
      optionB: "22 Juni 1945",
      optionC: "17 Agustus 1945",
      optionD: "18 Agustus 1945",
      optionE: "29 Mei 1945",
      correctAnswer: "D",
      explanation:
        "Pancasila disahkan oleh PPKI pada 18 Agustus 1945, satu hari setelah proklamasi kemerdekaan, bersamaan dengan pengesahan UUD 1945.",
    },
    {
      question: "Sila ke-4 Pancasila berbunyi...",
      optionA: "Ketuhanan Yang Maha Esa",
      optionB: "Kemanusiaan yang adil dan beradab",
      optionC: "Persatuan Indonesia",
      optionD: "Kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan/perwakilan",
      optionE: "Keadilan sosial bagi seluruh rakyat Indonesia",
      correctAnswer: "D",
      explanation:
        "Sila ke-4 menekankan demokrasi musyawarah-mufakat, di mana keputusan diambil melalui perwakilan yang dipimpin oleh hikmat kebijaksanaan.",
    },
    {
      question: "Tokoh yang pertama kali mengusulkan istilah 'Pancasila' dalam sidang BPUPKI adalah...",
      optionA: "Mohammad Yamin",
      optionB: "Soepomo",
      optionC: "Soekarno",
      optionD: "Mohammad Hatta",
      optionE: "KH. Wahid Hasyim",
      correctAnswer: "C",
      explanation:
        "Pada pidato 1 Juni 1945, Soekarno mengusulkan lima dasar negara dan menamainya 'Pancasila' atas saran seorang ahli bahasa.",
    },
    {
      question: "Piagam Jakarta ditandatangani pada tanggal...",
      optionA: "1 Juni 1945",
      optionB: "22 Juni 1945",
      optionC: "17 Juli 1945",
      optionD: "18 Agustus 1945",
      optionE: "10 Juli 1945",
      correctAnswer: "B",
      explanation:
        "Piagam Jakarta disusun oleh Panitia Sembilan dan ditandatangani 22 Juni 1945. Dokumen ini menjadi cikal bakal Pembukaan UUD 1945.",
    },
    {
      question: "Nilai instrumental Pancasila adalah...",
      optionA: "Nilai dasar yang terkandung dalam sila-sila",
      optionB: "Penjabaran nilai dasar dalam UUD, undang-undang, dan kebijakan negara",
      optionC: "Nilai yang langsung dipraktikkan dalam kehidupan sehari-hari",
      optionD: "Nilai religius yang bersifat universal",
      optionE: "Nilai yang hanya berlaku untuk pejabat negara",
      correctAnswer: "B",
      explanation:
        "Nilai instrumental adalah penjabaran nilai dasar Pancasila ke dalam aturan hukum positif seperti UUD, UU, dan peraturan turunannya.",
    },
    {
      question: "Sila pertama Pancasila mengandung nilai...",
      optionA: "Demokrasi",
      optionB: "Religius/ketuhanan",
      optionC: "Kemanusiaan universal",
      optionD: "Keadilan sosial",
      optionE: "Persatuan",
      correctAnswer: "B",
      explanation:
        "Sila ke-1 'Ketuhanan Yang Maha Esa' menegaskan bahwa Indonesia adalah negara religius yang mengakui keberadaan Tuhan dan kebebasan beragama.",
    },
    {
      question: "Lambang sila ke-3 Pancasila adalah...",
      optionA: "Bintang",
      optionB: "Rantai",
      optionC: "Pohon Beringin",
      optionD: "Kepala Banteng",
      optionE: "Padi dan Kapas",
      correctAnswer: "C",
      explanation:
        "Pohon Beringin melambangkan sila ke-3 'Persatuan Indonesia' karena akarnya yang kokoh dan rindang menggambarkan tempat berteduh bersama.",
    },
    {
      question: "Pancasila berkedudukan sebagai sumber dari segala sumber hukum di Indonesia. Hal ini ditegaskan dalam...",
      optionA: "UU No. 12 Tahun 2011",
      optionB: "TAP MPR No. III/MPR/2000",
      optionC: "Pembukaan UUD 1945",
      optionD: "UUD 1945 Pasal 1",
      optionE: "Semua jawaban benar",
      correctAnswer: "A",
      explanation:
        "UU No. 12 Tahun 2011 tentang Pembentukan Peraturan Perundang-undangan Pasal 2 menegaskan Pancasila sebagai sumber dari segala sumber hukum negara.",
    },
    {
      question: "Sila yang melambangkan keadilan dalam distribusi kesejahteraan adalah sila ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "5",
      correctAnswer: "E",
      explanation:
        "Sila ke-5 'Keadilan sosial bagi seluruh rakyat Indonesia' menekankan pemerataan kesejahteraan dan keadilan ekonomi untuk semua warga.",
    },
    {
      question: "Fungsi Pancasila sebagai pandangan hidup bangsa berarti...",
      optionA: "Sumber hukum tertulis",
      optionB: "Pedoman dalam menyelesaikan masalah dan mencapai cita-cita bersama",
      optionC: "Lambang resmi negara",
      optionD: "Aturan baku yang tidak bisa diubah",
      optionE: "Sistem politik tunggal",
      correctAnswer: "B",
      explanation:
        "Sebagai way of life, Pancasila menjadi pegangan moral dan pedoman bersikap dalam menjawab tantangan kehidupan berbangsa.",
    },
  ],
  ujian: [
    {
      question: "Pidato Soekarno yang dikenal sebagai lahirnya Pancasila disampaikan pada...",
      optionA: "29 Mei 1945",
      optionB: "31 Mei 1945",
      optionC: "1 Juni 1945",
      optionD: "22 Juni 1945",
      optionE: "17 Juli 1945",
      correctAnswer: "C",
      explanation:
        "Pidato Soekarno pada sidang BPUPKI 1 Juni 1945 mengusulkan lima dasar negara dan kini diperingati sebagai Hari Lahir Pancasila.",
    },
    {
      question: "Panitia Sembilan dibentuk dengan tujuan...",
      optionA: "Menyusun teks proklamasi",
      optionB: "Menjembatani perbedaan pendapat tentang dasar negara",
      optionC: "Membentuk tentara nasional",
      optionD: "Mengatur pemilu pertama",
      optionE: "Menyusun UUD sementara",
      correctAnswer: "B",
      explanation:
        "Panitia Sembilan dipimpin Soekarno untuk merumuskan kompromi antara kelompok nasionalis dan Islam terkait dasar negara, hasilnya adalah Piagam Jakarta.",
    },
    {
      question: "Kalimat 'dengan kewajiban menjalankan syariat Islam bagi pemeluk-pemeluknya' dalam Piagam Jakarta dihapus pada...",
      optionA: "1 Juni 1945",
      optionB: "22 Juni 1945",
      optionC: "17 Agustus 1945",
      optionD: "18 Agustus 1945",
      optionE: "29 Agustus 1945",
      correctAnswer: "D",
      explanation:
        "Pada sidang PPKI 18 Agustus 1945, tujuh kata tersebut dihapus demi menjaga persatuan dan menghormati keberagaman umat beragama di Indonesia.",
    },
    {
      question: "Lambang sila ke-2 Pancasila adalah...",
      optionA: "Bintang",
      optionB: "Rantai",
      optionC: "Pohon Beringin",
      optionD: "Kepala Banteng",
      optionE: "Padi dan Kapas",
      correctAnswer: "B",
      explanation:
        "Rantai melambangkan sila ke-2 'Kemanusiaan yang adil dan beradab', mengandung makna hubungan antar manusia yang saling membantu.",
    },
    {
      question: "Pancasila sebagai ideologi terbuka berarti...",
      optionA: "Boleh diganti sewaktu-waktu",
      optionB: "Nilai dasarnya tetap, namun penjabarannya dapat berkembang sesuai zaman",
      optionC: "Bebas tanpa aturan",
      optionD: "Hanya berlaku di Jawa",
      optionE: "Sama dengan ideologi liberal",
      correctAnswer: "B",
      explanation:
        "Ideologi terbuka berarti nilai dasar Pancasila bersifat tetap, tetapi nilai instrumental dan praksisnya dapat dinamis menjawab tantangan zaman.",
    },
    {
      question: "Berikut yang BUKAN merupakan fungsi Pancasila adalah...",
      optionA: "Dasar negara",
      optionB: "Pandangan hidup bangsa",
      optionC: "Sumber hukum",
      optionD: "Bahasa nasional",
      optionE: "Perjanjian luhur bangsa",
      correctAnswer: "D",
      explanation:
        "Bahasa nasional adalah Bahasa Indonesia, bukan fungsi Pancasila. Fungsi Pancasila meliputi dasar negara, pandangan hidup, sumber hukum, perjanjian luhur, dan jiwa bangsa.",
    },
    {
      question: "Nilai praksis Pancasila tercermin dalam...",
      optionA: "Pembukaan UUD 1945",
      optionB: "Undang-undang",
      optionC: "Peraturan pemerintah",
      optionD: "Sikap dan perilaku nyata warga negara sehari-hari",
      optionE: "Pasal-pasal UUD",
      correctAnswer: "D",
      explanation:
        "Nilai praksis adalah realisasi konkret nilai dasar dan instrumental ke dalam tindakan sehari-hari, misal gotong royong, toleransi, dan musyawarah.",
    },
    {
      question: "Trisila yang diusulkan Soekarno meliputi sosio-nasionalisme, sosio-demokrasi, dan...",
      optionA: "Internasionalisme",
      optionB: "Mufakat",
      optionC: "Ketuhanan",
      optionD: "Kesejahteraan sosial",
      optionE: "Keadilan",
      correctAnswer: "C",
      explanation:
        "Soekarno menyederhanakan lima sila menjadi Trisila (sosio-nasionalisme, sosio-demokrasi, ketuhanan), bahkan menjadi Ekasila yaitu gotong royong.",
    },
    {
      question: "Sila yang sesuai dengan asas demokrasi Pancasila adalah sila ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "5",
      correctAnswer: "D",
      explanation:
        "Sila ke-4 'Kerakyatan...' adalah dasar demokrasi Pancasila yang menekankan musyawarah-mufakat dengan akal sehat dan kepentingan bersama.",
    },
    {
      question: "Sumpah Pemuda dicetuskan pada tahun...",
      optionA: "1908",
      optionB: "1920",
      optionC: "1928",
      optionD: "1945",
      optionE: "1950",
      correctAnswer: "C",
      explanation:
        "Sumpah Pemuda dicetuskan pada Kongres Pemuda II, 28 Oktober 1928, sebagai tonggak persatuan bangsa di bawah satu tanah air, satu bangsa, satu bahasa.",
    },
    {
      question: "Eka Prasetia Pancakarsa adalah...",
      optionA: "Sumpah pegawai negeri",
      optionB: "Tekad tunggal melaksanakan lima kehendak Pancasila",
      optionC: "Lambang TNI",
      optionD: "Mars Pancasila",
      optionE: "Pengganti UUD",
      correctAnswer: "B",
      explanation:
        "Eka Prasetia Pancakarsa diambil dari P4 (Pedoman Penghayatan dan Pengamalan Pancasila), berarti tekad tunggal untuk menjalankan lima kehendak (sila) Pancasila.",
    },
    {
      question: "Pancasila pertama kali dikukuhkan sebagai dasar negara melalui...",
      optionA: "Dekrit Presiden 5 Juli 1959",
      optionB: "Sidang PPKI 18 Agustus 1945",
      optionC: "Proklamasi Kemerdekaan",
      optionD: "Konferensi Meja Bundar",
      optionE: "TAP MPR 1973",
      correctAnswer: "B",
      explanation:
        "Dalam sidang PPKI 18 Agustus 1945, Pancasila resmi disahkan sebagai dasar negara bersama dengan UUD 1945.",
    },
    {
      question: "Implementasi sila ke-2 dalam kehidupan bermasyarakat adalah...",
      optionA: "Beribadah sesuai agama masing-masing",
      optionB: "Menghormati hak asasi setiap orang tanpa diskriminasi",
      optionC: "Mencintai produk dalam negeri",
      optionD: "Mengutamakan musyawarah",
      optionE: "Membayar pajak tepat waktu",
      correctAnswer: "B",
      explanation:
        "Sila ke-2 'Kemanusiaan yang adil dan beradab' tercermin dalam pengakuan persamaan derajat dan penghormatan HAM tanpa membedakan SARA.",
    },
    {
      question: "Yang dimaksud Pancasila sebagai 'genetivus subjectivus' adalah...",
      optionA: "Pancasila sebagai objek penelitian",
      optionB: "Pancasila sebagai dasar mengkaji ilmu lain",
      optionC: "Pancasila sebagai cabang filsafat",
      optionD: "Pancasila sebagai sastra",
      optionE: "Pancasila sebagai mitos",
      correctAnswer: "B",
      explanation:
        "Genetivus subjectivus berarti Pancasila menjadi alat/dasar untuk mengkaji ilmu pengetahuan dan realitas, bukan menjadi objek kajian.",
    },
    {
      question: "Pancasila bersumber pada nilai-nilai...",
      optionA: "Asing yang diadopsi",
      optionB: "Religius dan budaya bangsa Indonesia sendiri",
      optionC: "Kapitalisme Barat",
      optionD: "Komunisme Eropa Timur",
      optionE: "Liberalisme Amerika",
      correctAnswer: "B",
      explanation:
        "Pancasila digali dari nilai-nilai luhur yang sudah hidup dalam kebudayaan dan religiositas bangsa Indonesia jauh sebelum kemerdekaan.",
    },
    {
      question: "Hubungan kausal antara Pembukaan UUD 1945 dengan Pancasila bersifat...",
      optionA: "Saling bertentangan",
      optionB: "Tidak ada hubungan",
      optionC: "Pancasila terkandung dalam Pembukaan UUD alinea ke-4",
      optionD: "Hanya simbolis",
      optionE: "Pancasila lebih rendah dari UUD",
      correctAnswer: "C",
      explanation:
        "Lima sila Pancasila secara eksplisit tercantum dalam alinea ke-4 Pembukaan UUD 1945, menjadikan keduanya satu kesatuan tak terpisahkan.",
    },
    {
      question: "Berikut adalah ciri ideologi Pancasila, KECUALI...",
      optionA: "Bersumber dari nilai bangsa",
      optionB: "Bersifat terbuka",
      optionC: "Mengakui keberagaman",
      optionD: "Bersifat dogmatis kaku",
      optionE: "Berorientasi pada kemanusiaan",
      correctAnswer: "D",
      explanation:
        "Pancasila bersifat dinamis-terbuka, BUKAN dogmatis kaku. Nilai instrumental dan praksisnya bisa berkembang sesuai konteks zaman.",
    },
    {
      question: "Pancasila pernah menghadapi ancaman ideologis dalam peristiwa...",
      optionA: "G30S/PKI 1965",
      optionB: "Reformasi 1998",
      optionC: "Krisis moneter 1997",
      optionD: "Pemilu 1955",
      optionE: "Konferensi Asia Afrika",
      correctAnswer: "A",
      explanation:
        "G30S/PKI 1965 adalah upaya menggantikan Pancasila dengan ideologi komunisme. Pancasila kemudian diteguhkan kembali sebagai dasar negara.",
    },
    {
      question: "Pancasila sebagai paradigma pembangunan berarti...",
      optionA: "Pembangunan bidang ekonomi saja",
      optionB: "Setiap pembangunan harus selaras dengan nilai-nilai Pancasila",
      optionC: "Pembangunan diserahkan ke pasar",
      optionD: "Pembangunan tanpa perencanaan",
      optionE: "Pembangunan eksklusif untuk kelompok tertentu",
      correctAnswer: "B",
      explanation:
        "Sebagai paradigma pembangunan, Pancasila menjadi kerangka acuan supaya pembangunan berjalan adil, manusiawi, religius, dan demokratis.",
    },
    {
      question: "Asas kekeluargaan dalam ekonomi Indonesia bersumber pada Pancasila sila ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "5",
      correctAnswer: "E",
      explanation:
        "Pasal 33 UUD 1945 menyebut perekonomian disusun atas asas kekeluargaan, berakar pada sila ke-5 'Keadilan sosial bagi seluruh rakyat Indonesia'.",
    },
    {
      question: "Salah satu makna sila ke-3 'Persatuan Indonesia' adalah...",
      optionA: "Mengutamakan suku sendiri",
      optionB: "Membangun nasionalisme tanpa chauvinisme",
      optionC: "Menutup diri dari dunia luar",
      optionD: "Mengabaikan budaya daerah",
      optionE: "Menyamakan semua tradisi",
      correctAnswer: "B",
      explanation:
        "Sila ke-3 menanamkan cinta tanah air yang sehat — bangga sebagai Indonesia tanpa merendahkan bangsa lain (chauvinisme adalah nasionalisme sempit).",
    },
    {
      question: "Sumber tertib hukum tertinggi di Indonesia adalah...",
      optionA: "UU",
      optionB: "Peraturan Pemerintah",
      optionC: "Pancasila",
      optionD: "Keputusan Presiden",
      optionE: "Peraturan Daerah",
      correctAnswer: "C",
      explanation:
        "Pancasila adalah sumber dari segala sumber hukum (staatsfundamentalnorm), di atas UUD 1945 sebagai norma dasar tertulis tertinggi.",
    },
    {
      question: "Pancasila sebagai dasar negara berfungsi sebagai...",
      optionA: "Slogan saja",
      optionB: "Norma fundamental yang menjadi pijakan seluruh aturan negara",
      optionC: "Mata pelajaran sekolah",
      optionD: "Lagu kebangsaan",
      optionE: "Lambang partai",
      correctAnswer: "B",
      explanation:
        "Sebagai dasar negara, Pancasila menjadi norma fundamental — semua aturan hukum dan kebijakan harus tidak bertentangan dengan nilainya.",
    },
    {
      question: "Sila Pancasila yang mengandung nilai HAM paling kental adalah sila ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "5",
      correctAnswer: "B",
      explanation:
        "Sila ke-2 'Kemanusiaan yang adil dan beradab' adalah pijakan filosofis HAM di Indonesia — pengakuan martabat dan persamaan derajat manusia.",
    },
    {
      question: "Konsep 'Bhinneka Tunggal Ika' diambil dari kitab...",
      optionA: "Sutasoma karya Mpu Tantular",
      optionB: "Negarakertagama karya Mpu Prapanca",
      optionC: "Arjuna Wiwaha",
      optionD: "Smaradahana",
      optionE: "Bharatayuddha",
      correctAnswer: "A",
      explanation:
        "Bhinneka Tunggal Ika berasal dari kitab Sutasoma karya Mpu Tantular abad ke-14 (Majapahit), bermakna 'berbeda-beda tetapi tetap satu jua'.",
    },
    {
      question: "Tujuan negara Indonesia tercantum dalam Pembukaan UUD 1945 alinea ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "Tidak ada",
      correctAnswer: "D",
      explanation:
        "Alinea ke-4 Pembukaan menyebut empat tujuan negara: melindungi segenap bangsa, memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ketertiban dunia.",
    },
    {
      question: "Pancasila bersifat hierarkis-piramidal artinya...",
      optionA: "Sila-sila bertingkat dan saling melengkapi, sila ke-1 menjadi puncak",
      optionB: "Sila-sila bisa dipisah",
      optionC: "Sila ke-5 paling penting",
      optionD: "Setiap sila berdiri sendiri",
      optionE: "Tidak ada urutan",
      correctAnswer: "A",
      explanation:
        "Sila-sila Pancasila bersifat hierarkis-piramidal — sila ke-1 (Ketuhanan) menjiwai sila berikutnya, dan tiap sila merupakan pengkhususan sila sebelumnya.",
    },
    {
      question: "Arti 'beradab' dalam sila ke-2 Pancasila merujuk pada...",
      optionA: "Pakaian rapi",
      optionB: "Tindakan yang sesuai dengan akhlak, etika, dan martabat manusia",
      optionC: "Tata cara berbicara halus",
      optionD: "Berbahasa Jawa krama",
      optionE: "Kebiasaan adat istiadat",
      correctAnswer: "B",
      explanation:
        "'Beradab' berarti tindakan manusia yang mencerminkan akal budi, etika, dan menghargai harkat-martabat sesama, bukan sekadar tata krama luar.",
    },
    {
      question: "Tugas konstitusional pelaksanaan sila ke-1 dalam negara antara lain...",
      optionA: "Menetapkan agama tunggal",
      optionB: "Menjamin kemerdekaan tiap penduduk untuk memeluk agamanya",
      optionC: "Melarang ibadah",
      optionD: "Mendirikan kuil resmi",
      optionE: "Membuat hari besar partai",
      correctAnswer: "B",
      explanation:
        "Pasal 29 ayat (2) UUD 1945 menjamin setiap penduduk bebas memeluk agama dan beribadah menurut keyakinannya — implementasi sila ke-1.",
    },
    {
      question: "Yang BUKAN termasuk Sumpah Pemuda 1928 adalah...",
      optionA: "Bertumpah darah satu, tanah air Indonesia",
      optionB: "Berbangsa satu, bangsa Indonesia",
      optionC: "Berbahasa satu, bahasa Indonesia",
      optionD: "Berdasar satu, Pancasila",
      optionE: "Semua benar",
      correctAnswer: "D",
      explanation:
        "Sumpah Pemuda 1928 hanya tiga butir: tanah air, bangsa, dan bahasa Indonesia. Pancasila baru lahir 1945, jadi 'berdasar Pancasila' bukan bagian Sumpah Pemuda.",
    },
  ],
};

export default bank;
