import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "NKRI adalah singkatan dari...",
      optionA: "Negara Konstitusional Republik Indonesia",
      optionB: "Negara Kesatuan Republik Indonesia",
      optionC: "Negara Kerjasama Republik Indonesia",
      optionD: "Negara Kedaulatan Republik Indonesia",
      optionE: "Negara Komite Republik Indonesia",
      correctAnswer: "B",
      explanation: "NKRI = Negara Kesatuan Republik Indonesia, sesuai Pasal 1 ayat (1) UUD 1945.",
    },
    {
      question: "Bentuk negara Indonesia adalah negara kesatuan dengan sistem...",
      optionA: "Sentralisasi penuh",
      optionB: "Desentralisasi/otonomi daerah",
      optionC: "Federal",
      optionD: "Konfederasi",
      optionE: "Monarki",
      correctAnswer: "B",
      explanation: "NKRI menganut desentralisasi — pemerintah pusat memberikan otonomi seluas-luasnya kepada daerah (Pasal 18 UUD 1945).",
    },
    {
      question: "Wawasan Nusantara adalah cara pandang bangsa Indonesia yang...",
      optionA: "Memisahkan pulau-pulau",
      optionB: "Menjadikan kepulauan sebagai satu kesatuan politik, ekonomi, sosial-budaya, dan hankam",
      optionC: "Hanya fokus Jawa",
      optionD: "Mengabaikan laut",
      optionE: "Menyerahkan kedaulatan ke negara lain",
      correctAnswer: "B",
      explanation: "Wawasan Nusantara: cara pandang bangsa atas diri dan lingkungannya berdasar Pancasila & UUD 1945, mempersatukan ribuan pulau dalam satu kesatuan.",
    },
    {
      question: "Ketahanan nasional bersifat...",
      optionA: "Statis",
      optionB: "Dinamis dan komprehensif",
      optionC: "Militer saja",
      optionD: "Ekonomi saja",
      optionE: "Hanya simbolis",
      correctAnswer: "B",
      explanation: "Ketahanan Nasional bersifat dinamis dan terdiri dari banyak aspek (Astagatra: ideologi, politik, ekonomi, sosbud, hankam + tri gatra geografis).",
    },
    {
      question: "Bela negara adalah hak dan kewajiban setiap warga negara, ditegaskan dalam pasal...",
      optionA: "27 ayat (3)",
      optionB: "28A",
      optionC: "29",
      optionD: "30",
      optionE: "31",
      correctAnswer: "A",
      explanation: "Pasal 27 ayat (3) UUD 1945: 'Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara.'",
    },
    {
      question: "Komponen utama pertahanan negara adalah...",
      optionA: "Polisi",
      optionB: "TNI",
      optionC: "Satpam",
      optionD: "Linmas",
      optionE: "Bea Cukai",
      correctAnswer: "B",
      explanation: "UU Pertahanan: TNI adalah komponen utama, didukung Polri dan rakyat sebagai komponen cadangan/pendukung.",
    },
    {
      question: "Wawasan Nusantara menjadikan laut sebagai...",
      optionA: "Pemisah pulau",
      optionB: "Penghubung dan pemersatu pulau-pulau",
      optionC: "Daerah terlarang",
      optionD: "Wilayah asing",
      optionE: "Tidak penting",
      correctAnswer: "B",
      explanation: "Wawasan Nusantara melihat laut sebagai penghubung — Indonesia adalah negara kepulauan (archipelagic state) dengan laut sebagai pemersatu.",
    },
    {
      question: "Deklarasi Djuanda 13 Desember 1957 mengubah konsep wilayah Indonesia menjadi...",
      optionA: "Hanya daratan",
      optionB: "Negara kepulauan dengan laut sebagai bagian wilayah kedaulatan",
      optionC: "Negara federal",
      optionD: "Negara persemakmuran",
      optionE: "Negara konfederasi",
      correctAnswer: "B",
      explanation: "Deklarasi Djuanda menetapkan wilayah laut antar pulau adalah laut nasional, bukan laut bebas — diakui internasional via UNCLOS 1982.",
    },
    {
      question: "Bela negara non-militer dapat dilakukan dengan cara...",
      optionA: "Hanya pegang senjata",
      optionB: "Belajar tekun, taat hukum, melestarikan budaya, dan bayar pajak",
      optionC: "Demonstrasi anarkis",
      optionD: "Provokasi SARA",
      optionE: "Mengabaikan kewajiban",
      correctAnswer: "B",
      explanation: "Bela negara mencakup banyak bentuk: pendidikan, ketaatan hukum, pelestarian budaya, dan kewajiban warga seperti membayar pajak.",
    },
    {
      question: "Dasar hukum NKRI adalah...",
      optionA: "Hanya Pancasila",
      optionB: "Pancasila dan UUD 1945",
      optionC: "Hanya UUD",
      optionD: "TAP MPR",
      optionE: "Keppres",
      correctAnswer: "B",
      explanation: "NKRI berdiri atas dasar Pancasila (filosofis) dan UUD 1945 (yuridis-konstitusional).",
    },
  ],
  ujian: [
    {
      question: "Empat pilar berbangsa-bernegara Indonesia adalah Pancasila, UUD 1945, NKRI, dan...",
      optionA: "Bhinneka Tunggal Ika",
      optionB: "Sumpah Pemuda",
      optionC: "Proklamasi",
      optionD: "GBHN",
      optionE: "Kompas",
      correctAnswer: "A",
      explanation: "Empat Pilar MPR: Pancasila, UUD 1945, NKRI, Bhinneka Tunggal Ika — tonggak konsensus bernegara.",
    },
    {
      question: "Astagatra dalam ketahanan nasional terdiri dari tri gatra (geografi, demografi, SDA) dan panca gatra. Yang TIDAK termasuk panca gatra adalah...",
      optionA: "Ideologi",
      optionB: "Politik",
      optionC: "Ekonomi",
      optionD: "Geografi",
      optionE: "Sosial Budaya",
      correctAnswer: "D",
      explanation: "Geografi adalah TRI GATRA, bukan panca gatra. Panca gatra: ideologi, politik, ekonomi, sosbud, hankam.",
    },
    {
      question: "Wilayah laut Indonesia berdasarkan UNCLOS 1982 mencakup laut teritorial sejauh...",
      optionA: "3 mil dari pantai",
      optionB: "12 mil dari garis pangkal",
      optionC: "100 mil dari pantai",
      optionD: "200 mil dari pantai",
      optionE: "350 mil dari pantai",
      correctAnswer: "B",
      explanation: "Laut teritorial = 12 mil dari garis pangkal. ZEE = 200 mil. Landas kontinen bisa lebih dari 200 mil dengan klaim tambahan.",
    },
    {
      question: "Zona Ekonomi Eksklusif (ZEE) Indonesia memiliki batas...",
      optionA: "12 mil",
      optionB: "24 mil",
      optionC: "100 mil",
      optionD: "200 mil dari garis pangkal",
      optionE: "350 mil",
      correctAnswer: "D",
      explanation: "ZEE Indonesia 200 mil dari garis pangkal — wilayah eksklusif untuk eksploitasi SDA laut, ditetapkan UU No. 5/1983.",
    },
    {
      question: "Provinsi yang merupakan provinsi termuda Indonesia (per 2023) adalah...",
      optionA: "Papua Barat",
      optionB: "Papua Selatan",
      optionC: "Aceh",
      optionD: "Maluku Utara",
      optionE: "Banten",
      correctAnswer: "B",
      explanation: "Pemekaran Papua 2022: Papua Selatan, Papua Tengah, Papua Pegunungan, Papua Barat Daya — termasuk provinsi termuda Indonesia.",
    },
    {
      question: "Tujuan pembentukan otonomi daerah adalah...",
      optionA: "Memperlemah pusat",
      optionB: "Mendekatkan pelayanan publik dan memberdayakan daerah",
      optionC: "Memerdekakan provinsi",
      optionD: "Menggantikan UUD",
      optionE: "Privatisasi negara",
      correctAnswer: "B",
      explanation: "Otonomi daerah bertujuan mendekatkan pelayanan publik, mempercepat pembangunan, dan memberdayakan daerah dalam bingkai NKRI.",
    },
    {
      question: "TNI dan Polri pernah tergabung dalam ABRI dan kemudian dipisahkan pada tahun...",
      optionA: "1995",
      optionB: "1998",
      optionC: "1999",
      optionD: "2000",
      optionE: "2002",
      correctAnswer: "C",
      explanation: "Pemisahan TNI-Polri dilakukan tahun 1999 melalui TAP MPR No. VI/MPR/2000 dan UU No. 2/2002 (Polri) serta UU No. 34/2004 (TNI).",
    },
    {
      question: "Tugas pokok TNI adalah...",
      optionA: "Penegakan hukum sipil",
      optionB: "Menegakkan kedaulatan negara dan keutuhan wilayah dari ancaman militer",
      optionC: "Mengelola pajak",
      optionD: "Mengatur lalu lintas",
      optionE: "Menjaga pasar",
      correctAnswer: "B",
      explanation: "UU TNI No. 34/2004: tugas pokok TNI menegakkan kedaulatan, menjaga keutuhan wilayah, dan melindungi segenap bangsa dari ancaman militer.",
    },
    {
      question: "Tugas pokok Polri adalah...",
      optionA: "Menyerang negara lain",
      optionB: "Memelihara kamtibmas, menegakkan hukum, dan melayani-melindungi masyarakat",
      optionC: "Menjadi prajurit perang",
      optionD: "Mengelola perpustakaan",
      optionE: "Hanya simbolis",
      correctAnswer: "B",
      explanation: "UU Polri No. 2/2002: tugas Polri adalah Kamtibmas, penegakan hukum, dan perlindungan-pelayanan-pengayoman masyarakat.",
    },
    {
      question: "Hari Bela Negara diperingati setiap...",
      optionA: "1 Juni",
      optionB: "17 Agustus",
      optionC: "5 Oktober",
      optionD: "10 November",
      optionE: "19 Desember",
      correctAnswer: "E",
      explanation: "Hari Bela Negara diperingati 19 Desember, mengenang pembentukan PDRI di Bukittinggi (1948) saat agresi militer Belanda II.",
    },
    {
      question: "Hari TNI diperingati pada tanggal...",
      optionA: "1 Juni",
      optionB: "17 Agustus",
      optionC: "5 Oktober",
      optionD: "10 November",
      optionE: "21 Mei",
      correctAnswer: "C",
      explanation: "Hari TNI diperingati 5 Oktober, ditetapkan dari pembentukan TKR (cikal bakal TNI) tahun 1945.",
    },
    {
      question: "Konferensi Meja Bundar (KMB) menghasilkan pengakuan kedaulatan Indonesia oleh Belanda pada...",
      optionA: "17 Agustus 1945",
      optionB: "27 Desember 1949",
      optionC: "1 Mei 1963",
      optionD: "17 Agustus 1950",
      optionE: "1 Januari 1955",
      correctAnswer: "B",
      explanation: "27 Desember 1949: Belanda mengakui kedaulatan Republik Indonesia Serikat, hasil KMB Den Haag.",
    },
    {
      question: "Republik Indonesia Serikat (RIS) berubah kembali menjadi NKRI pada tanggal...",
      optionA: "27 Desember 1949",
      optionB: "17 Agustus 1950",
      optionC: "5 Juli 1959",
      optionD: "1 Juni 1945",
      optionE: "11 Maret 1966",
      correctAnswer: "B",
      explanation: "17 Agustus 1950 RIS dibubarkan dan kembali ke bentuk NKRI dengan UUDS 1950 sebagai konstitusinya.",
    },
    {
      question: "Dekrit Presiden 5 Juli 1959 berisi...",
      optionA: "Kembali ke UUD 1945",
      optionB: "Mengganti Pancasila",
      optionC: "Membubarkan TNI",
      optionD: "Mendirikan negara federal",
      optionE: "Membatalkan kemerdekaan",
      correctAnswer: "A",
      explanation: "Dekrit Soekarno 5 Juli 1959: bubarkan Konstituante, kembali ke UUD 1945, bentuk MPRS-DPAS.",
    },
    {
      question: "Wilayah Indonesia paling Utara adalah...",
      optionA: "Pulau Rondo (Aceh)",
      optionB: "Pulau Miangas (Sulut)",
      optionC: "Pulau Rote (NTT)",
      optionD: "Sabang",
      optionE: "Merauke",
      correctAnswer: "B",
      explanation: "Pulau Miangas di Sulawesi Utara adalah titik paling Utara Indonesia, berbatasan dengan Filipina.",
    },
    {
      question: "Wilayah paling Selatan Indonesia adalah...",
      optionA: "Pulau Rote (NTT)",
      optionB: "Pulau Rondo",
      optionC: "Pulau Bali",
      optionD: "Pulau Jawa",
      optionE: "Pulau Madura",
      correctAnswer: "A",
      explanation: "Pulau Rote di NTT adalah titik paling Selatan Indonesia.",
    },
    {
      question: "Salah satu ancaman terhadap NKRI yang bersifat ideologis adalah...",
      optionA: "Bencana alam",
      optionB: "Radikalisme dan terorisme yang ingin mengganti dasar negara",
      optionC: "Inflasi",
      optionD: "Banjir",
      optionE: "Kemacetan",
      correctAnswer: "B",
      explanation: "Radikalisme/terorisme yang menolak Pancasila adalah ancaman ideologis serius — ditangani dengan kontra-radikalisasi dan deradikalisasi.",
    },
    {
      question: "Ancaman terhadap NKRI bersifat multidimensi, meliputi...",
      optionA: "Hanya militer",
      optionB: "Militer dan non-militer (ekonomi, ideologi, sosial-budaya, siber)",
      optionC: "Hanya ekonomi",
      optionD: "Hanya budaya",
      optionE: "Tidak ada ancaman",
      correctAnswer: "B",
      explanation: "Ancaman modern bersifat hibrida: konvensional (militer) dan non-konvensional (siber, ekonomi, ideologi, narkoba, dll).",
    },
    {
      question: "Pendidikan kewarganegaraan bertujuan...",
      optionA: "Membentuk warga negara apatis",
      optionB: "Membentuk warga negara cerdas, kritis, dan cinta tanah air",
      optionC: "Mengajarkan radikalisme",
      optionD: "Hanya hafalan undang-undang",
      optionE: "Tanpa tujuan",
      correctAnswer: "B",
      explanation: "PKn membentuk warga negara yang cerdas, kritis, partisipatif, dan cinta tanah air dengan landasan Pancasila.",
    },
    {
      question: "Hari Pahlawan 10 November diperingati sebagai...",
      optionA: "Hari Sumpah Pemuda",
      optionB: "Pertempuran Surabaya melawan Sekutu/NICA tahun 1945",
      optionC: "Proklamasi",
      optionD: "Hari Bela Negara",
      optionE: "Hari Lahir Pancasila",
      correctAnswer: "B",
      explanation: "10 November diperingati sebagai Hari Pahlawan, mengenang Pertempuran Surabaya (Bung Tomo) melawan pasukan Sekutu-NICA tahun 1945.",
    },
    {
      question: "Sumber Daya Alam (SDA) Indonesia menurut Pasal 33 UUD 1945 dikelola untuk...",
      optionA: "Sebesar-besarnya kemakmuran rakyat",
      optionB: "Kepentingan asing",
      optionC: "Hanya kelompok elit",
      optionD: "Pribadi pejabat",
      optionE: "Tidak diatur",
      correctAnswer: "A",
      explanation: "Pasal 33 ayat (3): bumi, air, dan kekayaan alam dikuasai negara dan dipergunakan untuk sebesar-besarnya kemakmuran rakyat.",
    },
    {
      question: "Globalisasi membawa peluang sekaligus ancaman bagi NKRI. Salah satu ancaman adalah...",
      optionA: "Pasar lebih luas",
      optionB: "Erosi nilai budaya bangsa dan masuknya ideologi yang bertentangan dengan Pancasila",
      optionC: "Akses informasi",
      optionD: "Pertukaran ilmu",
      optionE: "Mobilitas wisata",
      correctAnswer: "B",
      explanation: "Globalisasi bisa mengikis nilai-nilai bangsa dan membawa ideologi anti-Pancasila bila tidak disikapi dengan literasi dan filter Pancasila.",
    },
    {
      question: "Proklamasi 17 Agustus 1945 dibacakan di...",
      optionA: "Lapangan Ikada",
      optionB: "Jl. Pegangsaan Timur No. 56, Jakarta",
      optionC: "Istana Merdeka",
      optionD: "Bukittinggi",
      optionE: "Yogyakarta",
      correctAnswer: "B",
      explanation: "Soekarno-Hatta memproklamasikan kemerdekaan di kediaman Soekarno, Jl. Pegangsaan Timur No. 56 (sekarang Tugu Proklamasi).",
    },
    {
      question: "Nasionalisme yang sehat tercermin dalam sikap...",
      optionA: "Mengejek bangsa lain",
      optionB: "Bangga sebagai bangsa Indonesia tanpa merendahkan bangsa lain",
      optionC: "Menutup diri dari dunia",
      optionD: "Menyerah pada penjajahan",
      optionE: "Menjual aset negara",
      correctAnswer: "B",
      explanation: "Nasionalisme Indonesia bersifat luas dan inklusif — bangga sebagai Indonesia, sekaligus menghormati kemerdekaan dan martabat bangsa lain.",
    },
    {
      question: "Komponen pendukung pertahanan negara meliputi...",
      optionA: "Hanya TNI",
      optionB: "SDM, SDA, sarana-prasarana, serta nilai dan kondisi geografis nasional",
      optionC: "Polisi",
      optionD: "Hanya menteri",
      optionE: "Hanya elit",
      correctAnswer: "B",
      explanation: "UU No. 23/2019: komponen pendukung pertahanan adalah seluruh SDM, SDA, sarana-prasarana, dan nilai-nilai nasional yang dapat dimobilisasi.",
    },
    {
      question: "Wajib militer di Indonesia berbentuk...",
      optionA: "Wajib seumur hidup",
      optionB: "Sukarela direkrut TNI atau Komponen Cadangan dengan pelatihan",
      optionC: "Diundang ke perang langsung",
      optionD: "Tidak ada sama sekali",
      optionE: "Diserahkan ke negara lain",
      correctAnswer: "B",
      explanation: "Indonesia tidak menerapkan wajib militer paksa. Komponen Cadangan (UU No. 23/2019) bersifat sukarela dengan pelatihan terstruktur.",
    },
    {
      question: "Indonesia berbatasan darat dengan negara berikut, KECUALI...",
      optionA: "Malaysia",
      optionB: "Papua Nugini",
      optionC: "Timor Leste",
      optionD: "Singapura",
      optionE: "Semua benar",
      correctAnswer: "D",
      explanation: "Indonesia berbatasan darat dengan Malaysia (Kalimantan), Papua Nugini (Papua), Timor Leste (NTT). Singapura hanya berbatasan laut.",
    },
    {
      question: "Politik luar negeri Indonesia bersifat...",
      optionA: "Blok Barat",
      optionB: "Blok Timur",
      optionC: "Bebas-aktif",
      optionD: "Isolasionis",
      optionE: "Imperialis",
      correctAnswer: "C",
      explanation: "Politik LN Indonesia bebas-aktif (Mohammad Hatta): tidak terikat blok manapun, aktif menciptakan perdamaian dunia.",
    },
    {
      question: "Tribrata adalah pedoman hidup...",
      optionA: "TNI",
      optionB: "Polri",
      optionC: "ASN",
      optionD: "DPR",
      optionE: "BUMN",
      correctAnswer: "B",
      explanation: "Tribrata adalah pedoman hidup Polri: rastra sewakottama (pelayan bangsa), nagara janottama (warga teladan), yana anucasanadharma (taat hukum).",
    },
    {
      question: "Peran ASN/PNS dalam menjaga NKRI antara lain...",
      optionA: "Korupsi",
      optionB: "Memberi pelayanan publik berintegritas dan netral politik",
      optionC: "Berpolitik praktis",
      optionD: "Menyebarkan hoaks",
      optionE: "Memihak satu golongan",
      correctAnswer: "B",
      explanation: "ASN sebagai abdi negara wajib netral, profesional, integritas tinggi, dan memberi pelayanan publik prima — kontribusi nyata menjaga NKRI.",
    },
  ],
};

export default bank;
