import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "Semboyan 'Bhinneka Tunggal Ika' tertulis dalam pita yang dicengkeram oleh...",
      optionA: "Macan",
      optionB: "Garuda Pancasila",
      optionC: "Banteng",
      optionD: "Naga",
      optionE: "Singa",
      correctAnswer: "B",
      explanation: "Garuda Pancasila mencengkeram pita bertuliskan 'Bhinneka Tunggal Ika' sebagai semboyan resmi negara.",
    },
    {
      question: "Bhinneka Tunggal Ika berasal dari bahasa...",
      optionA: "Sanskerta",
      optionB: "Jawa Kuno (Kawi)",
      optionC: "Bali Kuno",
      optionD: "Melayu",
      optionE: "Pali",
      correctAnswer: "B",
      explanation: "Bhinneka Tunggal Ika berbahasa Jawa Kuno (Kawi) dari Kitab Sutasoma karya Mpu Tantular.",
    },
    {
      question: "Arti harfiah Bhinneka Tunggal Ika adalah...",
      optionA: "Bersatu kita teguh",
      optionB: "Berbeda-beda tetapi tetap satu jua",
      optionC: "Satu untuk semua",
      optionD: "Bangsa yang besar",
      optionE: "Tanah airku Indonesia",
      correctAnswer: "B",
      explanation: "Bhinneka = beragam/berbeda, Tunggal = satu, Ika = itu — secara harfiah 'berbeda-beda tetapi tetap satu jua'.",
    },
    {
      question: "Multikulturalisme di Indonesia tercermin dari...",
      optionA: "Hanya satu suku dominan",
      optionB: "Keberagaman suku, agama, bahasa, dan budaya yang hidup berdampingan",
      optionC: "Penyeragaman budaya nasional",
      optionD: "Larangan bahasa daerah",
      optionE: "Hanya satu agama resmi",
      correctAnswer: "B",
      explanation: "Multikulturalisme menghargai keberagaman — Indonesia memiliki >1.300 suku, 6 agama resmi, dan ratusan bahasa daerah yang hidup harmonis.",
    },
    {
      question: "Toleransi antarumat beragama di Indonesia berdasarkan pada...",
      optionA: "Sila ke-1 Pancasila dan Pasal 29 UUD 1945",
      optionB: "Pasal 27 UUD 1945",
      optionC: "Pasal 33 UUD 1945",
      optionD: "TAP MPR",
      optionE: "Keputusan Menteri",
      correctAnswer: "A",
      explanation: "Sila ke-1 'Ketuhanan YME' dan Pasal 29 menjamin kemerdekaan tiap penduduk untuk memeluk agama dan beribadah menurut keyakinannya.",
    },
    {
      question: "Berikut bukan agama yang diakui resmi di Indonesia...",
      optionA: "Islam",
      optionB: "Kristen",
      optionC: "Hindu",
      optionD: "Yahudi",
      optionE: "Konghucu",
      correctAnswer: "D",
      explanation: "Enam agama resmi: Islam, Kristen Protestan, Katolik, Hindu, Buddha, Konghucu. Yahudi tidak termasuk.",
    },
    {
      question: "Sikap yang sesuai dengan semangat Bhinneka Tunggal Ika adalah...",
      optionA: "Memaksakan budaya sendiri",
      optionB: "Menghormati perbedaan dan berdialog",
      optionC: "Menolak budaya lain",
      optionD: "Mendiskriminasi minoritas",
      optionE: "Mempertahankan eksklusivitas suku",
      correctAnswer: "B",
      explanation: "Bhinneka Tunggal Ika menuntut sikap saling menghormati perbedaan, dialog konstruktif, dan menjaga persatuan dalam keberagaman.",
    },
    {
      question: "Konsep integrasi nasional yang sesuai semangat Bhinneka adalah...",
      optionA: "Asimilasi paksa",
      optionB: "Akulturasi yang saling memperkaya",
      optionC: "Penghapusan budaya minoritas",
      optionD: "Pemaksaan satu bahasa",
      optionE: "Segregasi etnis",
      correctAnswer: "B",
      explanation: "Akulturasi memperkaya budaya nasional tanpa menghilangkan identitas asli — pendekatan yang selaras dengan Bhinneka Tunggal Ika.",
    },
    {
      question: "Politik identitas yang berlebihan dapat...",
      optionA: "Memperkuat persatuan",
      optionB: "Mengancam integrasi nasional",
      optionC: "Tidak berdampak",
      optionD: "Menambah kekayaan budaya",
      optionE: "Diperlukan untuk demokrasi",
      correctAnswer: "B",
      explanation: "Politik identitas yang berlebihan memecah belah dan mengancam integrasi nasional — bertentangan dengan semangat Bhinneka Tunggal Ika.",
    },
    {
      question: "Bahasa Indonesia berfungsi sebagai bahasa pemersatu karena...",
      optionA: "Berasal dari satu suku saja",
      optionB: "Diadopsi sukarela sebagai bahasa nasional di Sumpah Pemuda 1928",
      optionC: "Dipaksakan kolonial",
      optionD: "Bahasa internasional",
      optionE: "Bahasa kuno",
      correctAnswer: "B",
      explanation: "Sumpah Pemuda 28 Oktober 1928 menjunjung 'bahasa persatuan, bahasa Indonesia' (akar Melayu) sebagai jembatan komunikasi antar suku.",
    },
  ],
  ujian: [
    {
      question: "Kitab Sutasoma karya Mpu Tantular ditulis pada masa kerajaan...",
      optionA: "Sriwijaya",
      optionB: "Mataram Kuno",
      optionC: "Singasari",
      optionD: "Majapahit",
      optionE: "Kediri",
      correctAnswer: "D",
      explanation: "Kitab Sutasoma ditulis Mpu Tantular pada abad ke-14, masa Kerajaan Majapahit di bawah Hayam Wuruk.",
    },
    {
      question: "Konteks asli kalimat Bhinneka Tunggal Ika di Sutasoma adalah toleransi antara...",
      optionA: "Hindu dan Islam",
      optionB: "Buddha dan Hindu",
      optionC: "Kristen dan Buddha",
      optionD: "Konghucu dan Hindu",
      optionE: "Animisme dan Hindu",
      correctAnswer: "B",
      explanation: "Sutasoma membahas toleransi antara umat Buddha dan Hindu di Majapahit — 'Rwâneka dhâtu winuwus Buddha Wiswa, Bhinnêki rakwa ring apan kena parwanosen, mangka ng Jinatwa kalawan Siwatatwa tunggal, Bhinneka Tunggal Ika tan hana dharma mangrwa.'",
    },
    {
      question: "Yang BUKAN faktor pendorong integrasi nasional adalah...",
      optionA: "Bahasa Indonesia sebagai bahasa pemersatu",
      optionB: "Pancasila sebagai dasar negara",
      optionC: "Sumpah Pemuda",
      optionD: "Egoisme kedaerahan",
      optionE: "Lambang Garuda Pancasila",
      correctAnswer: "D",
      explanation: "Egoisme/primordialisme kedaerahan justru menghambat integrasi nasional — bertentangan dengan persatuan.",
    },
    {
      question: "Pluralisme dalam konteks Indonesia berarti...",
      optionA: "Hanya satu agama benar",
      optionB: "Pengakuan dan penghargaan terhadap keberagaman sebagai kenyataan sosial",
      optionC: "Sinkretisme agama",
      optionD: "Penghapusan identitas",
      optionE: "Menyeragamkan budaya",
      correctAnswer: "B",
      explanation: "Pluralisme adalah pengakuan keberagaman dan upaya hidup damai dalam perbedaan, bukan pencampuran/penghapusan identitas.",
    },
    {
      question: "Konflik horizontal yang berbasis SARA dapat dicegah dengan...",
      optionA: "Diskriminasi terbalik",
      optionB: "Pendidikan multikultural dan dialog antarbudaya",
      optionC: "Memisahkan komunitas",
      optionD: "Sensor budaya",
      optionE: "Memperluas ujaran kebencian",
      correctAnswer: "B",
      explanation: "Pendidikan multikultural dan dialog antarbudaya membangun pemahaman lintas kelompok — kunci pencegahan konflik horizontal.",
    },
    {
      question: "UU yang mengatur penghapusan diskriminasi rasial dan etnis di Indonesia adalah...",
      optionA: "UU No. 39/1999",
      optionB: "UU No. 40/2008",
      optionC: "UU No. 12/2005",
      optionD: "UU No. 21/2007",
      optionE: "UU No. 11/2008",
      correctAnswer: "B",
      explanation: "UU No. 40 Tahun 2008 tentang Penghapusan Diskriminasi Ras dan Etnis adalah landasan hukum melawan diskriminasi rasial.",
    },
    {
      question: "Salah satu manifestasi sikap toleransi adalah...",
      optionA: "Mengganggu ibadah orang lain",
      optionB: "Membiarkan dan melindungi praktik keagamaan kelompok lain",
      optionC: "Memaksakan keyakinan",
      optionD: "Mengabaikan hari besar agama lain",
      optionE: "Mengkritik keras agama lain",
      correctAnswer: "B",
      explanation: "Toleransi sejati adalah membiarkan dan melindungi hak orang lain menjalankan keyakinannya tanpa gangguan.",
    },
    {
      question: "Berikut bahasa daerah yang penuturnya terbanyak di Indonesia...",
      optionA: "Bahasa Sunda",
      optionB: "Bahasa Jawa",
      optionC: "Bahasa Madura",
      optionD: "Bahasa Batak",
      optionE: "Bahasa Bugis",
      correctAnswer: "B",
      explanation: "Bahasa Jawa adalah bahasa daerah dengan penutur terbanyak (>80 juta), diikuti Sunda dan Madura.",
    },
    {
      question: "Kesatuan dalam keberagaman menjadi kekuatan jika...",
      optionA: "Setiap kelompok mempertahankan eksklusivitas",
      optionB: "Setiap kelompok menyumbangkan kekhasannya untuk kepentingan bersama",
      optionC: "Mayoritas mendominasi minoritas",
      optionD: "Identitas dilenyapkan",
      optionE: "Konflik dibiarkan",
      correctAnswer: "B",
      explanation: "Kekuatan Indonesia justru pada kontribusi unik setiap suku/budaya bagi kemajuan bersama, bukan eksklusivitas atau dominasi.",
    },
    {
      question: "Suku terbesar di Indonesia berdasarkan jumlah penduduk adalah...",
      optionA: "Sunda",
      optionB: "Jawa",
      optionC: "Batak",
      optionD: "Madura",
      optionE: "Minangkabau",
      correctAnswer: "B",
      explanation: "Suku Jawa adalah etnis terbesar di Indonesia, sekitar 40% populasi, terutama mendiami Pulau Jawa bagian tengah dan timur.",
    },
    {
      question: "Hari Bhinneka Tunggal Ika diperingati setiap tanggal...",
      optionA: "1 Juni",
      optionB: "17 Agustus",
      optionC: "28 Oktober",
      optionD: "10 November",
      optionE: "Belum ada hari resmi",
      correctAnswer: "E",
      explanation: "Belum ada hari resmi Bhinneka Tunggal Ika. Yang ada adalah Hari Lahir Pancasila (1 Juni) dan Sumpah Pemuda (28 Oktober).",
    },
    {
      question: "Akulturasi budaya yang baik ditandai dengan...",
      optionA: "Hilangnya budaya asli",
      optionB: "Saling memperkaya tanpa menghilangkan identitas dasar",
      optionC: "Dominasi budaya asing",
      optionD: "Penolakan total terhadap pengaruh luar",
      optionE: "Pemaksaan budaya populer",
      correctAnswer: "B",
      explanation: "Akulturasi yang sehat: budaya asli tetap utuh sambil menyerap unsur asing yang positif — bukan asimilasi total atau resistensi total.",
    },
    {
      question: "Yang termasuk modal sosial bangsa Indonesia adalah...",
      optionA: "Korupsi struktural",
      optionB: "Gotong royong dan kekeluargaan",
      optionC: "Individualisme",
      optionD: "Egoisme suku",
      optionE: "Sektarianisme",
      correctAnswer: "B",
      explanation: "Gotong royong dan semangat kekeluargaan adalah modal sosial khas Indonesia yang menopang persatuan dan pembangunan.",
    },
    {
      question: "Wujud pengamalan Bhinneka di sekolah adalah...",
      optionA: "Memilih teman dari suku sendiri saja",
      optionB: "Berteman tanpa membedakan SARA",
      optionC: "Mengejek dialek teman",
      optionD: "Tidak mengikuti hari besar agama lain",
      optionE: "Membentuk geng eksklusif",
      correctAnswer: "B",
      explanation: "Pertemanan inklusif lintas SARA adalah wujud nyata Bhinneka Tunggal Ika di lingkungan pendidikan.",
    },
    {
      question: "Identitas nasional adalah...",
      optionA: "Identitas suku tertentu yang dominan",
      optionB: "Karakteristik bersama yang membedakan bangsa Indonesia dari bangsa lain",
      optionC: "Hanya bahasa daerah",
      optionD: "Hanya seragam militer",
      optionE: "Pakaian artis",
      correctAnswer: "B",
      explanation: "Identitas nasional adalah ciri khas bangsa: Pancasila, UUD 1945, bahasa Indonesia, lambang Garuda, lagu Indonesia Raya, dan keberagaman budaya.",
    },
    {
      question: "Asimilasi budaya berbeda dengan akulturasi karena...",
      optionA: "Asimilasi memadukan dua budaya jadi budaya baru, identitas asal cenderung melebur",
      optionB: "Asimilasi tidak mengubah apapun",
      optionC: "Asimilasi sama dengan akulturasi",
      optionD: "Asimilasi menghapus salah satu budaya secara paksa",
      optionE: "Asimilasi hanya soal makanan",
      correctAnswer: "A",
      explanation: "Asimilasi: peleburan dua budaya menjadi satu identitas baru. Akulturasi: penambahan unsur tanpa kehilangan identitas asli.",
    },
    {
      question: "Bahasa nasional Indonesia menjadi alat...",
      optionA: "Diskriminasi",
      optionB: "Komunikasi resmi dan pemersatu antar suku",
      optionC: "Eksklusi minoritas",
      optionD: "Pengganti bahasa daerah",
      optionE: "Penghapus identitas",
      correctAnswer: "B",
      explanation: "Bahasa Indonesia berfungsi sebagai bahasa resmi negara dan alat komunikasi yang menghubungkan ratusan kelompok bahasa di Nusantara.",
    },
    {
      question: "Berikut adalah ancaman terhadap kebhinnekaan, KECUALI...",
      optionA: "Radikalisme",
      optionB: "Intoleransi",
      optionC: "Politisasi SARA",
      optionD: "Dialog antarbudaya",
      optionE: "Hoaks adu domba",
      correctAnswer: "D",
      explanation: "Dialog antarbudaya justru memperkuat kebhinnekaan. Empat lainnya adalah ancaman nyata bagi persatuan bangsa.",
    },
    {
      question: "Pelaksanaan ibadah agama lain di lingkungan kita seharusnya...",
      optionA: "Diganggu",
      optionB: "Dilarang",
      optionC: "Dihormati dan dilindungi",
      optionD: "Diabaikan total",
      optionE: "Dimusuhi",
      correctAnswer: "C",
      explanation: "Sila ke-1 Pancasila dan Pasal 29 UUD 1945 menuntut warga negara saling menghormati dan melindungi pelaksanaan ibadah antarumat.",
    },
    {
      question: "Wawasan kebangsaan yang sesuai Bhinneka adalah...",
      optionA: "Chauvinisme",
      optionB: "Nasionalisme inklusif yang menghargai keberagaman",
      optionC: "Etnosentrisme",
      optionD: "Sukuisme",
      optionE: "Primordialisme",
      correctAnswer: "B",
      explanation: "Nasionalisme Indonesia bersifat inklusif — bangga sebagai bangsa tanpa merendahkan kelompok lain di dalam dan luar negeri.",
    },
    {
      question: "Sumber kebudayaan nasional Indonesia adalah...",
      optionA: "Budaya asing yang diadopsi",
      optionB: "Puncak-puncak kebudayaan daerah seluruh Indonesia",
      optionC: "Hanya budaya Jawa",
      optionD: "Hanya budaya Bali",
      optionE: "Tidak ada",
      correctAnswer: "B",
      explanation: "Pasal 32 UUD 1945 menegaskan negara memajukan kebudayaan nasional yang bersumber pada kebudayaan daerah-daerah Nusantara.",
    },
    {
      question: "Tugas pemerintah dalam menjaga kebhinnekaan antara lain...",
      optionA: "Membatasi ekspresi budaya daerah",
      optionB: "Memajukan dan melindungi keberagaman dengan kebijakan inklusif",
      optionC: "Menyeragamkan adat",
      optionD: "Menutup tempat ibadah minoritas",
      optionE: "Mengabaikan kebudayaan",
      correctAnswer: "B",
      explanation: "Negara wajib memajukan kebudayaan dan melindungi minoritas — itu mandat konstitusi (Pasal 32) sekaligus tuntutan Bhinneka Tunggal Ika.",
    },
    {
      question: "Salah satu wujud konkret integrasi adalah...",
      optionA: "Migrasi sukarela antar daerah dan transmigrasi",
      optionB: "Pengusiran kelompok minoritas",
      optionC: "Pemisahan wilayah berdasar suku",
      optionD: "Larangan kawin antar suku",
      optionE: "Larangan bahasa daerah",
      correctAnswer: "A",
      explanation: "Migrasi dan transmigrasi membaurkan suku-suku Indonesia dan menciptakan komunitas baru yang plural — wujud integrasi.",
    },
    {
      question: "Kearifan lokal seperti 'Tepa Salira' bermakna...",
      optionA: "Berbagi makanan",
      optionB: "Tenggang rasa, mempertimbangkan perasaan orang lain",
      optionC: "Bertukar tempat tinggal",
      optionD: "Menari bersama",
      optionE: "Bekerja keras",
      correctAnswer: "B",
      explanation: "Tepa Salira adalah falsafah Jawa: tenggang rasa, mengukur diri dengan diri orang lain — esensi toleransi yang sesuai Bhinneka.",
    },
    {
      question: "Stereotip negatif terhadap suku tertentu sebaiknya...",
      optionA: "Disebarluaskan",
      optionB: "Dilawan dengan pemahaman dan perjumpaan langsung",
      optionC: "Dijadikan dasar kebijakan",
      optionD: "Dibiarkan",
      optionE: "Dipakai untuk humor publik",
      correctAnswer: "B",
      explanation: "Stereotip dibongkar dengan pendidikan, perjumpaan langsung, dan pengalaman antar kelompok — bukan dipelihara.",
    },
    {
      question: "Forum Kerukunan Umat Beragama (FKUB) bertugas...",
      optionA: "Mendukung satu agama saja",
      optionB: "Memfasilitasi dialog dan kerukunan antarumat beragama",
      optionC: "Membuat kebijakan ekonomi",
      optionD: "Mengelola pajak",
      optionE: "Menyusun UU",
      correctAnswer: "B",
      explanation: "FKUB dibentuk berdasarkan PB Menag-Mendagri 9-8/2006 untuk memfasilitasi dialog dan rekomendasi izin rumah ibadah.",
    },
    {
      question: "Penyebab utama disintegrasi bangsa adalah...",
      optionA: "Kesetaraan kesempatan",
      optionB: "Ketimpangan ekonomi-sosial dan politisasi SARA",
      optionC: "Bahasa pemersatu",
      optionD: "Pendidikan multikultural",
      optionE: "Toleransi",
      correctAnswer: "B",
      explanation: "Ketimpangan + politisasi SARA adalah pemicu disintegrasi paling sering. Solusinya pemerataan pembangunan dan pendidikan kewargaan.",
    },
    {
      question: "Sikap inklusif terhadap penyandang disabilitas adalah bagian dari...",
      optionA: "Bhinneka Tunggal Ika dan sila ke-2 Pancasila",
      optionB: "Hanya kebijakan pemerintah",
      optionC: "Tidak ada hubungan",
      optionD: "Hanya tugas ortu",
      optionE: "Hanya tugas dokter",
      correctAnswer: "A",
      explanation: "Inklusi disabilitas adalah perwujudan kemanusiaan yang adil-beradab (sila ke-2) dan kebhinnekaan dalam arti luas.",
    },
    {
      question: "Salah satu lambang Bhinneka di kehidupan sehari-hari adalah...",
      optionA: "Pakaian batik dengan motif beragam dari berbagai daerah",
      optionB: "Pakaian seragam tunggal",
      optionC: "Larangan pakaian adat",
      optionD: "Hanya satu warna pakaian",
      optionE: "Tidak ada",
      correctAnswer: "A",
      explanation: "Batik dengan motif berbagai daerah (warisan UNESCO) merepresentasikan keberagaman dalam satu identitas nasional.",
    },
    {
      question: "Nasionalisme Indonesia menurut Soekarno adalah nasionalisme yang...",
      optionA: "Sempit dan eksklusif",
      optionB: "Luas, kemanusiaan, dan menjadi bagian dari peri-kemanusiaan internasional",
      optionC: "Anti-asing total",
      optionD: "Mengisolasi diri",
      optionE: "Imperialistik",
      correctAnswer: "B",
      explanation: "Soekarno menekankan nasionalisme Indonesia yang luas (sosio-nasionalisme) — cinta tanah air sekaligus solidaritas internasional.",
    },
  ],
};

export default bank;
