import type { QuestionBank } from "../types";

const bank: QuestionBank = {
  latihan: [
    {
      question: "UUD 1945 disahkan sebagai konstitusi negara Indonesia pada tanggal...",
      optionA: "17 Agustus 1945",
      optionB: "18 Agustus 1945",
      optionC: "19 Agustus 1945",
      optionD: "1 September 1945",
      optionE: "5 Juli 1945",
      correctAnswer: "B",
      explanation: "UUD 1945 disahkan oleh PPKI pada 18 Agustus 1945 bersama Pancasila sebagai dasar negara.",
    },
    {
      question: "Amandemen UUD 1945 telah dilakukan sebanyak...",
      optionA: "Dua kali",
      optionB: "Tiga kali",
      optionC: "Empat kali",
      optionD: "Lima kali",
      optionE: "Enam kali",
      correctAnswer: "C",
      explanation: "Amandemen UUD 1945 dilakukan empat kali (1999, 2000, 2001, 2002) oleh MPR pada masa reformasi.",
    },
    {
      question: "Lembaga yang berwenang mengubah UUD 1945 adalah...",
      optionA: "DPR",
      optionB: "MPR",
      optionC: "Presiden",
      optionD: "MK",
      optionE: "DPD",
      correctAnswer: "B",
      explanation: "Pasal 3 UUD 1945 menegaskan MPR berwenang mengubah dan menetapkan UUD.",
    },
    {
      question: "Indonesia adalah negara hukum, dinyatakan dalam pasal...",
      optionA: "Pasal 1 ayat (1)",
      optionB: "Pasal 1 ayat (2)",
      optionC: "Pasal 1 ayat (3)",
      optionD: "Pasal 2 ayat (1)",
      optionE: "Pasal 27",
      correctAnswer: "C",
      explanation: "Pasal 1 ayat (3) UUD 1945 hasil amandemen ke-3 menyatakan: 'Negara Indonesia adalah negara hukum.'",
    },
    {
      question: "Hak warga negara untuk mendapat pendidikan dijamin dalam pasal...",
      optionA: "Pasal 27",
      optionB: "Pasal 28",
      optionC: "Pasal 29",
      optionD: "Pasal 31",
      optionE: "Pasal 33",
      correctAnswer: "D",
      explanation: "Pasal 31 UUD 1945 menjamin hak setiap warga negara mendapat pendidikan dan kewajiban negara membiayai pendidikan dasar.",
    },
    {
      question: "Sistem pemerintahan Indonesia menurut UUD 1945 adalah...",
      optionA: "Parlementer",
      optionB: "Presidensial",
      optionC: "Semi-presidensial",
      optionD: "Monarki konstitusional",
      optionE: "Komunis",
      correctAnswer: "B",
      explanation: "Indonesia menganut sistem presidensial — Presiden adalah kepala negara sekaligus kepala pemerintahan, dipilih langsung oleh rakyat.",
    },
    {
      question: "Pasal 33 UUD 1945 mengatur tentang...",
      optionA: "Hak asasi manusia",
      optionB: "Pertahanan negara",
      optionC: "Perekonomian dan kekayaan alam",
      optionD: "Pendidikan",
      optionE: "Agama",
      correctAnswer: "C",
      explanation: "Pasal 33 mengatur perekonomian disusun berdasarkan asas kekeluargaan, dan cabang produksi penting dikuasai negara untuk sebesar-besarnya kemakmuran rakyat.",
    },
    {
      question: "Lembaga yang menguji UU terhadap UUD 1945 adalah...",
      optionA: "MA",
      optionB: "MK",
      optionC: "DPR",
      optionD: "Presiden",
      optionE: "Komisi Yudisial",
      correctAnswer: "B",
      explanation: "Mahkamah Konstitusi (MK) berwenang melakukan pengujian (judicial review) UU terhadap UUD 1945.",
    },
    {
      question: "Pemilu Presiden langsung pertama kali dilaksanakan di Indonesia pada tahun...",
      optionA: "1999",
      optionB: "2002",
      optionC: "2004",
      optionD: "2009",
      optionE: "2014",
      correctAnswer: "C",
      explanation: "Pemilu Presiden secara langsung oleh rakyat pertama kali dilaksanakan tahun 2004 setelah amandemen ke-4 UUD 1945.",
    },
    {
      question: "Masa jabatan Presiden Indonesia adalah...",
      optionA: "4 tahun, dapat dipilih lagi tanpa batas",
      optionB: "5 tahun, dapat dipilih kembali untuk satu kali masa jabatan",
      optionC: "5 tahun, hanya satu periode",
      optionD: "6 tahun, dapat dipilih kembali",
      optionE: "7 tahun, dua periode",
      correctAnswer: "B",
      explanation: "Pasal 7 UUD 1945 hasil amandemen menetapkan masa jabatan Presiden 5 tahun dan dapat dipilih kembali hanya untuk satu kali masa jabatan.",
    },
  ],
  ujian: [
    {
      question: "Pembukaan UUD 1945 terdiri atas...",
      optionA: "2 alinea",
      optionB: "3 alinea",
      optionC: "4 alinea",
      optionD: "5 alinea",
      optionE: "6 alinea",
      correctAnswer: "C",
      explanation: "Pembukaan UUD 1945 terdiri dari 4 alinea yang memuat dasar pemikiran, pernyataan kemerdekaan, cita-cita, dan dasar negara.",
    },
    {
      question: "Pernyataan kemerdekaan secara terperinci tercantum dalam Pembukaan UUD 1945 alinea ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "Semua alinea",
      correctAnswer: "C",
      explanation: "Alinea ke-3 Pembukaan UUD 1945 berisi pernyataan kemerdekaan yang merupakan rahmat Tuhan YME.",
    },
    {
      question: "Tujuan negara melindungi segenap bangsa, memajukan kesejahteraan, mencerdaskan kehidupan bangsa, dan ikut serta ketertiban dunia tercantum di alinea ke-...",
      optionA: "1",
      optionB: "2",
      optionC: "3",
      optionD: "4",
      optionE: "Tidak ada",
      correctAnswer: "D",
      explanation: "Empat tujuan negara secara eksplisit ada di alinea ke-4 Pembukaan UUD 1945, sebelum penyebutan dasar negara Pancasila.",
    },
    {
      question: "Yang BUKAN merupakan lembaga negara hasil amandemen UUD 1945 adalah...",
      optionA: "DPD",
      optionB: "MK",
      optionC: "KY",
      optionD: "DPA",
      optionE: "Komisi Pemilihan Umum",
      correctAnswer: "D",
      explanation: "DPA (Dewan Pertimbangan Agung) justru DIHAPUS oleh amandemen ke-4 UUD 1945. DPD, MK, dan KY adalah lembaga BARU hasil amandemen.",
    },
    {
      question: "Bentuk negara Indonesia menurut Pasal 1 ayat (1) UUD 1945 adalah...",
      optionA: "Negara Federal",
      optionB: "Negara Kesatuan",
      optionC: "Negara Konfederasi",
      optionD: "Negara Bagian",
      optionE: "Negara Persemakmuran",
      correctAnswer: "B",
      explanation: "Pasal 1 ayat (1): 'Negara Indonesia ialah Negara Kesatuan, yang berbentuk Republik.'",
    },
    {
      question: "Kedaulatan berada di tangan rakyat dan dilaksanakan menurut UUD, ditegaskan dalam pasal...",
      optionA: "Pasal 1 ayat (1)",
      optionB: "Pasal 1 ayat (2)",
      optionC: "Pasal 2",
      optionD: "Pasal 3",
      optionE: "Pasal 4",
      correctAnswer: "B",
      explanation: "Pasal 1 ayat (2) UUD 1945 hasil amandemen ke-3: 'Kedaulatan berada di tangan rakyat dan dilaksanakan menurut Undang-Undang Dasar.'",
    },
    {
      question: "Hak Asasi Manusia diatur secara khusus dalam UUD 1945 pasal...",
      optionA: "27",
      optionB: "28A-28J",
      optionC: "29",
      optionD: "30",
      optionE: "31",
      correctAnswer: "B",
      explanation: "Pasal 28A-28J adalah penjabaran HAM dalam UUD 1945, ditambahkan melalui amandemen ke-2 tahun 2000.",
    },
    {
      question: "Anggota DPR dipilih melalui...",
      optionA: "Penunjukan presiden",
      optionB: "Pemilihan umum",
      optionC: "Penunjukan partai",
      optionD: "Sidang MPR",
      optionE: "Lottery",
      correctAnswer: "B",
      explanation: "Pasal 19 UUD 1945: anggota DPR dipilih melalui pemilihan umum yang diselenggarakan KPU.",
    },
    {
      question: "Hak budget (anggaran) merupakan kewenangan...",
      optionA: "MA",
      optionB: "Presiden",
      optionC: "DPR",
      optionD: "DPD",
      optionE: "MK",
      correctAnswer: "C",
      explanation: "DPR memiliki hak budget — RAPBN diajukan presiden tetapi harus dibahas dan disetujui DPR (Pasal 23 UUD 1945).",
    },
    {
      question: "Mahkamah Agung dipimpin oleh...",
      optionA: "Presiden",
      optionB: "Ketua DPR",
      optionC: "Ketua MA yang dipilih dari dan oleh hakim agung",
      optionD: "Menteri Hukum",
      optionE: "Jaksa Agung",
      correctAnswer: "C",
      explanation: "Pasal 24A ayat (4): Ketua dan Wakil Ketua MA dipilih dari dan oleh hakim agung.",
    },
    {
      question: "Pasal yang mengatur pertahanan dan keamanan negara adalah...",
      optionA: "Pasal 27",
      optionB: "Pasal 28",
      optionC: "Pasal 30",
      optionD: "Pasal 31",
      optionE: "Pasal 33",
      correctAnswer: "C",
      explanation: "Pasal 30 UUD 1945 mengatur pertahanan dan keamanan negara — usaha hankam dilaksanakan TNI dan Polri sebagai kekuatan utama serta rakyat sebagai pendukung.",
    },
    {
      question: "Bahasa negara menurut Pasal 36 adalah...",
      optionA: "Bahasa Daerah",
      optionB: "Bahasa Indonesia",
      optionC: "Bahasa Inggris",
      optionD: "Bahasa Melayu",
      optionE: "Bahasa Jawa",
      correctAnswer: "B",
      explanation: "Pasal 36 UUD 1945: 'Bahasa Negara ialah Bahasa Indonesia.'",
    },
    {
      question: "Lambang negara menurut Pasal 36A adalah...",
      optionA: "Bendera Merah Putih",
      optionB: "Garuda Pancasila",
      optionC: "Pohon Beringin",
      optionD: "Padi dan Kapas",
      optionE: "Tugu Monas",
      correctAnswer: "B",
      explanation: "Pasal 36A UUD 1945: 'Lambang Negara ialah Garuda Pancasila dengan semboyan Bhinneka Tunggal Ika.'",
    },
    {
      question: "Lagu kebangsaan Indonesia ditegaskan dalam pasal...",
      optionA: "35",
      optionB: "36",
      optionC: "36A",
      optionD: "36B",
      optionE: "36C",
      correctAnswer: "D",
      explanation: "Pasal 36B UUD 1945: 'Lagu Kebangsaan ialah Indonesia Raya.'",
    },
    {
      question: "Hak presiden untuk memberi grasi diatur dalam pasal...",
      optionA: "10",
      optionB: "12",
      optionC: "14",
      optionD: "16",
      optionE: "20",
      correctAnswer: "C",
      explanation: "Pasal 14 UUD 1945: Presiden memberi grasi dan rehabilitasi dengan memperhatikan pertimbangan MA.",
    },
    {
      question: "Berikut termasuk hak prerogatif Presiden, KECUALI...",
      optionA: "Mengangkat menteri",
      optionB: "Memberi grasi",
      optionC: "Membuat UU",
      optionD: "Mengangkat duta besar",
      optionE: "Memberi gelar tanda jasa",
      correctAnswer: "C",
      explanation: "Membuat UU adalah kewenangan DPR bersama Presiden — bukan hak prerogatif tunggal Presiden.",
    },
    {
      question: "Hierarki perundang-undangan tertinggi setelah UUD 1945 adalah...",
      optionA: "TAP MPR",
      optionB: "UU/Perpu",
      optionC: "PP",
      optionD: "Perpres",
      optionE: "Perda",
      correctAnswer: "A",
      explanation: "Menurut UU No. 12/2011, hierarki: UUD 1945 > TAP MPR > UU/Perpu > PP > Perpres > Perda Provinsi > Perda Kab/Kota.",
    },
    {
      question: "Pemberhentian Presiden hanya dapat diusulkan oleh...",
      optionA: "MA",
      optionB: "MK",
      optionC: "DPR ke MPR setelah putusan MK",
      optionD: "Rakyat langsung",
      optionE: "Menteri Dalam Negeri",
      correctAnswer: "C",
      explanation: "Pasal 7A-7B mengatur impeachment: DPR mengajukan pendapat ke MK, MK memutus, MPR memberhentikan dalam sidang.",
    },
    {
      question: "DPD memiliki kewenangan utama dalam bidang...",
      optionA: "Pertahanan",
      optionB: "Otonomi daerah dan hubungan pusat-daerah",
      optionC: "Perpajakan internasional",
      optionD: "Yudikatif",
      optionE: "Eksekutif",
      correctAnswer: "B",
      explanation: "DPD mengusulkan dan mengawasi UU terkait otonomi daerah, hubungan pusat-daerah, pengelolaan SDA, dan keuangan daerah (Pasal 22D).",
    },
    {
      question: "Setiap warga negara berhak mempertahankan hidup dijamin dalam pasal...",
      optionA: "27",
      optionB: "28A",
      optionC: "29",
      optionD: "30",
      optionE: "31",
      correctAnswer: "B",
      explanation: "Pasal 28A: 'Setiap orang berhak untuk hidup serta berhak mempertahankan hidup dan kehidupannya.'",
    },
    {
      question: "Negara menjamin kemerdekaan beragama menurut pasal...",
      optionA: "27",
      optionB: "28",
      optionC: "29",
      optionD: "30",
      optionE: "31",
      correctAnswer: "C",
      explanation: "Pasal 29 ayat (2): 'Negara menjamin kemerdekaan tiap-tiap penduduk untuk memeluk agamanya masing-masing dan untuk beribadat menurut agamanya...'",
    },
    {
      question: "Pemerintah daerah diatur dalam pasal...",
      optionA: "16",
      optionB: "18",
      optionC: "20",
      optionD: "22",
      optionE: "24",
      correctAnswer: "B",
      explanation: "Pasal 18 UUD 1945 mengatur pembagian wilayah Indonesia atas provinsi, kabupaten, kota, dan otonomi seluas-luasnya.",
    },
    {
      question: "Komisi Pemilihan Umum (KPU) bersifat...",
      optionA: "Berada di bawah Presiden",
      optionB: "Bersifat nasional, tetap, dan mandiri",
      optionC: "Berada di bawah DPR",
      optionD: "Tidak permanen",
      optionE: "Hanya ada di pusat",
      correctAnswer: "B",
      explanation: "Pasal 22E ayat (5): Pemilu diselenggarakan oleh suatu komisi yang bersifat nasional, tetap, dan mandiri (KPU).",
    },
    {
      question: "BPK bertugas memeriksa pengelolaan keuangan negara, hasilnya disampaikan ke...",
      optionA: "Presiden saja",
      optionB: "DPR, DPD, dan DPRD",
      optionC: "Mahkamah Agung",
      optionD: "Mahkamah Konstitusi",
      optionE: "Komisi Yudisial",
      correctAnswer: "B",
      explanation: "Pasal 23E ayat (2): hasil pemeriksaan BPK diserahkan kepada DPR, DPD, dan DPRD sesuai kewenangan.",
    },
    {
      question: "Komisi Yudisial bertugas...",
      optionA: "Memeriksa keuangan negara",
      optionB: "Mengusulkan calon hakim agung dan menjaga kehormatan hakim",
      optionC: "Membuat undang-undang",
      optionD: "Mengadili presiden",
      optionE: "Mengangkat menteri",
      correctAnswer: "B",
      explanation: "Pasal 24B: KY mengusulkan pengangkatan hakim agung dan menjaga kehormatan, keluhuran martabat, serta perilaku hakim.",
    },
    {
      question: "Yang BUKAN merupakan kewenangan MK adalah...",
      optionA: "Menguji UU terhadap UUD",
      optionB: "Memutus sengketa kewenangan lembaga negara",
      optionC: "Memutus pembubaran partai politik",
      optionD: "Memutus sengketa pemilu",
      optionE: "Memutus kasasi pidana",
      correctAnswer: "E",
      explanation: "Kasasi adalah kewenangan MA, bukan MK. MK hanya menangani perkara konstitusi (Pasal 24C).",
    },
    {
      question: "Wajib Belajar 9 tahun adalah implementasi pasal...",
      optionA: "27",
      optionB: "28",
      optionC: "29",
      optionD: "31",
      optionE: "33",
      correctAnswer: "D",
      explanation: "Pasal 31 ayat (2): 'Setiap warga negara wajib mengikuti pendidikan dasar dan pemerintah wajib membiayainya.'",
    },
    {
      question: "Anggaran pendidikan minimal yang ditetapkan UUD 1945 adalah...",
      optionA: "10% APBN",
      optionB: "15% APBN",
      optionC: "20% APBN",
      optionD: "25% APBN",
      optionE: "30% APBN",
      correctAnswer: "C",
      explanation: "Pasal 31 ayat (4): negara memprioritaskan anggaran pendidikan sekurang-kurangnya 20% dari APBN dan APBD.",
    },
    {
      question: "Pemilu di Indonesia berdasarkan asas...",
      optionA: "LUBER JURDIL",
      optionB: "MUSDIKARMA",
      optionC: "Demokrasi terpimpin",
      optionD: "Bebas terbatas",
      optionE: "Penunjukan",
      correctAnswer: "A",
      explanation: "Asas pemilu: Langsung, Umum, Bebas, Rahasia (LUBER) serta Jujur dan Adil (JURDIL) — Pasal 22E ayat (1).",
    },
    {
      question: "Wewenang membentuk UU berada di tangan...",
      optionA: "Presiden",
      optionB: "DPR",
      optionC: "MPR",
      optionD: "MA",
      optionE: "BPK",
      correctAnswer: "B",
      explanation: "Pasal 20 ayat (1): 'Dewan Perwakilan Rakyat memegang kekuasaan membentuk undang-undang' — bersama Presiden untuk persetujuan.",
    },
  ],
};

export default bank;
